import { VizScenario } from './types';

const BASE_NODES = [
	{ id: 'client', label: 'Client', kind: 'client' as const, x: 60, y: 170 },
	{ id: 'api', label: 'API Gateway', kind: 'service' as const, x: 220, y: 170 },
	{ id: 'core', label: 'Core Service', kind: 'compute' as const, x: 400, y: 110 },
	{ id: 'store', label: 'State Store', kind: 'storage' as const, x: 610, y: 110 },
	{ id: 'queue', label: 'Event Stream', kind: 'queue' as const, x: 400, y: 245 },
	{ id: 'consumer', label: 'Consumer', kind: 'service' as const, x: 610, y: 245 },
];

const BASE_EDGES = [
	{ id: 'e1', from: 'client', to: 'api', label: 'request' },
	{ id: 'e2', from: 'api', to: 'core', label: 'command' },
	{ id: 'e3', from: 'core', to: 'store', label: 'persist' },
	{ id: 'e4', from: 'core', to: 'queue', label: 'publish' },
	{ id: 'e5', from: 'queue', to: 'consumer', label: 'consume' },
];

const createScenario = (
	id: VizScenario['id'],
	title: string,
	category: VizScenario['category'],
	summary: string,
	step1Title: string,
	step2Title: string,
	deepDiveHint: string,
	tradeoffHint: string,
): VizScenario => ({
	id,
	title,
	category,
	summary,
	nodes: BASE_NODES,
	edges: BASE_EDGES,
	steps: [
		{
			id: `${id}-step-1`,
			title: step1Title,
			description: 'Request enters the system and reaches the coordination boundary.',
			durationMs: 2200,
			highlightNodeIds: ['client', 'api', 'core'],
			highlightEdgeIds: ['e1', 'e2'],
			messages: [{ id: `${id}-m1`, edgeId: 'e1', label: 'req', progress: 0 }],
			layers: {
				overview: 'Traffic is admitted, validated, and transformed before execution.',
				deepDive: `Ingress controls enforce correctness before side effects. ${deepDiveHint}`,
				tradeoffs:
					'Early validation improves reliability but can add latency at high throughput.',
			},
		},
		{
			id: `${id}-step-2`,
			title: step2Title,
			description: 'State changes and downstream propagation complete the cycle.',
			durationMs: 2600,
			highlightNodeIds: ['core', 'store', 'queue', 'consumer'],
			highlightEdgeIds: ['e3', 'e4', 'e5'],
			messages: [
				{ id: `${id}-m2`, edgeId: 'e3', label: 'write', progress: 0, color: '#8b5cf6' },
				{ id: `${id}-m3`, edgeId: 'e4', label: 'event', progress: 0, color: '#0ea5e9' },
			],
			layers: {
				overview: 'Durable write and stream propagation synchronize derived systems.',
				deepDive: `${deepDiveHint} Downstream consumers react to immutable events for replayability.`,
				tradeoffs: tradeoffHint,
			},
		},
	],
});

export const VIS_SCENARIOS: VizScenario[] = [
	createScenario(
		'kafka-flow',
		'Kafka Topic Replication Flow',
		'kafka',
		'Partition leader writes and followers replicate before committed consumption.',
		'Produce to partition leader',
		'Replicate and commit offset',
		'ISR membership controls commit visibility and read safety.',
		'High replication factor improves durability but increases write coordination cost.',
	),
	createScenario(
		'dtx-saga',
		'Distributed Transaction Saga',
		'distributed-transactions',
		'Orchestrated steps with compensating actions replace global two-phase lock.',
		'Start saga command',
		'Commit or compensate',
		'Saga state machine tracks per-step outcome and retry envelopes.',
		'Sagas maximize availability but can temporarily expose intermediate states.',
	),
	createScenario(
		'replication-path',
		'Replication Topology',
		'replication',
		'Primary writes propagate to replicas with lag-awareness and read routing.',
		'Write on primary',
		'Fan-out replication',
		'Replica lag metrics gate stale reads for strict consistency modes.',
		'Synchronous replication reduces data loss risk but increases tail latency.',
	),
	createScenario(
		'quorum-rw',
		'Quorum Reads and Writes',
		'quorum',
		'R + W > N guarantees overlap between write acknowledgements and reads.',
		'Write quorum achieved',
		'Read quorum resolves latest value',
		'Version vectors or timestamps arbitrate concurrent versions safely.',
		'Lower quorum improves availability but raises stale-read probability.',
	),
	createScenario(
		'vector-db-ingest',
		'Vector Database Retrieval Cycle',
		'vector-database',
		'Embedding ingest, index mutation, and nearest-neighbor retrieval.',
		'Embed and index document',
		'ANN search and rerank',
		'Hybrid sparse+dense retrieval improves recall on precise technical terms.',
		'Higher-dimensional embeddings improve fidelity but grow memory footprint.',
	),
	createScenario(
		'llm-pipeline',
		'LLM Inference Pipeline',
		'llm-pipeline',
		'Request transforms through prompt, retrieval, generation, and guardrails.',
		'Assemble prompt context',
		'Generate and post-process',
		'Token budget management and truncation policy control factual grounding.',
		'More context increases quality but can degrade latency and cost.',
	),
	createScenario(
		'retrieval-rag',
		'Retrieval System Query Path',
		'retrieval',
		'Query expansion, retrieval, reranking, and answer grounding.',
		'Expand and retrieve',
		'Rerank and compose answer',
		'Reranker confidence can trigger fallback to strict citation mode.',
		'Aggressive query expansion boosts recall but may lower precision.',
	),
	createScenario(
		'cap-failure',
		'CAP Under Network Partition',
		'cap',
		'Systems choose between consistency and availability during partitions.',
		'Partition detected',
		'Policy-based response',
		'Coordinator policies can switch modes per keyspace or endpoint criticality.',
		'Prioritizing availability keeps service up but can accept divergent writes.',
	),
	createScenario(
		'consensus-round',
		'Consensus Election Round',
		'consensus',
		'Leader election and log agreement in a majority-based protocol.',
		'Start election term',
		'Win majority and replicate log',
		'Term monotonicity and quorum intersection prevent split-brain commits.',
		'Short election timeout improves failover speed but may increase flapping.',
	),
	createScenario(
		'k8s-scheduling',
		'Kubernetes Scheduling Loop',
		'kubernetes',
		'Scheduler scores nodes, binds pods, and reacts to pressure signals.',
		'Filter and score nodes',
		'Bind pod and observe metrics',
		'Affinity, taints, and resource pressure influence placement decisions.',
		'Stricter affinity improves locality but can reduce scheduling flexibility.',
	),
	createScenario(
		'event-sourcing',
		'Event Sourcing Projection Flow',
		'event-sourcing',
		'Domain events append immutably and project into read models.',
		'Append domain event',
		'Project to materialized view',
		'Rebuild capability enables deterministic recovery and backfill evolution.',
		'Projection lag can delay read freshness while preserving write throughput.',
	),
];
