export const CONTENT_REVALIDATE_SECONDS = 60 * 60;
export const ARTICLE_REVALIDATE_SECONDS = 60 * 60;
export const FEED_CACHE_SECONDS = 60 * 60;
export const FEED_STALE_WHILE_REVALIDATE_SECONDS = 24 * 60 * 60;
export const SHORT_LIVED_API_CACHE_SECONDS = 15 * 60;
export const DAILY_API_CACHE_SECONDS = 24 * 60 * 60;
