import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useState, useMemo, useEffect } from 'react';
import { Container } from '../../components/container';
import { AppProvider } from '../../components/contexts/appContext';
import { Footer } from '../../components/footer';
import { Layout } from '../../components/layout';
import { MinimalPosts } from '../../components/minimal-posts';
import { Pagination } from '../../components/pagination';
import { PersonalHeader } from '../../components/personal-theme-header';
import { getFooterPosts } from '../../lib/api/footerData';
import {
PostFragment,
PublicationFragment,
TagPostsByPublicationDocument,
TagPostsByPublicationQuery,
TagPostsByPublicationQueryVariables,
} from '../../generated/graphql';

type Props = {
posts: PostFragment[];
footerPosts: PostFragment[];
publication: PublicationFragment;
tag: string;
};

const GENERAL = '__general__';
const PAGE_SIZE = 12;
const CLUSTER_PREVIEW = 6;

const toTitleCase = (str: string) =>
str.replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());

export default function Tag({ publication, posts, tag, footerPosts }: Props) {
const title = `#${tag} - ${publication.title}`;
const [activeSubTag, setActiveSubTag] = useState<string | null>(null);

const tagLabel = tag.replace(/-/g, ' ');

/** Group posts by their primary "other" tag (first tag that isn't the current tag). */
const { subTags, grouped } = useMemo(() => {
  const order: { slug: string; name: string }[] = [];
  const seen = new Set<string>();
  const map = new Map<string, PostFragment[]>();

  for (const post of posts) {
    const otherTags = (post.tags ?? []).filter(
      (t): t is NonNullable<typeof t> => !!t?.slug && t.slug !== tag,
    );
    const primary = otherTags[0];
    const key = primary?.slug ?? GENERAL;
    const name = primary ? toTitleCase(primary.name ?? primary.slug) : 'General';

    if (!seen.has(key)) {
      seen.add(key);
      order.push({ slug: key, name });
    }
    map.set(key, [...(map.get(key) ?? []), post]);
  }

  // Sort by post count desc; General last
  const sorted = order
    .filter((c) => c.slug !== GENERAL)
    .sort((a, b) => (map.get(b.slug)?.length ?? 0) - (map.get(a.slug)?.length ?? 0));
  if (seen.has(GENERAL)) sorted.push({ slug: GENERAL, name: 'General' });

  return { subTags: sorted, grouped: map };
}, [posts, tag]);

const visibleSubTags = useMemo(
  () => (activeSubTag ? subTags.filter((s) => s.slug === activeSubTag) : subTags),
  [subTags, activeSubTag],
);

const useClustering = subTags.length > 1;

  // ── Pagination (flat list or single-cluster filter) ──────────────────────
  const [currentPage, setCurrentPage] = useState(1);

  const flatPosts = useMemo(() => {
    if (!useClustering) return posts;
    if (activeSubTag) return grouped.get(activeSubTag) ?? [];
    return posts;
  }, [useClustering, activeSubTag, posts, grouped]);

  const totalPages = Math.ceil(flatPosts.length / PAGE_SIZE);
  const pagedFlatPosts = flatPosts.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  useEffect(() => {
    setCurrentPage(1);
  }, [activeSubTag]);

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

return (
  <AppProvider publication={publication} footerPosts={footerPosts}>
    <Layout>
      <Head>
        <title>{title}</title>
        <meta
          property="og:image"
          content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
        />
        <meta
          property="twitter:image"
          content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
        />
      </Head>
      <Container className="mx-auto w-full">
        <PersonalHeader />
        <div className="max-w-7xl mx-auto w-full px-5 pt-10 pb-20">

          {/* ── Back nav ── */}
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-neutral-400 dark:text-neutral-500 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-10 group"
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform">
              <path fillRule="evenodd" d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z" clipRule="evenodd" />
            </svg>
            Home
          </Link>

          {/* ── Page header ── */}
          <div className="mb-10">
            <p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
              Topic
            </p>
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50 capitalize mb-3">
              {tagLabel}
            </h1>
            <p className="text-lg text-neutral-500 dark:text-neutral-400">
              {posts.length} article{posts.length !== 1 ? 's' : ''}
              {useClustering && (
                <span className="text-neutral-400 dark:text-neutral-500">
                  {' '}across {subTags.length} sub-topics
                </span>
              )}
            </p>
          </div>

          {useClustering ? (
            <>
              {/* ── Sub-topic filter pills ── */}
              <div className="flex flex-wrap gap-2 mb-12">
                <button
                  onClick={() => setActiveSubTag(null)}
                  className={`inline-flex items-center px-3.5 py-1.5 rounded-full text-sm font-medium border transition-all duration-150 ${
                    activeSubTag === null
                      ? 'bg-blue-600 text-white border-blue-600 shadow-sm'
                      : 'bg-white dark:bg-neutral-900 text-neutral-600 dark:text-neutral-400 border-neutral-200 dark:border-neutral-700 hover:border-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950/40 hover:text-blue-700 dark:hover:text-blue-300'
                  }`}
                >
                  All
                  <span className={`ml-1.5 text-xs tabular-nums ${activeSubTag === null ? 'text-blue-200' : 'text-neutral-400 dark:text-neutral-500'}`}>
                    {posts.length}
                  </span>
                </button>
                {subTags.map((st) => (
                  <button
                    key={st.slug}
                    onClick={() => setActiveSubTag(st.slug === activeSubTag ? null : st.slug)}
                    className={`inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-sm font-medium border transition-all duration-150 ${
                      activeSubTag === st.slug
                        ? 'bg-blue-600 text-white border-blue-600 shadow-sm'
                        : 'bg-white dark:bg-neutral-900 text-neutral-600 dark:text-neutral-400 border-neutral-200 dark:border-neutral-700 hover:border-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950/40 hover:text-blue-700 dark:hover:text-blue-300'
                    }`}
                  >
                    {st.name}
                    <span className={`text-xs tabular-nums ${activeSubTag === st.slug ? 'text-blue-200' : 'text-neutral-400 dark:text-neutral-500'}`}>
                      {grouped.get(st.slug)?.length ?? 0}
                    </span>
                  </button>
                ))}
              </div>

              {/* ── Single sub-tag selected: paginated flat list ── */}
              {activeSubTag ? (
                <>
                  <MinimalPosts context="tag" posts={pagedFlatPosts} />
                  <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={handlePageChange} />
                </>
              ) : (
                /* ── All sub-tags: show each cluster capped at CLUSTER_PREVIEW ── */
                <div className="flex flex-col divide-y divide-neutral-100 dark:divide-neutral-800">
                  {visibleSubTags.map((st) => {
                    const stPosts = grouped.get(st.slug) ?? [];
                    if (stPosts.length === 0) return null;
                    const preview = stPosts.slice(0, CLUSTER_PREVIEW);
                    const remaining = stPosts.length - CLUSTER_PREVIEW;
                    return (
                      <div key={st.slug} id={`subtag-${st.slug}`} className="py-10 first:pt-0">
                        <div className="flex items-center gap-3 mb-6">
                          <p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 whitespace-nowrap">
                            Sub-topic
                          </p>
                          <div className="flex-1 h-px bg-neutral-100 dark:bg-neutral-800" />
                        </div>
                        <div className="mb-5 flex items-end justify-between gap-4">
                          <div>
                            {st.slug !== GENERAL ? (
                              <Link
                                href={`/tag/${st.slug}`}
                                className="text-2xl font-bold tracking-tight text-neutral-900 dark:text-neutral-50 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
                              >
                                {st.name}
                              </Link>
                            ) : (
                              <h2 className="text-2xl font-bold tracking-tight text-neutral-900 dark:text-neutral-50">
                                {st.name}
                              </h2>
                            )}
                            <p className="text-sm text-neutral-400 dark:text-neutral-500 mt-1">
                              {stPosts.length} article{stPosts.length !== 1 ? 's' : ''}
                            </p>
                          </div>
                          {remaining > 0 && (
                            <button
                              onClick={() => setActiveSubTag(st.slug)}
                              className="flex-shrink-0 inline-flex items-center gap-1.5 text-sm font-semibold text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 transition-colors"
                            >
                              +{remaining} more
                              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                              </svg>
                            </button>
                          )}
                        </div>
                        <MinimalPosts context="tag" posts={preview} />
                      </div>
                    );
                  })}
                </div>
              )}
            </>
          ) : (
            /* ── Flat list (no sub-topics): paginated ── */
            <>
              {posts.length > 0 && <MinimalPosts context="tag" posts={pagedFlatPosts} />}
              <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={handlePageChange} />
            </>
          )}
        </div>
        <Footer />
      </Container>
    </Layout>
  </AppProvider>
);
}

type Params = {
slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
if (!params) {
  throw new Error('No params');
}

const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
const gqlEndpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

// First page — also provides publication metadata
const data = await request<TagPostsByPublicationQuery, TagPostsByPublicationQueryVariables>(
  gqlEndpoint,
  TagPostsByPublicationDocument,
  {
    host,
    first: 20,
    tagSlug: params.slug,
  },
);

const publication = data.publication;
if (!publication) {
  return { notFound: true };
}

// Collect all tag posts by following pagination cursors
const posts: PostFragment[] = publication.posts.edges.map((edge) => edge.node);
let cursor = publication.posts.pageInfo?.endCursor;
let hasNextPage = !!publication.posts.pageInfo?.hasNextPage;

while (hasNextPage && cursor) {
  const next = await request<TagPostsByPublicationQuery, TagPostsByPublicationQueryVariables>(
    gqlEndpoint,
    TagPostsByPublicationDocument,
    { host, first: 20, tagSlug: params.slug, after: cursor },
  );
  if (!next.publication) break;
  posts.push(...next.publication.posts.edges.map((e) => e.node));
  cursor = next.publication.posts.pageInfo?.endCursor;
  hasNextPage = !!next.publication.posts.pageInfo?.hasNextPage;
}

const footerPosts = await getFooterPosts();

return {
  props: {
    posts,
    publication,
    tag: params.slug,
    footerPosts,
  },
  revalidate: 1,
};
};

export async function getStaticPaths() {
return {
  paths: [],
  fallback: 'blocking',
};
}