import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { AppProvider } from '../../components/contexts/appContext';
import { Container } from '../../components/container';
import { Footer } from '../../components/footer';
import { Layout } from '../../components/layout';
import { PersonalHeader } from '../../components/personal-theme-header';
import { TopicLearningJourneyView } from '../../components/topic-learning-journey';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../../generated/graphql';
import { buildTopicLearningJourney, type TopicLearningJourney } from '../../lib/topic-learning';

type Props = {
	publication: PublicationFragment;
	posts: PostFragment[];
	journey: TopicLearningJourney;
};

export default function TopicLearningPage({ publication, posts, journey }: Props) {
	return (
		<AppProvider publication={publication} footerPosts={posts}>
			<Layout>
				<Head>
					<title>{journey.label} Learning Journey — {publication.title}</title>
					<meta
						name="description"
						content={`${journey.label} as a multi-article learning journey with concept graph navigation, simulations, AI mentoring, and semantic retrieval.`}
					/>
					<meta property="og:title" content={`${journey.label} Learning Journey — ${publication.title}`} />
					<meta property="og:description" content={journey.description} />
					<meta property="og:image" content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)} />
					<meta property="twitter:card" content="summary_large_image" />
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<main className="mx-auto w-full max-w-7xl px-5 pb-20 pt-10">
						<Link
							href="/guided-topics"
							className="mb-10 inline-flex items-center gap-1.5 text-sm text-neutral-400 transition-colors hover:text-blue-600 dark:text-neutral-500 dark:hover:text-blue-400"
						>
							<span aria-hidden="true">←</span>
							Learning Graphs
						</Link>
						<TopicLearningJourneyView journey={journey} posts={posts} />
					</main>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

const fetchAllPosts = async () => {
	const first = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		PostsByPublicationDocument,
		{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST },
	);

	const publication = first.publication;
	if (!publication) return null;

	const posts: PostFragment[] = publication.posts.edges.map((edge) => edge.node);
	let cursor = publication.posts.pageInfo?.endCursor;
	let hasNextPage = !!publication.posts.pageInfo?.hasNextPage;

	while (hasNextPage && cursor) {
		const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
		);
		if (!next.publication) break;
		posts.push(...next.publication.posts.edges.map((edge) => edge.node));
		cursor = next.publication.posts.pageInfo.endCursor;
		hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
	}

	return { publication, posts };
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params?.slug) return { notFound: true };

	try {
		const data = await fetchAllPosts();
		if (!data) return { notFound: true };
		const journey = buildTopicLearningJourney(params.slug, data.posts);

		return {
			props: {
				publication: data.publication,
				posts: data.posts,
				journey,
			},
			revalidate: 3600,
		};
	} catch (err) {
		console.error('[topic] getStaticProps error:', err);
		return { notFound: true };
	}
};

export async function getStaticPaths() {
	return {
		paths: [],
		fallback: 'blocking',
	};
}
