import { resizeImage } from '@starter-kit/utils/image';

const decodeHtml = (html: string): string =>
	html
		.replace(/&amp;/g, '&')
		.replace(/&lt;/g, '<')
		.replace(/&gt;/g, '>')
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&apos;/g, "'");
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
import request from 'graphql-request';
import { motion, useReducedMotion } from 'framer-motion';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { DateFormatter } from '../components/date-formatter';
import { formatTagName } from '../utils/format';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	PageByPublicationDocument,
	PostFragment,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';
import { getFooterPosts } from '../lib/api/footerData';
import { ScrollButtons } from '../components/scroll-buttons';
import { ArticleEngagement } from '../components/article-engagement';
import { ContextualBreadcrumbs } from '../components/contextual-breadcrumbs';
import { useLearningContext } from '../components/learning-context-provider';
import { CTAButton, CTALink } from '../components/cta-system';
import { useLearningMemoryStore } from '../lib/learning-memory';
import { getArticleConceptSeeds, inferArticleDomain, inferPrimaryArticleConcept } from '../lib/article-domain';
import { inferTopicSlugForPost } from '../lib/topic-learning';

// ─── Reading Progress Bar ─────────────────────────────────────────────────────
const ReadingProgressBar = () => {
	const [progress, setProgress] = useState(0);
	const reduceMotion = useReducedMotion();

	useEffect(() => {
		const onScroll = () => {
			const el = document.documentElement;
			const scrolled = el.scrollTop;
			const total = el.scrollHeight - el.clientHeight;
			setProgress(total > 0 ? Math.min(100, (scrolled / total) * 100) : 0);
		};
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	return (
		<div
			aria-hidden="true"
			className="fixed top-0 left-0 z-50 w-full h-0.5 bg-transparent pointer-events-none"
		>
			<motion.div
				className="h-full bg-blue-500 dark:bg-blue-400"
				animate={{ width: `${progress}%` }}
				transition={reduceMotion ? { duration: 0 } : { duration: 0.12, ease: 'linear' }}
			/>
		</div>
	);
};

type TocItem = {
	id: string;
	slug: string;
	title: string;
	level: number;
	parentId?: string | null;
};

type ArticleBackmatter = {
	executiveTldr?: string[];
	keySystemsVisualization?: {
		nodes?: string[];
		title?: string;
	};
	mermaidDiagram?: string;
};

const BACKMATTER_BLOCK_REGEX = /\n?<!--\s*AA_BACKMATTER\s*([\s\S]*?)-->\s*$/;

const normalizeBackmatterList = (value: unknown): string[] => {
	if (!Array.isArray(value)) return [];
	return value
		.map((item) => (typeof item === 'string' ? item.trim() : ''))
		.filter((item) => item.length > 0)
		.slice(0, 8);
};

const parseArticleBackmatter = (
	markdown: string,
): { cleanMarkdown: string; backmatter: ArticleBackmatter | null } => {
	const match = markdown.match(BACKMATTER_BLOCK_REGEX);
	if (!match) return { cleanMarkdown: markdown, backmatter: null };

	const raw = match[1]?.trim();
	if (!raw) {
		return {
			cleanMarkdown: markdown.replace(BACKMATTER_BLOCK_REGEX, '').trimEnd(),
			backmatter: null,
		};
	}

	try {
		const parsed = JSON.parse(raw) as {
			executiveTldr?: unknown;
			keySystemsVisualization?: { nodes?: unknown; title?: unknown };
			mermaidDiagram?: unknown;
		};
		const executiveTldr = normalizeBackmatterList(parsed.executiveTldr);
		const visualizationNodes = normalizeBackmatterList(parsed.keySystemsVisualization?.nodes);
		const visualizationTitle =
			typeof parsed.keySystemsVisualization?.title === 'string'
				? parsed.keySystemsVisualization.title.trim()
				: '';
		const mermaidDiagram = typeof parsed.mermaidDiagram === 'string' ? parsed.mermaidDiagram.trim() : '';

		const backmatter: ArticleBackmatter = {};
		if (executiveTldr.length > 0) backmatter.executiveTldr = executiveTldr;
		if (visualizationNodes.length > 0 || visualizationTitle) {
			backmatter.keySystemsVisualization = {};
			if (visualizationNodes.length > 0) backmatter.keySystemsVisualization.nodes = visualizationNodes;
			if (visualizationTitle) backmatter.keySystemsVisualization.title = visualizationTitle;
		}
		if (mermaidDiagram) backmatter.mermaidDiagram = mermaidDiagram;

		return {
			cleanMarkdown: markdown.replace(BACKMATTER_BLOCK_REGEX, '').trimEnd(),
			backmatter:
				Object.keys(backmatter).length > 0
					? backmatter
					: null,
		};
	} catch (error) {
		console.warn('[backmatter] Invalid AA_BACKMATTER JSON block:', error);
		return {
			cleanMarkdown: markdown.replace(BACKMATTER_BLOCK_REGEX, '').trimEnd(),
			backmatter: null,
		};
	}
};

const stripMarkdown = (markdown: string) =>
	markdown
		.replace(/```[\s\S]*?```/g, ' ')
		.replace(/`[^`]*`/g, ' ')
		.replace(/!\[[^\]]*\]\([^)]+\)/g, ' ')
		.replace(/\[[^\]]+\]\([^)]+\)/g, ' ')
		.replace(/[#>*_\-\n]/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();

const normalizeCoverImageUrl = (raw?: string | null) => {
	if (!raw) return null;
	const withProtocol = raw.startsWith('//') ? `https:${raw}` : raw;
	return resizeImage(withProtocol, { w: 960, h: 540, c: 'thumb' });
};

const getAiSummaryBullets = (markdown: string, fallback: string) => {
	const plain = stripMarkdown(markdown);
	const sentences = plain
		.split(/(?<=[.!?])\s+/)
		.map((line) => line.trim())
		.filter((line) => line.length > 35)
		.slice(0, 4);
	return sentences.length > 0 ? sentences : [`This article explains ${fallback.toLowerCase()} in depth.`];
};

const normalizeTradeoffText = (value: string) =>
	value
		.replace(/```[\s\S]*?```/g, ' ')
		.replace(/`+/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();

const stripTldrPrefix = (value: string) =>
	value
		.replace(/^\s*tl;?dr\s*:\s*/i, '')
		.replace(/^\s*tldr\s*:\s*/i, '')
		.trim();

const sanitizeTradeoffOptions = (options: Array<{ title: string; body: string }>) => {
	const cleaned = options
		.map((option) => {
			const title = stripTldrPrefix(normalizeTradeoffText(option.title || ''));
			const body = stripTldrPrefix(normalizeTradeoffText(option.body || ''));
			return { title, body };
		})
		.filter((option) => {
			const combined = `${option.title} ${option.body}`.toLowerCase();
			if (!option.title || !option.body) return false;
			if (combined.includes('tldr:') || combined.includes('tl;dr')) return false;
			if (combined.includes('tool use') || combined.includes('function_call') || combined.includes('observation:')) return false;
			if (combined.includes('->>')) return false;
			if (/^why\s+["'`]/i.test(option.title)) return false;
			if (/^📖/.test(option.title)) return false;
			return true;
		});

	const deduped = cleaned.filter(
		(option, index, arr) =>
			arr.findIndex((item) => item.title.toLowerCase() === option.title.toLowerCase()) === index,
	);

	return deduped.slice(0, 2);
};

const isNoisyCompanionText = (value: string) => {
	const text = normalizeTradeoffText(value).toLowerCase();
	if (!text) return true;
	if (/^tl;?dr\s*:/.test(text)) return true;
	if (text.includes('function_call') || text.includes('observation:')) return true;
	if (text.includes('tool use execution sequence') || text.includes('llm->>') || text.includes('->>')) return true;
	if (text.includes('a tool is a single callable capability')) return true;
	return false;
};

const GLOSSARY_TERMS: Record<string, string> = {
	cap: 'Consistency, Availability, and Partition tolerance tradeoff model.',
	quorum: 'Minimum number of distributed votes required for validity.',
	replication: 'Copying data across nodes to improve resilience and availability.',
	latency: 'Time delay between request and response completion.',
	rag: 'Retrieval-Augmented Generation: grounding LLM output in retrieved context.',
	embedding: 'Vector representation used for semantic similarity and retrieval.',
	transformer: 'Neural network architecture used by modern LLMs.',
	sharding: 'Splitting data across partitions to scale throughput and storage.',
	backpressure: 'Flow-control mechanism to prevent downstream overload.',
	idempotency: 'Safe repeated operation producing the same result.',
};

const detectGlossaryTerms = (markdown: string) => {
	const haystack = markdown.toLowerCase();
	return Object.entries(GLOSSARY_TERMS)
		.filter(([term]) => haystack.includes(term))
		.slice(0, 8);
};

const deriveFallbackConcepts = (title: string, tags: NonNullable<PostFullFragment['tags']>) => {
	const fromTags = tags.map((tag) => formatTagName(tag.name)).filter(Boolean);
	const fromTitle = title
		.replace(/[^\w\s-]/g, ' ')
		.split(/\s+/)
		.map((word) => word.trim())
		.filter((word) => word.length > 3 && !/with|from|into|that|this|what|when|your|their/i.test(word))
		.slice(0, 5);
	return [...new Set([...fromTags, ...fromTitle])].slice(0, 5);
};

const deriveArticleFlowNodes = (
	tocItems: TocItem[],
	tags: NonNullable<PostFullFragment['tags']>,
	title: string,
) => {
	const fromToc = tocItems
		.filter((item) => item.level <= 2)
		.map((item) => decodeHtml(item.title).replace(/^[\d.]+\s*/, '').trim())
		.filter(Boolean)
		.slice(0, 5);
	if (fromToc.length >= 3) return fromToc;

	const fallback = deriveFallbackConcepts(title, tags);
	return (fallback.length >= 3 ? fallback : [...fallback, 'Core idea', 'Tradeoffs', 'Application']).slice(0, 5);
};

const normalizeHeadingKey = (value: string) =>
	decodeHtml(value)
		.toLowerCase()
		.replace(/[^a-z0-9\s]/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();

const deriveDeepDiveSummaries = (markdown: string, tocItems: TocItem[]) => {
	const lines = markdown.split(/\r?\n/);
	type SectionBlock = { title: string; body: string[] };
	const blocks: SectionBlock[] = [];
	let current: SectionBlock | null = null;

	for (const rawLine of lines) {
		const headingMatch = rawLine.match(/^#{1,6}\s+(.+)$/);
		if (headingMatch) {
			if (current) blocks.push(current);
			current = { title: headingMatch[1].trim(), body: [] };
			continue;
		}
		if (!current) continue;
		current.body.push(rawLine);
	}
	if (current) blocks.push(current);

	const allSentences = stripMarkdown(markdown)
		.split(/(?<=[.!?])\s+/)
		.map((line) => line.trim())
		.filter((line) => line.length > 35)
		.filter((line) => !isNoisyCompanionText(line));

	const titleKeywords = (title: string) =>
		normalizeHeadingKey(title)
			.split(' ')
			.filter((token) => token.length > 3)
			.filter((token) => !['deep', 'dive', 'with', 'from', 'into', 'that', 'this', 'what', 'when'].includes(token));

	const getHeadingMatchScore = (targetKey: string, keywords: string[], blockTitle: string) => {
		const headingKey = normalizeHeadingKey(blockTitle);
		if (!headingKey) return 0;
		if (headingKey === targetKey) return 100;
		if (headingKey.includes(targetKey) || targetKey.includes(headingKey)) return 75;
		return keywords.reduce((score, keyword) => (headingKey.includes(keyword) ? score + 1 : score), 0);
	};

	const getExcerptMarkdown = (bodyLines: string[]) => {
		const cleaned: string[] = [];
		let inCodeFence = false;

		for (const rawLine of bodyLines) {
			const line = rawLine.trimEnd();
			const trimmed = line.trim();

			if (/^```/.test(trimmed)) {
				inCodeFence = !inCodeFence;
				continue;
			}
			if (inCodeFence) continue;
			if (!trimmed) {
				cleaned.push(line);
				continue;
			}
			// Avoid raw markdown table rows in summary excerpts; they render poorly in compact cards.
			if (/^\|.*\|$/.test(trimmed)) continue;
			if (/^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(trimmed)) continue;
			// Avoid raw Mermaid/diagram syntax leaking into compact deep-dive summaries.
			if (/^(sequenceDiagram|flowchart|graph\s+(TD|TB|LR|RL|BT)|classDiagram|stateDiagram|erDiagram|journey|gantt|pie\s+title)\b/i.test(trimmed)) continue;
			if (/^[A-Za-z0-9_.-]+\s*-{1,2}>{1,2}\s*[A-Za-z0-9_.-]+\s*:/.test(trimmed)) continue;
			if (/^(participant|actor|autonumber|title)\b/i.test(trimmed)) continue;
			if (isNoisyCompanionText(trimmed)) continue;

			cleaned.push(line);
		}
		const chunks: string[] = [];
		let chunk: string[] = [];

		for (const line of cleaned) {
			if (!line.trim()) {
				if (chunk.length > 0) {
					chunks.push(chunk.join('\n').trim());
					chunk = [];
				}
				continue;
			}
			chunk.push(line);
		}
		if (chunk.length > 0) chunks.push(chunk.join('\n').trim());

		const narrativeChunks = chunks.filter((value) => {
			if (!value) return false;
			if (/^#{1,6}\s+/.test(value)) return false;
			if (/^```/.test(value)) return false;
			if (/^([-*+]\s+|\d+[.)]\s+)/.test(value)) return false;
			if (value.includes('|')) return false;
			return stripMarkdown(value).replace(/\s+/g, ' ').trim().length > 80;
		});

		return (narrativeChunks[0] ?? chunks.find(Boolean) ?? '').slice(0, 1200);
	};

	return tocItems.reduce<Record<string, { summaryMarkdown: string; bulletMarkdown: string }>>((acc, item) => {
		const key = normalizeHeadingKey(item.title);
		const keywords = titleKeywords(item.title);
		const match =
			blocks
				.map((block) => ({
					block,
					score: getHeadingMatchScore(key, keywords, block.title),
				}))
				.sort((left, right) => right.score - left.score)[0] ?? null;

		const rawBody = match && match.score > 0 ? match.block.body : [];
		const excerptMarkdown = getExcerptMarkdown(rawBody);
		const plain = stripMarkdown(rawBody.join('\n')).trim();
		const sentences = plain
			.split(/(?<=[.!?])\s+/)
			.map((line) => line.trim())
			.filter((line) => line.length > 35)
			.filter((line) => !isNoisyCompanionText(line));
		const semanticFallback = allSentences.find((sentence) =>
			keywords.filter((keyword) => sentence.toLowerCase().includes(keyword)).length >= Math.min(2, Math.max(1, keywords.length)) &&
			!sentence.includes('|'),
		);
		const safeExcerpt = stripTldrPrefix(excerptMarkdown || '');
		const safeSemanticFallback = stripTldrPrefix(semanticFallback || '');
		const summaryMarkdown =
			(safeExcerpt && !isNoisyCompanionText(safeExcerpt) ? safeExcerpt : '') ||
			(safeSemanticFallback && !isNoisyCompanionText(safeSemanticFallback) ? safeSemanticFallback : '') ||
			`This section explains ${decodeHtml(item.title)} and connects it to the broader concept progression in this article.`;

		const bulletLines = rawBody
			.map((line) => line.trim())
			.filter((line) => /^([-*+]\s+|\d+[.)]\s+)/.test(line))
			.slice(0, 3);
		const fallbackBullets = [
			...sentences.slice(1, 4),
			...allSentences
				.filter((sentence) => keywords.some((keyword) => sentence.toLowerCase().includes(keyword)))
				.slice(0, 2),
		]
			.map((point) => stripTldrPrefix(point))
			.filter((point) => !isNoisyCompanionText(point))
			.filter((point) => point.length < 180)
			.filter((point) => !summaryMarkdown.includes(point))
			.slice(0, 3)
			.map((point) => `- ${point}`);
		const bulletMarkdown =
			bulletLines.length > 0
				? bulletLines.join('\n')
				: summaryMarkdown.includes('|')
				? ''
				: fallbackBullets.join('\n');

		acc[item.slug] = { summaryMarkdown, bulletMarkdown };
		return acc;
	}, {});
};

const getNumberedTocLabel = (item: TocItem, index: number) => {
	return `${index + 1}. ${decodeHtml(item.title)}`;
};

const ReadingNavigationSidebar = ({
	tocItems,
	readTimeInMinutes,
	progress,
	onBeginnerHelp,
	onOpenQuiz,
	onMarkComplete,
}: {
	tocItems: TocItem[];
	readTimeInMinutes: number;
	progress: number;
	onBeginnerHelp: () => void;
	onOpenQuiz: () => void;
	onMarkComplete: () => void;
}) => {
	const [tocSearch, setTocSearch] = useState('');
	const [tocCollapsed, setTocCollapsed] = useState(false);
	const [activeSection, setActiveSection] = useState<string>('');
	const filteredToc = tocItems.filter((item) =>
		decodeHtml(item.title).toLowerCase().includes(tocSearch.toLowerCase()),
	);
	const estimatedRemaining = Math.max(
		1,
		Math.round((readTimeInMinutes * Math.max(0, 100 - progress)) / 100),
	);

	useEffect(() => {
		if (tocItems.length === 0) return;
		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries
					.filter((entry) => entry.isIntersecting)
					.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
				if (visible[0]) setActiveSection(visible[0].target.id);
			},
			{ rootMargin: '0px 0px -68% 0px', threshold: 0 },
		);
		tocItems.forEach((item) => {
			const el = document.getElementById(`heading-${item.slug}`);
			if (el) observer.observe(el);
		});
		return () => observer.disconnect();
	}, [tocItems]);

	return (
		<aside className="hidden xl:block min-w-0">
			<div className="sticky top-24 space-y-4">
				<div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-[0_12px_40px_rgba(15,23,42,0.04)] dark:border-neutral-800 dark:bg-neutral-900">
					<p className="mb-3 flex items-center gap-2 text-xs font-bold text-neutral-900 dark:text-neutral-100">
						<span className="inline-flex h-6 w-6 items-center justify-center rounded-lg bg-violet-50 text-violet-600 dark:bg-violet-950/40 dark:text-violet-300">✣</span>
						On this page
					</p>
					<div className="relative max-h-72 space-y-1 overflow-auto pr-1">
						<div className="absolute bottom-2 left-[11px] top-2 w-px bg-violet-100 dark:bg-violet-950" aria-hidden="true" />
						{tocItems.map((item) => {
							const headingId = `heading-${item.slug}`;
							const isActive = activeSection === headingId;
							return (
								<a
									key={item.id}
									href={`#${headingId}`}
									className={`group flex items-center gap-2 rounded-md px-2 py-1.5 text-xs transition-colors ${
										isActive
											? 'bg-violet-50 text-violet-700 dark:bg-violet-950/40 dark:text-violet-300'
											: 'text-neutral-600 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800/60'
									}`}
								>
									<span className={`relative z-10 h-2.5 w-2.5 rounded-full ${isActive ? 'bg-violet-600 shadow-[0_0_0_4px_rgba(124,58,237,0.12)]' : 'bg-violet-200 dark:bg-violet-900'}`} />
									<span className="line-clamp-1">{getNumberedTocLabel(item, tocItems.indexOf(item))}</span>
								</a>
							);
						})}
					</div>
					<button
						onClick={onOpenQuiz}
						className="mt-4 flex w-full items-center gap-2 rounded-xl border border-violet-100 px-3 py-2 text-left text-xs font-bold text-neutral-800 transition-colors hover:border-violet-300 hover:text-violet-700 dark:border-violet-900 dark:text-neutral-100 dark:hover:text-violet-300"
					>
						<span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-violet-50 text-violet-600 dark:bg-violet-950/40 dark:text-violet-300">□</span>
						Quiz Yourself
					</button>
				</div>

				<div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-[0_12px_40px_rgba(15,23,42,0.04)] dark:border-neutral-800 dark:bg-neutral-900">
					<p className="mb-3 text-xs font-bold text-neutral-900 dark:text-neutral-100">
						Reading progress
					</p>
					<div className="flex items-center gap-3">
						<div className="h-2 flex-1 overflow-hidden rounded-full bg-violet-100 dark:bg-neutral-800">
							<div className="h-full rounded-full bg-gradient-to-r from-violet-600 to-blue-500" style={{ width: `${progress}%` }} />
						</div>
						<p className="text-xs font-bold text-neutral-700 dark:text-neutral-200">{Math.round(progress)}%</p>
					</div>
					<p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
						{estimatedRemaining} min left
					</p>
					<button
						onClick={onMarkComplete}
						className="mt-3 w-full rounded-xl border border-violet-200 px-3 py-2 text-xs font-bold text-violet-700 transition-colors hover:border-violet-400 hover:bg-violet-50 dark:border-violet-800 dark:text-violet-300 dark:hover:bg-violet-950/30"
					>
						Mark as complete
					</button>
				</div>

				<div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-[0_12px_40px_rgba(15,23,42,0.04)] dark:border-neutral-800 dark:bg-neutral-900">
					<div className="flex items-center justify-between">
						<p className="text-xs font-bold text-neutral-900 dark:text-neutral-100">
							Table of contents
						</p>
						<button onClick={() => setTocCollapsed((prev) => !prev)} className="text-[11px] font-semibold text-violet-600 dark:text-violet-300">
							{tocCollapsed ? 'Show all' : 'Collapse'}
						</button>
					</div>
					{!tocCollapsed ? (
						<div className="mt-3 max-h-44 overflow-auto space-y-1">
							<input
								value={tocSearch}
								onChange={(e) => setTocSearch(e.target.value)}
								placeholder="Search section"
								className="mb-2 w-full rounded-lg border border-neutral-200 bg-neutral-50 px-2.5 py-1.5 text-xs outline-none focus:border-violet-300 dark:border-neutral-700 dark:bg-neutral-950"
							/>
							{filteredToc.map((item) => (
								<a key={`toc-mini-${item.id}`} href={`#heading-${item.slug}`} className="block rounded-md px-2 py-1 text-xs text-neutral-600 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800/60">
									{decodeHtml(item.title)}
								</a>
							))}
						</div>
					) : null}
				</div>

				<div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-[0_12px_40px_rgba(15,23,42,0.04)] dark:border-neutral-800 dark:bg-neutral-900">
					<p className="text-xs font-semibold text-neutral-900 dark:text-neutral-100">Need another angle?</p>
					<p className="mt-2 text-[11px] leading-relaxed text-neutral-500 dark:text-neutral-400">
						Switch the companion view to a lower-complexity pass for the current article.
					</p>
					<button
						onClick={onBeginnerHelp}
						className="mt-3 w-full rounded-xl border border-violet-200 bg-white px-3 py-2 text-xs font-bold text-violet-700 transition-colors hover:border-violet-400 hover:bg-violet-50 dark:border-violet-800 dark:bg-neutral-950 dark:text-violet-300"
					>
						Explain like I’m 5
					</button>
				</div>
			</div>
		</aside>
	);
};

const ReadingContextSidebar = () => null;

const MobileChunkNavigator = ({
	tocItems,
	onAiExplain,
	onBookmark,
	isBookmarked,
	interviewHref,
	whiteboardHref,
	mockHref,
}: {
	tocItems: TocItem[];
	onAiExplain: (sectionTitle: string) => void;
	onBookmark: () => void;
	isBookmarked: boolean;
	interviewHref: string;
	whiteboardHref: string;
	mockHref: string;
}) => {
	const [activeIdx, setActiveIdx] = useState(0);
	const [trayOpen, setTrayOpen] = useState(false);
	const cognitionSteps = ['Concept', 'Visual', 'Tradeoff', 'Challenge', 'Continue'];

	useEffect(() => {
		if (tocItems.length === 0) return;
		const headings = tocItems
			.map((item, index) => ({ index, el: document.getElementById(`heading-${item.slug}`) }))
			.filter((entry): entry is { index: number; el: HTMLElement } => Boolean(entry.el));

		if (headings.length === 0) return;

		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries
					.filter((entry) => entry.isIntersecting)
					.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
				if (visible[0]) {
					const match = headings.find((h) => h.el.id === visible[0].target.id);
					if (match) setActiveIdx(match.index);
				}
			},
			{ rootMargin: '0px 0px -70% 0px', threshold: 0 },
		);

		headings.forEach((heading) => observer.observe(heading.el));
		return () => observer.disconnect();
	}, [tocItems]);

	if (tocItems.length === 0) return null;

	const goTo = (index: number) => {
		const target = tocItems[index];
		if (!target) return;
		document.getElementById(`heading-${target.slug}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
	};

	return (
		<div className="xl:hidden fixed bottom-0 left-0 right-0 z-40 border-t border-neutral-200 bg-white/95 px-3 py-3 shadow-[0_-16px_40px_rgba(15,23,42,0.08)] backdrop-blur dark:border-neutral-800 dark:bg-neutral-950/95">
			<span className="sr-only">Concept Visual Tradeoff Challenge Continue</span>
			{trayOpen ? (
				<div className="fixed inset-0 z-[-1] bg-black/20" onClick={() => setTrayOpen(false)} aria-hidden="true" />
			) : null}
			{trayOpen ? (
				<div className="mx-auto mb-3 max-w-xl rounded-3xl border border-neutral-200 bg-white p-3 shadow-2xl dark:border-neutral-800 dark:bg-neutral-950">
					<div className="mx-auto mb-3 h-1 w-10 rounded-full bg-neutral-200 dark:bg-neutral-700" />
					<p className="px-1 text-[11px] font-semibold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">Section actions</p>
					<div className="mt-2 grid grid-cols-2 gap-2">
						<a
							href={interviewHref}
							onClick={() => setTrayOpen(false)}
							className="rounded-xl border border-violet-200 bg-violet-50 px-3 py-3 text-center text-xs font-bold text-violet-700 dark:border-violet-800 dark:bg-violet-950/30 dark:text-violet-300"
						>
							Interview Drill
						</a>
						<a
							href={whiteboardHref}
							onClick={() => setTrayOpen(false)}
							className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-3 text-center text-xs font-bold text-blue-700 dark:border-blue-800 dark:bg-blue-950/30 dark:text-blue-300"
						>
							Whiteboard
						</a>
						<button
							onClick={() => {
								goTo(Math.max(0, activeIdx - 1));
								setTrayOpen(false);
							}}
							disabled={activeIdx === 0}
							className="rounded-xl border border-neutral-200 px-3 py-3 text-xs font-bold text-neutral-700 disabled:opacity-40 dark:border-neutral-700 dark:text-neutral-300"
						>
							Previous
						</button>
						<button
							onClick={() => {
								onAiExplain(tocItems[activeIdx]?.title ?? 'current section');
								setTrayOpen(false);
							}}
							className="rounded-xl border border-violet-200 bg-violet-50 px-3 py-3 text-xs font-bold text-violet-700 dark:border-violet-800 dark:bg-violet-950/30 dark:text-violet-300"
						>
							Ask AI
						</button>
						<button
							onClick={() => {
								onBookmark();
								setTrayOpen(false);
							}}
							className="rounded-xl border border-neutral-200 px-3 py-3 text-xs font-bold text-neutral-700 dark:border-neutral-700 dark:text-neutral-300"
						>
							{isBookmarked ? 'Saved' : 'Save'}
						</button>
						<a
							href={mockHref}
							onClick={() => setTrayOpen(false)}
							className="rounded-xl border border-neutral-200 px-3 py-3 text-center text-xs font-bold text-neutral-700 dark:border-neutral-700 dark:text-neutral-300"
						>
							Mock
						</a>
						<a
							href={`#heading-${tocItems[activeIdx]?.slug}`}
							onClick={() => setTrayOpen(false)}
							className="rounded-xl border border-neutral-200 px-3 py-3 text-center text-xs font-bold text-neutral-700 dark:border-neutral-700 dark:text-neutral-300"
						>
							Current
						</a>
					</div>
					<div className="mt-2 max-h-44 overflow-y-auto rounded-2xl bg-neutral-50 p-1 dark:bg-neutral-900">
						{tocItems.slice(0, 10).map((item, index) => (
							<button
								key={`tray-${item.id}`}
								onClick={() => {
									goTo(index);
									setTrayOpen(false);
								}}
								className={`block w-full rounded-xl px-3 py-2 text-left text-xs font-semibold ${
									index === activeIdx
										? 'bg-white text-violet-700 shadow-sm dark:bg-neutral-800 dark:text-violet-300'
										: 'text-neutral-600 dark:text-neutral-300'
								}`}
							>
								{decodeHtml(item.title)}
							</button>
						))}
					</div>
				</div>
			) : null}
			<div className="mx-auto grid max-w-xl grid-cols-[44px_minmax(0,1fr)] gap-2">
				<button
					onClick={() => setTrayOpen((prev) => !prev)}
					className="rounded-2xl border border-neutral-200 px-3 py-3 text-lg font-black text-neutral-700 dark:border-neutral-700 dark:text-neutral-300"
					aria-expanded={trayOpen}
					aria-label="Open section action tray"
				>
					⋯
				</button>
				<button
					onClick={() => goTo(Math.min(tocItems.length - 1, activeIdx + 1))}
					disabled={activeIdx >= tocItems.length - 1}
					className="min-w-0 rounded-2xl bg-gradient-to-r from-violet-600 to-blue-600 px-3 py-3 text-left text-xs font-bold text-white shadow-lg shadow-violet-500/20 disabled:opacity-40"
				>
					<span className="mb-1 flex gap-1">
						{cognitionSteps.map((step, index) => (
							<span
								key={step}
								className={`h-1.5 flex-1 rounded-full ${index <= Math.min(4, activeIdx % 5) ? 'bg-white' : 'bg-white/30'}`}
							/>
						))}
					</span>
					<span className="block text-[10px] uppercase tracking-[0.16em] text-blue-100">
						{cognitionSteps[Math.min(4, activeIdx % 5)]}
					</span>
					<span className="block truncate">
						Next: {decodeHtml(tocItems[Math.min(tocItems.length - 1, activeIdx + 1)]?.title ?? 'Topic')}
					</span>
				</button>
			</div>
		</div>
	);
};

const StickyMiniArticleHeader = ({
	title,
	readTimeInMinutes,
	progress,
}: {
	title: string;
	readTimeInMinutes: number;
	progress: number;
}) => {
	const [isVisible, setIsVisible] = useState(false);
	useEffect(() => {
		const onScroll = () => setIsVisible(window.scrollY > 220);
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	if (!isVisible) return null;
	return (
		<div className="fixed top-14 inset-x-0 z-40 border-b border-neutral-200/80 bg-white/90 backdrop-blur dark:border-neutral-800 dark:bg-neutral-950/90 xl:hidden">
			<div className="mx-auto max-w-7xl px-4 sm:px-5 py-2 flex items-center gap-3">
				<p className="flex-1 min-w-0 line-clamp-1 text-xs font-semibold text-neutral-700 dark:text-neutral-200">{title}</p>
				<p className="text-[11px] text-neutral-500 dark:text-neutral-400">{readTimeInMinutes} min</p>
				<div className="h-1.5 w-20 rounded-full bg-neutral-100 dark:bg-neutral-800 overflow-hidden">
					<div className="h-1.5 rounded-full bg-blue-500" style={{ width: `${progress}%` }} />
				</div>
			</div>
		</div>
	);
};

const MobileArticleLearningPanel = ({
	tocItems,
	readTimeInMinutes,
	progress,
	onBeginnerHelp,
	onOpenQuiz,
}: {
	tocItems: TocItem[];
	readTimeInMinutes: number;
	progress: number;
	onBeginnerHelp: () => void;
	onOpenQuiz: () => void;
}) => {
	const estimatedRemaining = Math.max(
		1,
		Math.round((readTimeInMinutes * Math.max(0, 100 - progress)) / 100),
	);

	return (
		<div className="mb-5 space-y-2.5 xl:hidden">
			<div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
				<div className="flex items-center justify-between gap-4">
					<p className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">Reading progress</p>
					<p className="text-xs text-neutral-500 dark:text-neutral-400">{estimatedRemaining} min left</p>
				</div>
				<div className="mt-3 flex items-center gap-3">
					<div className="h-2 flex-1 overflow-hidden rounded-full bg-violet-100 dark:bg-neutral-800">
						<div className="h-full rounded-full bg-gradient-to-r from-violet-600 to-blue-500" style={{ width: `${Math.round(progress)}%` }} />
					</div>
					<span className="text-xs font-semibold text-neutral-600 dark:text-neutral-300">{Math.round(progress)}%</span>
				</div>
				<details className="group mt-3">
					<summary className="flex cursor-pointer list-none items-center justify-between rounded-xl bg-neutral-50 px-3 py-2 text-xs font-semibold text-neutral-600 dark:bg-neutral-800/60 dark:text-neutral-300">
						<span>Metadata and pacing</span>
						<span className="transition group-open:rotate-180">⌄</span>
					</summary>
					<div className="mt-2 grid grid-cols-2 gap-2 text-xs">
						<div className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800">
							<p className="text-neutral-500 dark:text-neutral-400">Total read</p>
							<p className="mt-1 font-bold text-neutral-900 dark:text-neutral-50">{readTimeInMinutes} min</p>
						</div>
						<div className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800">
							<p className="text-neutral-500 dark:text-neutral-400">Sections</p>
							<p className="mt-1 font-bold text-neutral-900 dark:text-neutral-50">{tocItems.length || 1}</p>
						</div>
					</div>
				</details>
			</div>

			<details className="group rounded-2xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900">
				<summary className="flex cursor-pointer list-none items-center justify-between px-4 py-3 text-sm font-semibold text-neutral-900 dark:text-neutral-100">
					<span className="inline-flex items-center gap-2"><span className="text-violet-600 dark:text-violet-300">◴</span> On this page</span>
					<span className="text-neutral-400 transition group-open:rotate-180">⌄</span>
				</summary>
				<div className="border-t border-neutral-100 px-4 py-3 dark:border-neutral-800">
					<div className="space-y-1">
						{tocItems.map((item) => (
							<a
								key={`mobile-toc-${item.id}`}
								href={`#heading-${item.slug}`}
								className="block rounded-lg px-2 py-2 text-sm text-neutral-600 hover:bg-neutral-50 dark:text-neutral-300 dark:hover:bg-neutral-800/60"
							>
								{decodeHtml(item.title)}
							</a>
						))}
					</div>
				</div>
			</details>

			<details className="group rounded-2xl border border-violet-200 bg-violet-50/50 dark:border-violet-900 dark:bg-violet-950/20">
				<summary className="flex cursor-pointer list-none items-center justify-between px-4 py-3 text-sm font-semibold text-neutral-900 dark:text-neutral-100">
					<span className="inline-flex items-center gap-2"><span className="text-violet-600 dark:text-violet-300">✣</span> Need another angle?</span>
					<span className="text-neutral-400 transition group-open:rotate-180">⌄</span>
				</summary>
				<div className="border-t border-violet-100 px-4 py-3 dark:border-violet-900/60">
					<p className="text-sm text-neutral-600 dark:text-neutral-300">
						Switch the article companion into a lower-complexity framing, then quiz yourself when you are ready.
					</p>
					<div className="mt-3 grid grid-cols-2 gap-2">
						<button
							onClick={onBeginnerHelp}
							className="rounded-lg border border-violet-300 bg-white px-3 py-2 text-xs font-semibold text-violet-700 dark:border-violet-800 dark:bg-neutral-950 dark:text-violet-300"
						>
							Explain simply
						</button>
						<button
							onClick={onOpenQuiz}
							className="rounded-lg bg-gradient-to-r from-violet-600 to-blue-600 px-3 py-2 text-xs font-semibold text-white"
						>
							Quiz me
						</button>
					</div>
				</div>
			</details>
		</div>
	);
};

const ArticleOverviewBlock = ({
	post,
	tags,
	tocItems,
	summaryBullets,
	flowNodes,
}: {
	post: PostFullFragment;
	tags: NonNullable<PostFullFragment['tags']>;
	tocItems: TocItem[];
	summaryBullets: string[];
	flowNodes: string[];
}) => {
	const overview =
		post.subtitle ||
		post.brief ||
		summaryBullets[0] ||
		`Understand ${post.title} through a practical engineering lens.`;
	const whyItMatters =
		summaryBullets.find((item) => item !== overview) ||
		(tocItems[0]?.title ? `This article builds from ${decodeHtml(tocItems[0].title)} toward practical application.` : `This article connects ${post.title} to implementation decisions and tradeoffs.`);

	return (
		<section className="mb-7 space-y-4">
			<div>
				<h2 id="learning-overview" className="text-xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50 md:text-2xl">
					1. Overview
				</h2>
				<p className="mt-2 text-base leading-relaxed text-neutral-700 dark:text-neutral-300">{overview}</p>
			</div>

			<div className="rounded-xl border border-amber-200 bg-amber-50/70 p-3.5 dark:border-amber-800 dark:bg-amber-950/25">
				<div className="flex gap-3">
					<div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-900/50 dark:text-amber-300">⌁</div>
					<div>
						<p className="text-sm font-bold text-neutral-900 dark:text-neutral-100">Why it matters</p>
						<p className="mt-1 text-sm leading-relaxed text-neutral-700 dark:text-neutral-300">
							{whyItMatters}
						</p>
					</div>
				</div>
			</div>
		</section>
	);
};

const ArticleCognitionLayers = ({
	title,
	summaryBullets,
	flowNodes,
	tradeoffOptions,
	failureScenarios,
	interviewPrompts,
	getSimulationHref,
	onSimulationIntent,
	onAsk,
}: {
	title: string;
	summaryBullets: string[];
	flowNodes: string[];
	tradeoffOptions: Array<{ title: string; body: string }>;
	failureScenarios: Array<{ title: string; impact: string; mitigation: string; severity: number }>;
	interviewPrompts: InterviewPromptSet;
	getSimulationHref: (sectionTitle: string, sectionId?: string) => string;
	onSimulationIntent: (sectionTitle: string, sectionId?: string) => void;
	onAsk: (prompt: string) => void;
}) => {
	const layers = [
		{
			id: 'mental-model',
			label: 'Mental model',
			body: summaryBullets[0] || `Understand ${title} as a system of state, guarantees, and failure boundaries.`,
			action: 'Explain model',
			onAction: () => onAsk(`Explain the mental model behind ${title} with one concrete systems analogy.`),
		},
		{
			id: 'tradeoffs',
			label: 'Production tradeoffs',
			body: tradeoffOptions[0]?.body || `Compare the speed, correctness, cost, and operability choices behind ${title}.`,
			action: 'Reason tradeoffs',
			onAction: () => onAsk(interviewPrompts.tradeoffPrompt),
		},
		{
			id: 'failure',
			label: 'Failure pressure-testing',
			body: failureScenarios[0]?.impact || `Stress the assumptions until the design reveals where it bends or breaks.`,
			action: 'Replay failure',
			onAction: () => onSimulationIntent('Failure pressure test', 'cognition-failure'),
		},
		{
			id: 'interview',
			label: 'Interview reasoning',
			body: interviewPrompts.practiceQuestion,
			action: 'Practice answer',
			onAction: () => onAsk(interviewPrompts.practiceQuestion),
		},
	];

	return (
		<section className="my-8 rounded-3xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900 md:p-5">
			<div className="grid gap-5 lg:grid-cols-[minmax(0,0.72fr)_minmax(0,1fr)] lg:items-start">
				<div>
					<p className="text-[10px] font-mono uppercase tracking-[0.24em] text-blue-600 dark:text-blue-300">
						Engineering cognition interface
					</p>
					<h2 id="cognition-interface" className="mt-2 text-2xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
						Read this as decisions, not prose.
					</h2>
					<p className="mt-3 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
						Use the layers below as the primary article navigation. The full MDX article remains available as deep reference after the cognition path.
					</p>
					<div className="mt-4 flex snap-x gap-2 overflow-x-auto pb-2">
						{flowNodes.slice(0, 5).map((node, index) => (
							<a
								key={`${node}-${index}`}
								href={getSimulationHref(node, `cognition-node-${index}`)}
								onClick={() => onSimulationIntent(node, `cognition-node-${index}`)}
								className="min-w-[132px] snap-start rounded-2xl border border-neutral-200 bg-neutral-50 p-3 text-xs font-bold text-neutral-800 dark:border-neutral-800 dark:bg-neutral-950 dark:text-neutral-100"
							>
								<span className="block text-[10px] text-blue-600 dark:text-blue-300">Node {index + 1}</span>
								<span className="mt-1 block line-clamp-2">{node}</span>
							</a>
						))}
					</div>
				</div>
				<div className="space-y-3">
					{layers.map((layer, index) => (
						<details
							key={layer.id}
							open={index === 0}
							className="group rounded-2xl border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-800 dark:bg-neutral-950"
						>
							<summary className="flex cursor-pointer list-none items-center justify-between gap-3">
								<span>
									<span className="block text-[10px] font-mono uppercase tracking-[0.2em] text-neutral-500 dark:text-neutral-400">
										0{index + 1}
									</span>
									<span className="mt-1 block text-base font-black text-neutral-950 dark:text-neutral-50">{layer.label}</span>
								</span>
								<span className="text-neutral-400 transition group-open:rotate-180">⌄</span>
							</summary>
							<p className="mt-3 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">{layer.body}</p>
							<CTAButton type="button" level={index === 0 ? 1 : 2} size="sm" className="mt-3" onClick={layer.onAction}>
								{layer.action}
							</CTAButton>
						</details>
					))}
				</div>
			</div>
		</section>
	);
};

const ImmersiveArticleStory = ({
	postTitle,
	overview,
	flowNodes,
	architectureSequence,
	insightCards,
	tradeoffOptions,
	failureScenarios,
	animateArchitecture,
	reduceMotion,
	onToggleAnimation,
	getSimulationHref,
	onSimulationIntent,
}: {
	postTitle: string;
	overview: string;
	flowNodes: string[];
	architectureSequence: string[];
	insightCards: Array<{ title: string; icon: string; body: string }>;
	tradeoffOptions: Array<{ title: string; body: string }>;
	failureScenarios: Array<{ title: string; impact: string; mitigation: string; severity: number }>;
	animateArchitecture: boolean;
	reduceMotion: boolean | null;
	onToggleAnimation: () => void;
	getSimulationHref: (sectionTitle: string, sectionId?: string) => string;
	onSimulationIntent: (sectionTitle: string, sectionId?: string) => void;
}) => {
	const topologyNodes = flowNodes.length > 0 ? flowNodes.slice(0, 5) : architectureSequence.slice(0, 5);
	const storySections = insightCards.slice(0, 3);

	return (
		<section className="my-10 space-y-10">
			<div className="relative w-screen left-1/2 -translate-x-1/2 xl:w-auto xl:left-auto xl:translate-x-0 border-y xl:border border-violet-100 bg-gradient-to-br from-white via-violet-50/60 to-blue-50/70 py-8 dark:border-violet-950 dark:from-neutral-950 dark:via-violet-950/20 dark:to-blue-950/20 md:py-10 xl:rounded-3xl xl:px-6 xl:mx-0">
				<div className="mx-auto grid max-w-7xl gap-6 px-4 sm:px-6 lg:grid-cols-[minmax(0,0.84fr)_minmax(520px,1.16fr)] xl:grid-cols-1 lg:items-center">
					<div>
						<p className="text-[10px] font-mono uppercase tracking-[0.24em] text-violet-600 dark:text-violet-300">
							System lens
						</p>
						<h2 id="story-architecture" className="mt-3 text-2xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50 md:text-4xl">
							See {postTitle} as a living topology.
						</h2>
						<p className="mt-4 text-base leading-relaxed text-neutral-600 dark:text-neutral-300">
							{overview}
						</p>
						<div className="mt-5 flex flex-wrap gap-2">
							<CTALink
								href={getSimulationHref('Visual topology', 'story-architecture')}
								level={1}
								size="md"
								onClick={() => onSimulationIntent('Visual topology', 'story-architecture')}
							>
								Launch Section Simulation
							</CTALink>
							<CTAButton type="button" level={2} size="md" onClick={onToggleAnimation}>
								{animateArchitecture ? 'Pause Flow' : 'Play Flow'}
							</CTAButton>
						</div>
					</div>

					<div className="overflow-x-auto rounded-3xl border border-white/80 bg-white/80 p-4 shadow-2xl shadow-violet-500/10 backdrop-blur dark:border-neutral-800 dark:bg-neutral-950/80 dark:shadow-violet-950/20">
						<div className="relative min-w-[620px] rounded-2xl bg-[linear-gradient(to_right,rgba(99,102,241,0.08)_1px,transparent_1px),linear-gradient(to_bottom,rgba(99,102,241,0.08)_1px,transparent_1px)] bg-[size:28px_28px] p-5">
							<div className="grid grid-cols-5 gap-3">
								{topologyNodes.map((node, index) => (
									<div key={`${node}-${index}`} className="relative min-h-32 rounded-2xl border border-neutral-200 bg-white p-3 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
										<div className={`mb-3 h-10 w-10 rounded-2xl ${
											index % 3 === 0
												? 'bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-200'
												: index % 3 === 1
												? 'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-200'
												: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-200'
										} flex items-center justify-center text-sm font-black`}>
											{index + 1}
										</div>
										<p className="text-sm font-bold text-neutral-950 dark:text-neutral-50">{node}</p>
										<p className="mt-2 text-[11px] leading-relaxed text-neutral-500 dark:text-neutral-400">
											{index === 0 ? 'Ingress and assumptions' : index === topologyNodes.length - 1 ? 'Outcome and guarantees' : 'State transition'}
										</p>
										{index < topologyNodes.length - 1 ? (
											<motion.div
												aria-hidden="true"
												className="absolute -right-5 top-1/2 z-10 h-1 w-8 rounded-full bg-gradient-to-r from-violet-500 to-blue-500"
												animate={
													animateArchitecture && !reduceMotion
														? { opacity: [0.35, 1, 0.35], scaleX: [0.72, 1, 0.72] }
														: { opacity: 0.65, scaleX: 1 }
												}
												transition={{ duration: 1.8 + index * 0.18, repeat: animateArchitecture && !reduceMotion ? Infinity : 0 }}
											/>
										) : null}
									</div>
								))}
							</div>
							<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50/80 px-4 py-3 text-center text-sm font-bold text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-200">
								The article becomes easier when every section maps to a state change, a guarantee, or a failure boundary.
							</div>
						</div>
					</div>
				</div>
			</div>

			<div className="grid gap-4 md:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] md:items-start">
				<div className="md:sticky md:top-28">
					<p className="text-[10px] font-mono uppercase tracking-[0.24em] text-blue-600 dark:text-blue-300">
						Narrative transition
					</p>
					<h2 id="story-pacing" className="mt-2 text-2xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
						Move from explanation to operating judgment.
					</h2>
					<p className="mt-3 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
						Use these checkpoints as the conceptual pacing layer before continuing into the full article.
					</p>
				</div>
				<div className="space-y-3">
					{storySections.map((item, index) => (
						<div
							key={item.title}
							className={`rounded-2xl border p-4 ${
								index === 1
									? 'ml-0 border-blue-200 bg-blue-50/70 dark:border-blue-900 dark:bg-blue-950/20 md:ml-8'
									: 'border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900'
							}`}
						>
							<p className="text-sm font-bold text-neutral-950 dark:text-neutral-50">
								<span className="mr-2 text-violet-600 dark:text-violet-300">{item.icon}</span>
								{item.title}
							</p>
							<p className="mt-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">{item.body}</p>
						</div>
					))}
				</div>
			</div>

			<div className="grid gap-4 md:grid-cols-2">
				{tradeoffOptions.slice(0, 2).map((option, index) => (
					<div key={option.title} className={`rounded-2xl border p-5 ${
						index === 0
							? 'border-emerald-200 bg-emerald-50/70 dark:border-emerald-900 dark:bg-emerald-950/20'
							: 'border-amber-200 bg-amber-50/70 dark:border-amber-900 dark:bg-amber-950/20'
					}`}>
						<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-500 dark:text-neutral-400">
							Tradeoff path {index + 1}
						</p>
						<h3 className="mt-2 text-base font-extrabold text-neutral-950 dark:text-neutral-50">{option.title}</h3>
						<p className="mt-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">{option.body}</p>
					</div>
				))}
			</div>

			<div className="rounded-3xl border border-rose-200 bg-rose-50/60 p-5 dark:border-rose-950 dark:bg-rose-950/15">
				<div className="flex flex-wrap items-start justify-between gap-3">
					<div>
						<p className="text-[10px] font-mono uppercase tracking-[0.24em] text-rose-600 dark:text-rose-300">
							Failure rehearsal
						</p>
						<h2 id="story-failure" className="mt-2 text-xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
							Pressure-test the mental model.
						</h2>
					</div>
					<CTALink
						href={getSimulationHref('Failure rehearsal', 'story-failure')}
						level={2}
						size="sm"
						onClick={() => onSimulationIntent('Failure rehearsal', 'story-failure')}
					>
						Simulate Failure Mode
					</CTALink>
				</div>
				<div className="mt-4 space-y-3">
					{failureScenarios.map((scenario) => (
						<div key={scenario.title} className="rounded-2xl border border-white/80 bg-white/80 p-4 dark:border-neutral-800 dark:bg-neutral-950/70">
							<div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_120px] md:items-center">
								<div>
									<p className="text-sm font-bold text-neutral-950 dark:text-neutral-50">{scenario.title}</p>
									<p className="mt-1 text-xs leading-relaxed text-neutral-600 dark:text-neutral-300">{scenario.impact}</p>
									<p className="mt-1 text-xs leading-relaxed text-neutral-600 dark:text-neutral-300">
										Mitigation: <span className="font-semibold">{scenario.mitigation}</span>
									</p>
								</div>
								<div>
									<p className="text-right text-[11px] font-semibold text-rose-700 dark:text-rose-300">Risk {scenario.severity}%</p>
									<div className="mt-2 h-2 overflow-hidden rounded-full bg-rose-100 dark:bg-rose-950">
										<motion.div
											className="h-full rounded-full bg-rose-500"
											animate={{ width: `${scenario.severity}%` }}
											transition={{ duration: reduceMotion ? 0 : 0.45 }}
										/>
									</div>
								</div>
							</div>
						</div>
					))}
				</div>
			</div>

			<div className="rounded-3xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
				<p className="text-[10px] font-mono uppercase tracking-[0.24em] text-neutral-500 dark:text-neutral-400">
					Back to the article
				</p>
				<p className="mt-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
					Continue into the authored sections with the topology in mind: each heading should now answer what changes, what can fail, and what guarantee the system is trying to preserve.
				</p>
			</div>
		</section>
	);
};

type InterviewPromptSet = {
	relevanceScore: number;
	relevanceLabel: string;
	practiceQuestion: string;
	tradeoffPrompt: string;
	whiteboardPrompt: string;
	mockDiscussionPrompt: string;
	checkpoints: string[];
};

type ArticleCompanionData = {
	overview: string;
	summaryBullets: string[];
	flowNodes: string[];
	conceptDependencies: Array<{ concept: string; dependsOn: string | null }>;
	tradeoffOptions: Array<{ title: string; body: string }>;
	failureScenarios: Array<{ title: string; impact: string; mitigation: string; severity: number }>;
	interviewPrompts: InterviewPromptSet;
	quizPrompts: string[];
	relatedArticleRefs: Array<{ title: string; slug: string }>;
	deepDiveSections: Array<{ slug: string; title: string; summaryMarkdown: string; bulletMarkdown: string }>;
};

const getInterviewPromptSet = ({
	title,
	tags,
	flowNodes,
	tradeoffOptions,
	failureScenarios,
	tocItems,
}: {
	title: string;
	tags: NonNullable<PostFullFragment['tags']>;
	flowNodes: string[];
	tradeoffOptions: Array<{ title: string; body: string }>;
	failureScenarios: Array<{ title: string; impact: string; mitigation: string; severity: number }>;
	tocItems: TocItem[];
}): InterviewPromptSet => {
	const corpus = `${title} ${tags.map((tag) => tag.name).join(' ')} ${tocItems.map((item) => item.title).join(' ')}`.toLowerCase();
	const signals = [
		/system|design|architecture|distributed|scalability|database|kafka|consensus|replication/.test(corpus),
		/interview|tradeoff|failure|latency|throughput|consistency|availability/.test(corpus),
		flowNodes.length >= 3,
		failureScenarios.length > 0,
	].filter(Boolean).length;
	const relevanceScore = Math.min(96, 42 + signals * 14 + Math.min(10, tocItems.length));
	const primaryFlow = flowNodes.slice(0, 3).join(' -> ') || title;
	const tradeoff = tradeoffOptions[0]?.title || 'speed, correctness, and operational simplicity';
	const failure = failureScenarios[0]?.title || 'the most likely production failure mode';

	return {
		relevanceScore,
		relevanceLabel: relevanceScore >= 82 ? 'High interview signal' : relevanceScore >= 64 ? 'Useful interview practice' : 'Light interview practice',
		practiceQuestion: `Explain ${title} to a senior engineering interviewer in under two minutes. Include the core mechanism, one tradeoff, and one failure mode.`,
		tradeoffPrompt: `Help me explain the tradeoffs in ${title}. Compare ${tradeoff} with the alternative and give me interviewer follow-ups.`,
		whiteboardPrompt: `Whiteboard ${title} as a system design discussion. Use this flow: ${primaryFlow}. Include APIs, state, scaling limits, and failure recovery.`,
		mockDiscussionPrompt: `Start a mock interview discussion for ${title}. Interrupt me with clarification questions, scaling follow-ups, and tradeoff challenges.`,
		checkpoints: [
			`Clarify the problem boundary before explaining ${title}.`,
			`Draw the flow: ${primaryFlow}.`,
			`Name the main tradeoff: ${tradeoff}.`,
			`Handle failure scenario: ${failure}.`,
			`Close with observability, rollback, and scaling signals.`,
		],
	};
};

const buildLocalArticleCompanion = ({
	post,
	tags,
	tocItems,
	morePosts,
	primaryArticleConcept,
}: {
	post: PostFullFragment;
	tags: NonNullable<PostFullFragment['tags']>;
	tocItems: TocItem[];
	morePosts: PostFragment[];
	primaryArticleConcept: string;
}): ArticleCompanionData => {
	const summaryBullets = getAiSummaryBullets(post.content.markdown, post.title);
	const glossaryTerms = detectGlossaryTerms(post.content.markdown);
	const conceptDependencies = tags.slice(0, 6).map((tag, index) => ({
		concept: formatTagName(tag.name),
		dependsOn: index > 0 ? formatTagName(tags[index - 1].name) : null,
	}));
	const misunderstandingWarnings = (() => {
		const warnings = [
			'Low latency does not automatically mean high throughput under contention.',
			'Eventual consistency does not mean random correctness; it depends on reconciliation strategy.',
			'Retries without idempotency can amplify failures and duplicate side effects.',
		];
		if (/llm|rag|embedding|retrieval/i.test(post.content.markdown)) {
			warnings.unshift('High model quality can still produce incorrect outputs without grounding and verification.');
		}
		return warnings.slice(0, 3);
	})();
	const articleFlowNodes = deriveArticleFlowNodes(tocItems, tags, post.title);
	const summaryCandidates = summaryBullets
		.map((value) => stripTldrPrefix(normalizeTradeoffText(value)))
		.filter((value) => value.length > 25 && !/tool use|function_call|observation:|->>/i.test(value));
	const tradeoffOptions = sanitizeTradeoffOptions([
		{
			title: `${articleFlowNodes[0] || tags[0]?.name || 'Fast path'}: speed-first`,
			body: summaryCandidates[0] || 'Optimizes for faster understanding or delivery, but can hide edge cases.',
		},
		{
			title: `${articleFlowNodes[1] || tags[1]?.name || 'Safer path'}: reliability-first`,
			body: summaryCandidates[1] || 'Optimizes for correctness and clarity, with more upfront structure.',
		},
	]);
	const failureScenarios = [
		{
			title: `${articleFlowNodes[0] || 'Core concept'} misunderstood`,
			impact: misunderstandingWarnings[0] || `The reader may apply ${post.title} without understanding its assumptions.`,
			mitigation: tocItems[0]?.title ? `Revisit ${decodeHtml(tocItems[0].title)} and validate the first principles.` : 'Revisit the first principles and validate assumptions.',
			severity: 68,
		},
		{
			title: `${articleFlowNodes[1] || 'Implementation'} tradeoff missed`,
			impact: misunderstandingWarnings[1] || 'The design may optimize one property while quietly weakening another.',
			mitigation: tocItems[1]?.title ? `Compare against ${decodeHtml(tocItems[1].title)} and document the tradeoff.` : 'Document the tradeoff and add an operational check.',
			severity: 58,
		},
	];
	const interviewPrompts = getInterviewPromptSet({
		title: post.title,
		tags,
		flowNodes: articleFlowNodes,
		tradeoffOptions,
		failureScenarios,
		tocItems,
	});
	const quizPrompts = [
		`What is the core tradeoff explained in "${post.title}"?`,
		`Which failure mode is most likely if this design is deployed at scale?`,
		`How would you explain the architecture in a whiteboard interview?`,
	];

	return {
		overview:
			post.subtitle ||
			post.brief ||
			summaryBullets[0] ||
			`Understand ${post.title} through a practical engineering lens.`,
		summaryBullets,
		flowNodes: articleFlowNodes,
		conceptDependencies: conceptDependencies.length > 0 ? conceptDependencies : [{ concept: primaryArticleConcept, dependsOn: null }],
		tradeoffOptions,
		failureScenarios,
		interviewPrompts,
		quizPrompts,
		relatedArticleRefs: morePosts.slice(0, 4).map((item) => ({ title: item.title, slug: item.slug })),
		deepDiveSections: tocItems.slice(0, 4).map((item) => {
			const dive = deriveDeepDiveSummaries(post.content.markdown, tocItems)[item.slug];
			return {
				slug: item.slug,
				title: item.title,
				summaryMarkdown: dive?.summaryMarkdown || '',
				bulletMarkdown: dive?.bulletMarkdown || '',
			};
		}),
	};
};

const InterviewArticleOverlay = ({
	promptSet,
	onAsk,
	assistantHref,
	mockHref,
	whiteboardHref,
}: {
	promptSet: InterviewPromptSet;
	onAsk: (prompt: string) => void;
	assistantHref: string;
	mockHref: string;
	whiteboardHref: string;
}) => (
	<section className="my-8 overflow-hidden rounded-3xl border border-violet-200 bg-gradient-to-br from-white via-violet-50/70 to-blue-50/70 p-5 dark:border-violet-900 dark:from-neutral-950 dark:via-violet-950/20 dark:to-blue-950/20">
		<div className="grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(320px,0.55fr)]">
			<div>
				<div className="flex flex-wrap items-center gap-2">
					<span className="rounded-full bg-violet-100 px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-violet-700 dark:bg-violet-950 dark:text-violet-200">
						{promptSet.relevanceLabel}
					</span>
					<span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-neutral-600 shadow-sm dark:bg-neutral-900 dark:text-neutral-300">
						{promptSet.relevanceScore}% readiness relevance
					</span>
				</div>
				<h2 id="interview-mode" className="mt-3 text-2xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
					Reason through this article.
				</h2>
				<p className="mt-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
					Explain the mechanism, defend tradeoffs, sketch the architecture, and handle production failure follow-ups.
				</p>
				<div className="mt-4 grid gap-2 sm:grid-cols-2">
					<CTALink href={assistantHref} level={1} size="sm">Try a Reasoning Prompt</CTALink>
					<CTAButton type="button" level={2} size="sm" onClick={() => onAsk(promptSet.tradeoffPrompt)}>
						Explain Tradeoffs
					</CTAButton>
					<CTALink href={whiteboardHref} level={2} size="sm">Whiteboard This System</CTALink>
					<CTALink href={mockHref} level={3} size="sm">Start Mock Discussion</CTALink>
				</div>
			</div>
			<div className="rounded-2xl border border-white/80 bg-white/85 p-4 shadow-lg shadow-violet-500/10 dark:border-neutral-800 dark:bg-neutral-950/70">
				<p className="text-[11px] font-semibold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">System design checkpoints</p>
				<ol className="mt-3 space-y-2">
					{promptSet.checkpoints.map((checkpoint, index) => (
						<li key={checkpoint} className="grid grid-cols-[24px_minmax(0,1fr)] gap-2 text-xs leading-relaxed text-neutral-700 dark:text-neutral-300">
							<span className="flex h-6 w-6 items-center justify-center rounded-full bg-violet-100 text-[10px] font-black text-violet-700 dark:bg-violet-950 dark:text-violet-200">
								{index + 1}
							</span>
							<span>{checkpoint}</span>
						</li>
					))}
				</ol>
			</div>
		</div>
	</section>
);

type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
	footerPosts: PostFragment[];
	morePosts: PostFragment[];
	backmatter?: ArticleBackmatter | null;
};

type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
	footerPosts: PostFragment[];
};

type Props = PostProps | PageProps;

const Post = ({ publication, post, morePosts, backmatter }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';
	const [, setMobMount] = useState(false);
	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	const [animateArchitecture, setAnimateArchitecture] = useState(true);
	const [readingProgress, setReadingProgress] = useState(0);
	const [showQuizDrawer, setShowQuizDrawer] = useState(false);
	const [isBookmarked, setIsBookmarked] = useState(false);
	const [markedHelpful, setMarkedHelpful] = useState(false);
	const [articleCompanionState, setArticleCompanionState] = useState<ArticleCompanionData | null>(null);
	const completedMemoryRef = useRef(false);
	const reduceMotion = useReducedMotion();
	const { context, setContext, buildPrompt, getContextHref } = useLearningContext();
	const recordConceptSeen = useLearningMemoryStore((state) => state.recordConceptSeen);
	const recordConceptCompleted = useLearningMemoryStore((state) => state.recordConceptCompleted);
	useEmbeds({ enabled: canLoadEmbeds });

	if (post.hasLatexInPost) {
		setTimeout(() => handleMathJax(true), 500);
	}

	useEffect(() => {
		if (screen.width <= 425) setMobMount(true);
		if (!post) return;
		(async () => {
			await loadIframeResizer();
			triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
	}, []);

	useEffect(() => {
		const onScroll = () => {
			const doc = document.documentElement;
			const total = doc.scrollHeight - doc.clientHeight;
			const next = total > 0 ? Math.min(100, (doc.scrollTop / total) * 100) : 0;
			setReadingProgress(next);
		};
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	const tocItems = useMemo<TocItem[]>(() => {
		if (!post.features?.tableOfContents?.isEnabled) return [];
		const items = post.features.tableOfContents.items ?? [];
		if (items.length === 0) return [];

		return items.map((item) => ({
			id: item.id,
			slug: item.slug,
			title: item.title,
			level: item.level ?? 1,
			parentId: item.parentId ?? null,
		}));
	}, [post.features?.tableOfContents?.isEnabled, post.features?.tableOfContents?.items]);

	const tags = useMemo(() => post.tags ?? [], [post.tags]);
	const primaryArticleConcept = useMemo(() => inferPrimaryArticleConcept(post), [post]);
	const articleConceptSeeds = useMemo(() => getArticleConceptSeeds(post), [post]);
	const topicLearningSlug = useMemo(() => inferTopicSlugForPost(post), [post]);

	useEffect(() => {
		const primaryTag = tags[0] ? formatTagName(tags[0].name) : undefined;
		const primaryTopicSlug = tags[0]?.slug ?? topicLearningSlug;
		const secondaryTag = tags[1] ? formatTagName(tags[1].name) : undefined;
		const subtopicHref = post.series?.slug
			? `/series/${post.series.slug}`
			: tags[1]?.slug
				? `/topic/${tags[1].slug}`
				: undefined;
		setContext({
			source: 'article',
			pathname: `/${post.slug}`,
			title: post.title,
			slug: post.slug,
			domain: primaryTag ? 'Engineering' : 'Abstract Algorithms',
			topic: primaryTag ?? post.series?.name ?? post.title,
			subtopic: post.series?.name ?? secondaryTag,
			subtopicHref,
			concept: primaryArticleConcept,
			roadmapNode: primaryArticleConcept,
			roadmapHref: `/topic/${primaryTopicSlug}`,
			simulationTopic: primaryArticleConcept,
		});
		recordConceptSeen({
			label: primaryArticleConcept,
			domain: primaryTag ?? post.series?.name,
			slug: post.slug,
		});
	}, [post.series?.name, post.series?.slug, post.slug, post.title, primaryArticleConcept, recordConceptSeen, setContext, tags, topicLearningSlug]);

	useEffect(() => {
		completedMemoryRef.current = false;
	}, [post.slug]);

	useEffect(() => {
		if (readingProgress < 85) return;
		if (completedMemoryRef.current) return;
		completedMemoryRef.current = true;
		const primaryTag = tags[0] ? formatTagName(tags[0].name) : undefined;
		recordConceptCompleted({
			label: post.title,
			domain: primaryTag ?? post.series?.name,
			slug: post.slug,
			minutes: post.readTimeInMinutes,
		});
		tags.slice(0, 4).forEach((tag) => {
			recordConceptCompleted({
				label: formatTagName(tag.name),
				domain: primaryTag,
			});
		});
	}, [post.readTimeInMinutes, post.series?.name, post.slug, post.title, readingProgress, recordConceptCompleted, tags]);

	const localArticleCompanion = useMemo(
		() => buildLocalArticleCompanion({ post, tags, tocItems, morePosts, primaryArticleConcept }),
		[morePosts, post, primaryArticleConcept, tags, tocItems],
	);

	useEffect(() => {
		let isActive = true;
		const controller = new AbortController();
		setArticleCompanionState(null);

		(async () => {
			try {
				const response = await fetch('/api/article-companion', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({
						title: post.title,
						subtitle: post.subtitle,
						brief: post.brief,
						markdown: post.content.markdown,
						tocItems,
						tags: tags.map((tag) => ({ name: tag.name, slug: tag.slug })),
						relatedPosts: morePosts,
						readTimeInMinutes: post.readTimeInMinutes,
					}),
					signal: controller.signal,
				});

				if (!response.ok) {
					throw new Error(`Article companion request failed with ${response.status}`);
				}

				const data = (await response.json()) as ArticleCompanionData;
				if (!isActive) return;
				if (data?.overview && Array.isArray(data.summaryBullets)) {
					setArticleCompanionState(data);
				}
			} catch (error) {
				if (!isActive || controller.signal.aborted) return;
				console.error('[article-companion] request failed:', error);
			}
		})();

		return () => {
			isActive = false;
			controller.abort();
		};
	}, [morePosts, post.brief, post.content.markdown, post.readTimeInMinutes, post.slug, post.subtitle, post.title, tags, tocItems]);

	const articleCompanion = articleCompanionState ?? localArticleCompanion;
	const aiSummaryBullets = useMemo(() => {
		const override = normalizeBackmatterList(backmatter?.executiveTldr);
		if (override.length > 0) return override;
		return articleCompanion.summaryBullets;
	}, [articleCompanion.summaryBullets, backmatter?.executiveTldr]);
	const articleFlowNodes = useMemo(() => {
		const overrideNodes = normalizeBackmatterList(backmatter?.keySystemsVisualization?.nodes);
		if (overrideNodes.length > 0) return overrideNodes;
		return articleCompanion.flowNodes;
	}, [articleCompanion.flowNodes, backmatter?.keySystemsVisualization?.nodes]);
	const conceptDependencies = articleCompanion.conceptDependencies;
	const tradeoffOptions = useMemo(() => {
		const primary = sanitizeTradeoffOptions(articleCompanion.tradeoffOptions || []);
		if (primary.length > 0) return primary;
		return sanitizeTradeoffOptions(localArticleCompanion.tradeoffOptions || []);
	}, [articleCompanion.tradeoffOptions, localArticleCompanion.tradeoffOptions]);
	const failureScenarios = articleCompanion.failureScenarios;
	const quizPrompts = articleCompanion.quizPrompts;
	const interviewPrompts = articleCompanion.interviewPrompts;
	const storyOverview = articleCompanion.overview;
	const glossaryTerms = useMemo(() => detectGlossaryTerms(post.content.markdown), [post.content.markdown]);
	const architectureSequence = useMemo(() => {
		if (articleFlowNodes.length >= 3) return articleFlowNodes;
		const fromToc = tocItems
			.map((item) => item.title.trim())
			.filter(Boolean)
			.slice(0, 5);
		if (fromToc.length >= 3) return fromToc;

		const fromTags = tags
			.map((tag) => `${formatTagName(tag.name)} foundation`)
			.slice(0, 4);
		if (fromTags.length >= 3) return fromTags;

		const markdown = post.content.markdown.toLowerCase();
		const heuristic: string[] = [];
		if (/request|ingress|api|gateway/.test(markdown)) heuristic.push('Request ingress');
		if (/validate|auth|policy/.test(markdown)) heuristic.push('Validation and policy');
		if (/persist|storage|database|state/.test(markdown)) heuristic.push('State update');
		if (/event|queue|stream|kafka/.test(markdown)) heuristic.push('Event propagation');
		if (/monitor|observ|retry|recovery|fail/.test(markdown)) heuristic.push('Recovery and observability');

		return heuristic.length >= 3
			? heuristic.slice(0, 5)
			: ['Foundations', 'Core mechanism', 'State flow', 'Failure handling', 'Production hardening'];
	}, [articleFlowNodes, tocItems, tags, post.content.markdown]);
	const insightCards = useMemo(() => {
		const source = [
			{ title: 'Why this matters', icon: '!', body: aiSummaryBullets[0] || post.brief || post.subtitle || `Understand the core idea behind ${post.title}.` },
			{ title: 'Key section to watch', icon: '#', body: tocItems[1]?.title ? `Pay attention to "${decodeHtml(tocItems[1].title)}"; it usually contains the main mechanism or tradeoff.` : `Use the first sections to identify the main mechanism and its constraints.` },
			{ title: 'Interview angle', icon: '?', body: `Be ready to explain ${articleFlowNodes.slice(0, 2).join(' and ') || post.title} with one concrete example and one tradeoff.` },
			{
				title: 'Production concern',
				icon: '!',
				body:
					glossaryTerms[0]
						? `${glossaryTerms[0][0]}: ${glossaryTerms[0][1]}`
						: `Map the idea to failure modes, monitoring signals, and rollback behavior before implementation.`,
			},
		];
		return source.slice(0, 4);
	}, [aiSummaryBullets, articleFlowNodes, glossaryTerms, post.brief, post.subtitle, post.title, tocItems]);
	const deepDiveSummaries = useMemo(
		() =>
			(articleCompanion.deepDiveSections?.length ? articleCompanion.deepDiveSections : localArticleCompanion.deepDiveSections).reduce<Record<string, { summaryMarkdown: string; bulletMarkdown: string }>>(
				(acc, item) => {
					acc[item.slug] = {
						summaryMarkdown: item.summaryMarkdown,
						bulletMarkdown: item.bulletMarkdown,
					};
					return acc;
				},
				{},
			),
		[articleCompanion.deepDiveSections, localArticleCompanion.deepDiveSections],
	);
	const atGlanceMetadata = useMemo(
		() => [
			`${post.readTimeInMinutes > 12 ? 'Advanced' : 'Intermediate'} level`,
			`${Math.max(5, tocItems.length)} concepts`,
			`${post.readTimeInMinutes} min`,
			`${conceptDependencies.slice(0, 2).map((item) => item.concept).join(', ') || 'Foundations'}`,
		],
		[conceptDependencies, post.readTimeInMinutes, tocItems.length],
	);
	const upNextPost = morePosts[0] ?? null;

	const getSimulationHrefForSection = (sectionTitle: string, sectionId?: string) => {
		const params = new URLSearchParams({
			q: post.title,
			from: `/${post.slug}`,
			section: sectionTitle,
			node: sectionTitle,
		});
		if (sectionId) params.set('sectionId', sectionId);
		return `/visualizations?${params.toString()}`;
	};

	const syncSimulationContext = (sectionTitle: string, sectionId?: string) => {
		setContext({
			source: 'article',
			pathname: `/${post.slug}`,
			title: post.title,
			slug: post.slug,
			sectionId,
			sectionTitle,
			roadmapNode: sectionTitle,
			simulationTopic: post.title,
		});
	};
	const interviewAssistantHref = `/assistant?q=${encodeURIComponent(buildPrompt(interviewPrompts.practiceQuestion))}`;
	const whiteboardHref = `/assistant?q=${encodeURIComponent(buildPrompt(interviewPrompts.whiteboardPrompt))}`;
	const handleAiExplain = (section: string) => {
		window.location.href = `/assistant?q=${encodeURIComponent(
			buildPrompt(`Explain ${section} from ${post.title} in simpler terms.`),
		)}`;
	};

	const openArticleChat = (question?: string) => {
		const currentQuestion =
			question ||
			buildPrompt(`Summarize the key ideas in "${post.title}" and explain what I should focus on.`);
		window.dispatchEvent(
			new CustomEvent('open-chatbot', {
				detail: {
					question: currentQuestion,
				},
			}),
		);
	};

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta
					name="description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }} />
			</Head>

			<div className="mx-auto mt-10 grid max-w-7xl gap-10 2xl:grid-cols-[minmax(0,1fr)_220px] 2xl:items-start">
				<div className="min-w-0">
					<div className="mx-auto mb-10 w-full max-w-none">
						<div className="mb-3 flex flex-wrap items-center gap-2 text-[11px]">
							<ContextualBreadcrumbs compact />
						</div>
						<div className="mb-4 flex flex-wrap items-center gap-2">
							<span className="inline-flex rounded-full border border-neutral-200 bg-white px-2.5 py-1 text-[11px] text-neutral-600 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300">
								{post.readTimeInMinutes} min read
							</span>
							{tags.slice(0, 3).map((tag) => (
								<Link
									key={`hero-tag-${tag.id}`}
									href={`/tag/${tag.slug}`}
									className="inline-flex rounded-full border border-neutral-200 bg-white px-2.5 py-1 text-[11px] text-neutral-600 transition-colors hover:border-blue-200 hover:text-blue-700 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-300 dark:hover:border-blue-800 dark:hover:text-blue-300"
								>
									{formatTagName(tag.name)}
								</Link>
							))}
						</div>
						<h1 className="text-4xl font-extrabold leading-[1.08] tracking-tight text-neutral-950 dark:text-neutral-50 md:text-6xl">
							{post.title}
						</h1>
						{post.subtitle ? (
							<p className="mt-5 text-lg leading-relaxed text-neutral-600 dark:text-neutral-300 md:text-xl">
								{post.subtitle}
							</p>
						) : null}
						<div className="mt-6 flex flex-wrap items-center gap-x-3 gap-y-2 text-sm text-neutral-500 dark:text-neutral-400">
							{post.author.profilePicture ? (
								<img
									src={resizeImage(post.author.profilePicture, { w: 80, h: 80, c: 'face' })}
									alt={post.author.name}
									className="h-8 w-8 rounded-full ring-2 ring-neutral-100 dark:ring-neutral-800"
								/>
							) : null}
							<span className="font-semibold text-neutral-700 dark:text-neutral-200">{post.author.name}</span>
							<span className="text-neutral-300 dark:text-neutral-700">/</span>
							<time><DateFormatter dateString={post.publishedAt} /></time>
							{post.series ? (
								<>
									<span className="text-neutral-300 dark:text-neutral-700">/</span>
									<Link href={`/series/${post.series.slug}`} className="font-semibold text-blue-600 hover:text-blue-700 dark:text-blue-300 dark:hover:text-blue-200">
										{post.series.name}
									</Link>
								</>
							) : null}
						</div>
					</div>

					{tocItems.length > 0 ? (
						<section className="mx-auto mb-8 w-full max-w-none rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
							<p className="text-[11px] font-mono uppercase tracking-[0.2em] text-neutral-500 dark:text-neutral-400">On this page</p>
							<div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
								{tocItems.slice(0, 9).map((item) => (
									<a
										key={`inline-toc-${item.id}`}
										href={`#heading-${item.slug}`}
										className="rounded-xl border border-neutral-100 px-3 py-2 text-sm font-semibold leading-snug text-neutral-600 transition-colors hover:border-blue-200 hover:text-blue-700 dark:border-neutral-800 dark:text-neutral-300 dark:hover:border-blue-800 dark:hover:text-blue-300"
									>
										{decodeHtml(item.title)}
									</a>
								))}
							</div>
						</section>
					) : null}

					<ArticleEngagement post={post} publication={publication} />

					<section className="mx-auto w-full max-w-none rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900 md:p-6">
						<p className="text-[11px] font-mono uppercase tracking-[0.2em] text-blue-600 dark:text-blue-300">Executive TLDR</p>
						<ul className="mt-4 space-y-3 text-sm leading-relaxed text-neutral-700 dark:text-neutral-300">
							{aiSummaryBullets.slice(0, 4).map((item) => (
								<li key={item} className="flex gap-3">
									<span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-500" />
									<span>{item}</span>
								</li>
							))}
						</ul>
					</section>

					<section className="mx-auto mt-8 w-full max-w-none">
						<p className="text-[11px] font-mono uppercase tracking-[0.2em] text-neutral-500 dark:text-neutral-400">Core mental model</p>
						<h2 className="mt-3 text-2xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
							Read this as a system of state, constraints, and failure boundaries.
						</h2>
						<p className="mt-4 text-base leading-relaxed text-neutral-700 dark:text-neutral-300">
							{storyOverview}
						</p>
						<div className="mt-5 flex flex-wrap gap-2">
							<Link href={`/assistant?q=${encodeURIComponent(buildPrompt(`Explain the mental model behind ${post.title} in simpler terms.`))}`} className="inline-flex rounded-lg border border-neutral-200 px-3 py-2 text-sm font-semibold text-neutral-700 transition-colors hover:border-blue-300 hover:text-blue-700 dark:border-neutral-700 dark:text-neutral-200 dark:hover:border-blue-700 dark:hover:text-blue-300">
								Explain simpler
							</Link>
							<Link href={`/assistant?q=${encodeURIComponent(buildPrompt(interviewPrompts.tradeoffPrompt))}`} className="inline-flex rounded-lg border border-neutral-200 px-3 py-2 text-sm font-semibold text-neutral-700 transition-colors hover:border-blue-300 hover:text-blue-700 dark:border-neutral-700 dark:text-neutral-200 dark:hover:border-blue-700 dark:hover:text-blue-300">
								Compare tradeoffs
							</Link>
						</div>
					</section>

					<section className="mx-auto mt-10 w-full max-w-none rounded-2xl border border-neutral-200 bg-neutral-50 p-5 dark:border-neutral-800 dark:bg-neutral-900/60 md:p-6">
						<div className="mx-auto max-w-none">
							<p className="text-[11px] font-mono uppercase tracking-[0.2em] text-neutral-500 dark:text-neutral-400">Key systems visualization</p>
							<h2 className="mt-3 text-2xl font-extrabold tracking-tight text-neutral-950 dark:text-neutral-50">
								The article’s conceptual path
							</h2>
						</div>
						{backmatter?.mermaidDiagram ? (
							<div className="mt-6 overflow-x-auto pb-2">
								<div className="rounded-xl border border-blue-200 bg-white p-4 dark:border-blue-900 dark:bg-blue-950/20">
									<div className="mermaid">
										{backmatter.mermaidDiagram}
									</div>
								</div>
							</div>
						) : (
							<div className="mt-6 overflow-x-auto pb-2">
								<div className="flex min-w-max items-stretch gap-3">
									{articleFlowNodes.slice(0, 5).map((node, index) => (
										<div key={`${node}-${index}`} className="flex items-center gap-3">
											<div className="w-44 rounded-xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-950">
												<p className="text-[11px] font-semibold text-blue-600 dark:text-blue-300">0{index + 1}</p>
												<p className="mt-2 text-sm font-bold leading-snug text-neutral-950 dark:text-neutral-50">{decodeHtml(node)}</p>
											</div>
											{index < Math.min(articleFlowNodes.length, 5) - 1 ? (
												<span className="text-neutral-300 dark:text-neutral-700">{'->'}</span>
											) : null}
										</div>
									))}
								</div>
							</div>
						)}
					</section>

					<div className="article-doc mx-auto mt-12 w-full max-w-none min-w-0">
						<MarkdownToHtml contentMarkdown={post.content.markdown} />
					</div>





					<section className="mx-auto mt-10 w-full max-w-none rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
						<p className="text-[11px] font-mono uppercase tracking-[0.2em] text-neutral-500 dark:text-neutral-400">Quiet AI help</p>
						<div className="mt-4 grid gap-3 sm:grid-cols-3">
							<Link href={`/assistant?q=${encodeURIComponent(buildPrompt(`Explain ${post.title} more simply, preserving the engineering details.`))}`} className="rounded-xl border border-neutral-200 px-3 py-3 text-sm font-semibold text-neutral-700 transition-colors hover:border-blue-300 hover:text-blue-700 dark:border-neutral-700 dark:text-neutral-200 dark:hover:border-blue-700 dark:hover:text-blue-300">
								Explain simpler
							</Link>
							<Link href={`/assistant?q=${encodeURIComponent(buildPrompt(interviewPrompts.tradeoffPrompt))}`} className="rounded-xl border border-neutral-200 px-3 py-3 text-sm font-semibold text-neutral-700 transition-colors hover:border-blue-300 hover:text-blue-700 dark:border-neutral-700 dark:text-neutral-200 dark:hover:border-blue-700 dark:hover:text-blue-300">
								Compare approaches
							</Link>
							<Link href={`/assistant?q=${encodeURIComponent(buildPrompt(`What should I read next after ${post.title}?`))}`} className="rounded-xl border border-neutral-200 px-3 py-3 text-sm font-semibold text-neutral-700 transition-colors hover:border-blue-300 hover:text-blue-700 dark:border-neutral-700 dark:text-neutral-200 dark:hover:border-blue-700 dark:hover:text-blue-300">
								What next?
							</Link>
						</div>
					</section>

					{/* Tags */}
					{tags.length > 0 && (
						<div className="mx-auto mt-10 w-full max-w-none border-t border-neutral-100 pt-8 dark:border-neutral-800">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-3">
								Article metadata
							</p>
							<ul className="flex flex-wrap gap-2 list-none m-0 p-0">
								{tags.map((tag) => (
									<li key={tag.id} className="m-0 p-0">
										<Link
											href={`/tag/${tag.slug}`}
											className="inline-flex items-center px-3 py-1 bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400 rounded-full text-xs font-mono border border-neutral-200 dark:border-neutral-700 hover:bg-blue-50 hover:text-blue-700 hover:border-blue-200 dark:hover:bg-blue-950 dark:hover:text-blue-300 dark:hover:border-blue-800 transition-colors"
										>
											{formatTagName(tag.name)}
										</Link>
									</li>
								))}
							</ul>
						</div>
					)}

					{/* Author Card */}
					<div className="mx-auto mt-10 flex w-full max-w-none items-center gap-4 rounded-xl border border-neutral-200 bg-neutral-50 p-5 dark:border-neutral-800 dark:bg-neutral-900">
						{post.author.profilePicture && (
							<img
								src={resizeImage(post.author.profilePicture, { w: 120, h: 120, c: 'face' })}
								alt={post.author.name}
								className="w-14 h-14 rounded-full ring-2 ring-neutral-200 dark:ring-neutral-700 flex-shrink-0"
							/>
						)}
						<div className="min-w-0 flex-1">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-0.5">
								Written by
							</p>
							<p className="font-semibold text-neutral-900 dark:text-neutral-100 text-sm">
								{post.author.name}
							</p>
							<p className="text-xs text-neutral-400 dark:text-neutral-500 mt-0.5 font-mono">
								@{post.author.username}
							</p>
						</div>
					</div>

					{/* Related deep dives */}
					{morePosts.length > 1 ? (
					<section className="mx-auto mt-10 w-full max-w-none rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
						<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-3">
							Related deep dives
						</p>
						<div className="grid grid-cols-1 gap-3 md:grid-cols-3">
							{morePosts.slice(1, 4).map((nextPost) => {
								const nextCoverImage = normalizeCoverImageUrl(nextPost.coverImage?.url);
								return (
									<Link
										key={nextPost.id}
										href={`/${nextPost.slug}`}
										className="rounded-lg border border-neutral-200 dark:border-neutral-700 p-3 hover:border-blue-300 dark:hover:border-blue-500 transition-colors"
									>
										{nextCoverImage ? (
											<img
												src={nextCoverImage}
												alt={nextPost.title}
												className="mb-2 h-24 w-full rounded-md object-cover"
											/>
										) : (
											<div className="mb-2 h-24 w-full rounded-md bg-gradient-to-br from-blue-100 via-indigo-100 to-teal-100 dark:from-blue-950/40 dark:via-indigo-950/30 dark:to-teal-950/30" />
										)}
										<p className="text-sm font-semibold text-neutral-900 dark:text-neutral-100 line-clamp-2">
											{nextPost.title}
										</p>
										<p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
											{nextPost.readTimeInMinutes} min read
										</p>
									</Link>
								);
							})}
						</div>
					</section>
					) : null}

					<section className="mx-auto mt-8 w-full max-w-none rounded-xl border border-blue-200 bg-blue-50/60 p-4 dark:border-blue-900 dark:bg-blue-950/20">
						<p className="text-[10px] font-mono uppercase tracking-widest text-blue-600 dark:text-blue-300 mb-2">
							Continue reading
						</p>
						{upNextPost ? (
							<div className="grid grid-cols-1 gap-3 md:grid-cols-[minmax(0,1fr)_auto] md:items-center">
								<Link href={`/${upNextPost.slug}`} className="block rounded-lg border border-blue-200 bg-white p-3 transition-colors hover:border-blue-400 dark:border-blue-900 dark:bg-neutral-950 dark:hover:border-blue-600">
									<p className="text-sm font-semibold text-neutral-900 dark:text-neutral-100">{upNextPost.title}</p>
									<p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
										{upNextPost.readTimeInMinutes} min · {upNextPost.tags?.[0]?.name ? `${formatTagName(upNextPost.tags[0].name)} · ` : ''}best next step
									</p>
								</Link>
								<CTALink href={`/topic/${topicLearningSlug}`} level={1} size="sm">
									Open Collection
								</CTALink>
							</div>
						) : (
							<div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_auto] md:items-center">
								<p className="text-xs text-neutral-500 dark:text-neutral-400">Continue through the broader topic instead of stopping at this article.</p>
								<CTALink href={`/topic/${topicLearningSlug}`} level={1} size="sm">
									Open Collection
								</CTALink>
							</div>
						)}
					</section>

				</div>

				<aside className="hidden 2xl:block">
					<div className="sticky top-24 space-y-5">
						<div className="rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
							<p className="text-[11px] font-mono uppercase tracking-[0.2em] text-neutral-500 dark:text-neutral-400">On this page</p>
							<div className="mt-3 space-y-2">
								{tocItems.slice(0, 7).map((item) => (
									<a key={`quiet-toc-${item.id}`} href={`#heading-${item.slug}`} className="block text-sm leading-snug text-neutral-600 transition-colors hover:text-blue-700 dark:text-neutral-300 dark:hover:text-blue-300">
										{decodeHtml(item.title)}
									</a>
								))}
							</div>
						</div>
						<Link href={`/topic/${topicLearningSlug}`} className="block rounded-2xl border border-blue-200 bg-blue-50/70 p-4 text-sm font-semibold text-blue-800 transition-colors hover:border-blue-300 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">
							Explore related concept
						</Link>
					</div>
				</aside>
			</div>

			<ScrollButtons />
		</>
	);
};

const Page = ({ page }: PageProps) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title}</title>
			</Head>
			<MarkdownToHtml contentMarkdown={page.content.markdown} />
		</>
	);
};

export default function PostOrPage(props: Props) {
	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;

	return (
		<AppProvider publication={publication} post={maybePost} page={maybePage} footerPosts={props.footerPosts}>
			<Layout>
				{props.type === 'post' && <ReadingProgressBar />}
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-7xl mx-auto w-full px-4 sm:px-5 pt-4 pb-28 md:pt-5 md:pb-20 overflow-x-hidden">
						<article className="w-full min-w-0">
							{props.type === 'post' && <Post {...props} />}
							{props.type === 'page' && <Page {...props} />}
						</article>
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		const footerPosts = await getFooterPosts();
		const currentPost = postData.publication.post;
		const currentDomain = inferArticleDomain(currentPost);
		const currentConcept = inferPrimaryArticleConcept(currentPost).toLowerCase();
		const domainTerms: Record<string, RegExp> = {
			'probabilistic-data-structures': /hyperloglog|bloom filter|count-min sketch|cardinality|probabilistic|sketch|membership|frequency estimation/i,
			'data-structures': /data structure|algorithm|tree|graph|heap|hash|sketch|complexity/i,
			'distributed-systems': /distributed|consensus|quorum|replication|leader|transaction|clock|split brain|kafka/i,
			'ai-systems': /llm|rag|embedding|vector|model|inference|softmax|machine learning/i,
			'system-design': /system design|architecture|scaling|load balancer|cache|sharding/i,
			backend: /api|database|backend|microservice|queue|redis|postgres/i,
			general: /./i,
		};

		// ── Compute related posts from footerPosts by tag overlap + title similarity ──
		const currentTagSlugs = new Set((currentPost.tags ?? []).map((t) => t.slug));
		const currentKeywords = currentPost.title
			.toLowerCase()
			.replace(/[^\w\s]/g, ' ')
			.split(/\s+/)
			.filter((w) => w.length > 3);

		const scored = footerPosts
			.filter((p) => p.slug !== slug)
			.map((p) => {
				const tagScore = (p.tags ?? []).filter((t) => currentTagSlugs.has(t.slug)).length * 10;
				const titleWords = p.title.toLowerCase();
				const briefWords = (p.brief ?? '').toLowerCase();
				const haystack = `${titleWords} ${briefWords} ${(p.tags ?? []).map((tag) => `${tag.name} ${tag.slug}`).join(' ')}`;
				const kwScore = currentKeywords.reduce((s, w) => {
					return s + (titleWords.includes(w) ? 3 : 0) + (briefWords.includes(w) ? 1 : 0);
				}, 0);
				const domainScore = domainTerms[currentDomain]?.test(haystack) ? 14 : 0;
				const conceptScore = currentConcept && haystack.includes(currentConcept) ? 8 : 0;
				const distributedPenalty =
					currentDomain !== 'distributed-systems' && domainTerms['distributed-systems'].test(haystack) ? -10 : 0;
				const partitioningPenalty =
					currentDomain === 'probabilistic-data-structures' && /partition|sharding|sql|nosql|cassandra|dynamodb|mongodb/i.test(haystack)
						? -16
						: 0;
				return { post: p, score: tagScore + kwScore + domainScore + conceptScore + distributedPenalty + partitioningPenalty };
			})
			.filter(({ score }) => score > 0)
			.sort((a, b) => b.score - a.score);

		// Require at least a tag match (>=10) or strong keyword overlap (>=6)
		const threshold = scored[0]?.score >= 10 ? 10 : 6;
		const morePosts = scored
			.filter(({ score }) => score >= threshold)
			.slice(0, 4)
			.map(({ post }) => post);

		const { cleanMarkdown, backmatter } = parseArticleBackmatter(currentPost.content.markdown);
		const postWithBackmatter: PostFullFragment = {
			...currentPost,
			content: {
				...currentPost.content,
				markdown: cleanMarkdown,
			},
		};

		return {
			props: {
				type: 'post',
				post: postWithBackmatter,
				backmatter,
				publication: postData.publication,
				footerPosts,
				morePosts,
			},
			revalidate: 1,
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		const footerPosts = await getFooterPosts();
		return {
			props: {
				type: 'page',
				page: pageData.publication.staticPage,
				publication: pageData.publication,
				footerPosts,
			},
			revalidate: 1,
		};
	}

	return {
		notFound: true,
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => ({ params: { slug } })),
		fallback: 'blocking',
	};
}
