import { resizeImage } from '@starter-kit/utils/image';
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';

// ─── Reading Progress Bar ─────────────────────────────────────────────────────
const ReadingProgressBar = () => {
	const [progress, setProgress] = useState(0);

	useEffect(() => {
		const onScroll = () => {
			const el = document.documentElement;
			const scrolled = el.scrollTop;
			const total = el.scrollHeight - el.clientHeight;
			setProgress(total > 0 ? Math.min(100, (scrolled / total) * 100) : 0);
		};
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	return (
		<div
			aria-hidden="true"
			className="fixed top-0 left-0 z-50 w-full h-0.5 bg-transparent pointer-events-none"
		>
			<div
				className="h-full bg-blue-500 dark:bg-blue-400"
				style={{ width: `${progress}%`, transition: 'width 80ms linear' }}
			/>
		</div>
	);
};
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { CoverImage } from '../components/cover-image';
import { DateFormatter } from '../components/date-formatter';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	PageByPublicationDocument,
	PostFragment,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';
import { getFooterPosts } from '../lib/api/footerData';

type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
	footerPosts: PostFragment[];
};

type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
	footerPosts: PostFragment[];
};

type Props = PostProps | PageProps;

const Post = ({ publication, post }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';
	const [, setMobMount] = useState(false);
	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	useEmbeds({ enabled: canLoadEmbeds });

	if (post.hasLatexInPost) {
		setTimeout(() => handleMathJax(true), 500);
	}

	useEffect(() => {
		if (screen.width <= 425) setMobMount(true);
		if (!post) return;
		(async () => {
			await loadIframeResizer();
			triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
	}, []);

	const coverImageSrc = !!post.coverImage?.url
		? resizeImage(post.coverImage.url, { w: 1600, h: 840, c: 'thumb' })
		: undefined;

	const tocItems =
		post.features?.tableOfContents?.isEnabled &&
		(post.features.tableOfContents.items ?? []).length > 0
			? post.features.tableOfContents.items ?? []
			: [];

	const tags = post.tags ?? [];

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta
					name="description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }} />
			</Head>

			{/* ── Back Navigation ── */}
			<Link
				href="/"
				className="inline-flex items-center gap-1.5 text-sm text-neutral-400 dark:text-neutral-500 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-8 group"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 20 20"
					fill="currentColor"
					className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform"
				>
					<path
						fillRule="evenodd"
						d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z"
						clipRule="evenodd"
					/>
				</svg>
				All Posts
			</Link>

			{/* ── Post Hero: header + cover image side-by-side ── */}
			<div className={`flex flex-col ${coverImageSrc ? 'md:flex-row md:items-center md:gap-10' : ''} mb-12`}>
				{/* Left: title, subtitle, meta */}
				<div className={coverImageSrc ? 'flex-1 min-w-0' : 'w-full'}>
					<h1 className="text-4xl md:text-5xl font-extrabold leading-[1.15] tracking-tight text-neutral-900 dark:text-neutral-50 mb-4">
						{post.title}
					</h1>

					{post.subtitle && (
						<p className="text-xl text-neutral-500 dark:text-neutral-400 leading-relaxed font-normal mb-6">
							{post.subtitle}
						</p>
					)}

					{/* Meta row */}
					<div className="flex flex-wrap items-center gap-x-3 gap-y-2 pt-5 border-t border-neutral-100 dark:border-neutral-800">
						<div className="flex items-center gap-2">
							{post.author.profilePicture && (
								<img
									src={resizeImage(post.author.profilePicture, { w: 80, h: 80, c: 'face' })}
									alt={post.author.name}
									className="w-7 h-7 rounded-full ring-2 ring-neutral-100 dark:ring-neutral-800"
								/>
							)}
							<span className="text-sm font-semibold text-neutral-700 dark:text-neutral-300">
								{post.author.name}
							</span>
						</div>
						<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
						<time className="text-sm text-neutral-400 dark:text-neutral-500">
							<DateFormatter dateString={post.publishedAt} />
						</time>
						<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
						<span className="inline-flex items-center gap-1 text-sm text-neutral-400 dark:text-neutral-500">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								viewBox="0 0 20 20"
								fill="currentColor"
								className="w-3.5 h-3.5"
							>
								<path
									fillRule="evenodd"
									d="M10 18a8 8 0 100-16 8 8 0 000 16zm.75-13a.75.75 0 00-1.5 0v5c0 .414.336.75.75.75h4a.75.75 0 000-1.5h-3.25V5z"
									clipRule="evenodd"
								/>
							</svg>
							{post.readTimeInMinutes} min read
						</span>
						{post.reactionCount > 0 && (
							<>
								<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
								<span className="text-sm text-neutral-400 dark:text-neutral-500">
									♥ {post.reactionCount}
								</span>
							</>
						)}
					</div>
				</div>

				{/* Right: cover image */}
				{!!coverImageSrc && (
					<div className="w-full md:w-2/5 shrink-0 mt-8 md:mt-0 h-52 md:h-64 rounded-xl overflow-hidden ring-1 ring-neutral-200 dark:ring-neutral-800 shadow-sm">
						<img
							src={coverImageSrc}
							alt={`Cover Image for ${post.title}`}
							className="w-full h-full object-cover"
						/>
					</div>
				)}
			</div>

			{/* ── Table of Contents ── */}
			{tocItems.length > 0 && (
				<nav
					aria-label="Table of contents"
					className="mb-10 p-5 rounded-xl bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800"
				>
					<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-3">
						In this article
					</p>
					<ol className="flex flex-col gap-1.5 m-0 p-0 list-none">
						{tocItems.map((item) => (
							<li
								key={item.id}
								style={{ paddingLeft: `${(item.level - 1) * 0.875}rem` }}
								className="m-0 p-0"
							>
								<a
									href={`#${item.slug}`}
									className="text-sm text-neutral-600 dark:text-neutral-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors leading-snug no-underline"
								>
									{item.title}
								</a>
							</li>
						))}
					</ol>
				</nav>
			)}

			{/* ── Article Body ── */}
			<div className="w-full">
				<MarkdownToHtml contentMarkdown={post.content.markdown} />
			</div>

			{/* ── Tags ── */}
			{tags.length > 0 && (
				<div className="mt-12 pt-8 border-t border-neutral-100 dark:border-neutral-800">
					<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-3">
						Tags
					</p>
					<ul className="flex flex-wrap gap-2 list-none m-0 p-0">
						{tags.map((tag) => (
							<li key={tag.id} className="m-0 p-0">
								<Link
									href={`/tag/${tag.slug}`}
									className="inline-flex items-center px-3 py-1 bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400 rounded-full text-xs font-mono border border-neutral-200 dark:border-neutral-700 hover:bg-blue-50 hover:text-blue-700 hover:border-blue-200 dark:hover:bg-blue-950 dark:hover:text-blue-300 dark:hover:border-blue-800 transition-colors"
								>
									#{tag.slug}
								</Link>
							</li>
						))}
					</ul>
				</div>
			)}

			{/* ── Author Card ── */}
			<div className="mt-10 p-5 rounded-xl bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 flex items-center gap-4">
				{post.author.profilePicture && (
					<img
						src={resizeImage(post.author.profilePicture, { w: 120, h: 120, c: 'face' })}
						alt={post.author.name}
						className="w-14 h-14 rounded-full ring-2 ring-neutral-200 dark:ring-neutral-700 flex-shrink-0"
					/>
				)}
				<div>
					<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-0.5">
						Written by
					</p>
					<p className="font-semibold text-neutral-900 dark:text-neutral-100 text-sm">
						{post.author.name}
					</p>
					<p className="text-xs text-neutral-400 dark:text-neutral-500 mt-0.5 font-mono">
						@{post.author.username}
					</p>
				</div>
			</div>
		</>
	);
};

const Page = ({ page }: PageProps) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title}</title>
			</Head>
			<MarkdownToHtml contentMarkdown={page.content.markdown} />
		</>
	);
};

export default function PostOrPage(props: Props) {
	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;

	return (
		<AppProvider publication={publication} post={maybePost} page={maybePage} footerPosts={props.footerPosts}>
			<Layout>
				{props.type === 'post' && <ReadingProgressBar />}
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-6xl mx-auto w-full px-5 pt-10 pb-20">
						<article>
							{props.type === 'post' && <Post {...props} />}
							{props.type === 'page' && <Page {...props} />}
						</article>
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		const footerPosts = await getFooterPosts();
		return {
			props: {
				type: 'post',
				post: postData.publication.post,
				publication: postData.publication,
				footerPosts,
			},
			revalidate: 1,
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		const footerPosts = await getFooterPosts();
		return {
			props: {
				type: 'page',
				page: pageData.publication.staticPage,
				publication: pageData.publication,
				footerPosts,
			},
			revalidate: 1,
		};
	}

	return {
		notFound: true,
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => ({ params: { slug } })),
		fallback: 'blocking',
	};
}
