import { resizeImage } from '@starter-kit/utils/image';

const decodeHtml = (html: string): string =>
	html
		.replace(/&amp;/g, '&')
		.replace(/&lt;/g, '<')
		.replace(/&gt;/g, '>')
		.replace(/&quot;/g, '"')
		.replace(/&#39;/g, "'")
		.replace(/&apos;/g, "'");
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
import request from 'graphql-request';
import { motion, useReducedMotion } from 'framer-motion';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { CoverImage } from '../components/cover-image';
import { DateFormatter } from '../components/date-formatter';
import { ReadingLevelIndicator } from '../components/reading-level-indicator';
import { formatTagName } from '../utils/format';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
import { ProgressBadge } from '../components/progress-badge';
import {
	PageByPublicationDocument,
	PostFragment,
	PostFullFragment,
	PublicationFragment,
	SinglePostByPublicationDocument,
	SlugPostsByPublicationDocument,
	StaticPageFragment,
} from '../generated/graphql';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';
import { getFooterPosts } from '../lib/api/footerData';
import { SocialShare, MobileShareBar } from '../components/social-share';
import { TableOfContents } from '../components/table-of-contents';
import { PostChatbot } from '../components/post-chatbot';
import { PostQuiz } from '../components/post-quiz';
import { ScrollButtons } from '../components/scroll-buttons';
import { LearningPathNav } from '../components/learning-path-nav';
import { loadLearningPath } from '../components/learn-today';
import { CalloutBlock } from '../components/callout-block';
// CalloutBlock and QuizCard are available for use inside article content:
// import { CalloutBlock } from '../components/callout-block';
// import { QuizCard } from '../components/quiz-card';

// ─── Reading Progress Bar ─────────────────────────────────────────────────────
const ReadingProgressBar = () => {
	const [progress, setProgress] = useState(0);
	const reduceMotion = useReducedMotion();

	useEffect(() => {
		const onScroll = () => {
			const el = document.documentElement;
			const scrolled = el.scrollTop;
			const total = el.scrollHeight - el.clientHeight;
			setProgress(total > 0 ? Math.min(100, (scrolled / total) * 100) : 0);
		};
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	return (
		<div
			aria-hidden="true"
			className="fixed top-0 left-0 z-50 w-full h-0.5 bg-transparent pointer-events-none"
		>
			<motion.div
				className="h-full bg-blue-500 dark:bg-blue-400"
				animate={{ width: `${progress}%` }}
				transition={reduceMotion ? { duration: 0 } : { duration: 0.12, ease: 'linear' }}
			/>
		</div>
	);
};

type TocItem = {
	id: string;
	slug: string;
	title: string;
	level: number;
	parentId?: string | null;
};

const stripMarkdown = (markdown: string) =>
	markdown
		.replace(/```[\s\S]*?```/g, ' ')
		.replace(/`[^`]*`/g, ' ')
		.replace(/!\[[^\]]*\]\([^)]+\)/g, ' ')
		.replace(/\[[^\]]+\]\([^)]+\)/g, ' ')
		.replace(/[#>*_\-\n]/g, ' ')
		.replace(/\s+/g, ' ')
		.trim();

const normalizeCoverImageUrl = (raw?: string | null) => {
	if (!raw) return null;
	const withProtocol = raw.startsWith('//') ? `https:${raw}` : raw;
	return resizeImage(withProtocol, { w: 960, h: 540, c: 'thumb' });
};

const getAiSummaryBullets = (markdown: string, fallback: string) => {
	const plain = stripMarkdown(markdown);
	const sentences = plain
		.split(/(?<=[.!?])\s+/)
		.map((line) => line.trim())
		.filter((line) => line.length > 35)
		.slice(0, 4);
	return sentences.length > 0 ? sentences : [`This article explains ${fallback.toLowerCase()} in depth.`];
};

const GLOSSARY_TERMS: Record<string, string> = {
	cap: 'Consistency, Availability, and Partition tolerance tradeoff model.',
	quorum: 'Minimum number of distributed votes required for validity.',
	replication: 'Copying data across nodes to improve resilience and availability.',
	latency: 'Time delay between request and response completion.',
	rag: 'Retrieval-Augmented Generation: grounding LLM output in retrieved context.',
	embedding: 'Vector representation used for semantic similarity and retrieval.',
	transformer: 'Neural network architecture used by modern LLMs.',
	sharding: 'Splitting data across partitions to scale throughput and storage.',
	backpressure: 'Flow-control mechanism to prevent downstream overload.',
	idempotency: 'Safe repeated operation producing the same result.',
};

const detectGlossaryTerms = (markdown: string) => {
	const haystack = markdown.toLowerCase();
	return Object.entries(GLOSSARY_TERMS)
		.filter(([term]) => haystack.includes(term))
		.slice(0, 8);
};

const ReadingContextSidebar = ({
	tocItems,
	readTimeInMinutes,
	glossaryTerms,
	conceptDependencies,
}: {
	tocItems: TocItem[];
	readTimeInMinutes: number;
	glossaryTerms: Array<[string, string]>;
	conceptDependencies: Array<{ concept: string; dependsOn: string | null }>;
}) => {
	const [progress, setProgress] = useState(0);
	const reduceMotion = useReducedMotion();

	useEffect(() => {
		const onScroll = () => {
			const doc = document.documentElement;
			const total = doc.scrollHeight - doc.clientHeight;
			const next = total > 0 ? Math.min(100, (doc.scrollTop / total) * 100) : 0;
			setProgress(next);
		};
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	const checkpoints = [25, 50, 75, 100].map((mark) => ({
		mark,
		minutes: Math.max(1, Math.round((readTimeInMinutes * mark) / 100)),
	}));

	return (
		<aside className="hidden xl:block w-72 shrink-0">
			<div className="sticky top-20 space-y-4">
				<div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-3">
					<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
						Reading progress
					</p>
					<div className="h-2 rounded-full bg-neutral-100 dark:bg-neutral-800 overflow-hidden">
						<motion.div
							className="h-full bg-blue-500 dark:bg-blue-400"
							animate={{ width: `${progress}%` }}
							transition={reduceMotion ? { duration: 0 } : { duration: 0.2, ease: [0.2, 0, 0, 1] }}
						/>
					</div>
					<div className="mt-2 grid grid-cols-4 gap-1">
						{checkpoints.map((cp) => (
							<div
								key={cp.mark}
								className={`rounded-md px-1.5 py-1 text-[10px] text-center ${
									progress >= cp.mark
										? 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300'
										: 'bg-neutral-100 text-neutral-500 dark:bg-neutral-800 dark:text-neutral-400'
								}`}
							>
								{cp.minutes}m
							</div>
						))}
					</div>
				</div>

				<div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-3">
					<TableOfContents items={tocItems} variant="embedded" />
				</div>

				{glossaryTerms.length > 0 && (
					<div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-3">
						<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
							Inline glossary
						</p>
						<div className="space-y-2">
							{glossaryTerms.map(([term, description]) => (
								<div key={term} className="rounded-lg bg-neutral-50 dark:bg-neutral-800/60 p-2">
									<p className="text-xs font-semibold text-neutral-800 dark:text-neutral-100 capitalize">
										{term}
									</p>
									<p className="mt-0.5 text-[11px] text-neutral-500 dark:text-neutral-400">
										{description}
									</p>
								</div>
							))}
						</div>
					</div>
				)}

				{conceptDependencies.length > 0 && (
					<div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-3">
						<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
							Concept dependencies
						</p>
						<div className="space-y-2">
							{conceptDependencies.map((item) => (
								<div key={item.concept} className="text-xs text-neutral-600 dark:text-neutral-300">
									<span className="font-semibold">{item.concept}</span>
									<span className="text-neutral-400 dark:text-neutral-500">
										{' '}
										← {item.dependsOn ?? 'Foundations'}
									</span>
								</div>
							))}
						</div>
					</div>
				)}
			</div>
		</aside>
	);
};

const MobileChunkNavigator = ({ tocItems }: { tocItems: TocItem[] }) => {
	const [activeIdx, setActiveIdx] = useState(0);

	useEffect(() => {
		if (tocItems.length === 0) return;
		const headings = tocItems
			.map((item, index) => ({ index, el: document.getElementById(`heading-${item.slug}`) }))
			.filter((entry): entry is { index: number; el: HTMLElement } => Boolean(entry.el));

		if (headings.length === 0) return;

		const observer = new IntersectionObserver(
			(entries) => {
				const visible = entries
					.filter((entry) => entry.isIntersecting)
					.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
				if (visible[0]) {
					const match = headings.find((h) => h.el.id === visible[0].target.id);
					if (match) setActiveIdx(match.index);
				}
			},
			{ rootMargin: '0px 0px -70% 0px', threshold: 0 },
		);

		headings.forEach((heading) => observer.observe(heading.el));
		return () => observer.disconnect();
	}, [tocItems]);

	if (tocItems.length === 0) return null;

	const goTo = (index: number) => {
		const target = tocItems[index];
		if (!target) return;
		document.getElementById(`heading-${target.slug}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
	};

	return (
		<div className="xl:hidden fixed bottom-0 left-0 right-0 z-40 border-t border-neutral-200 dark:border-neutral-800 bg-white/95 dark:bg-neutral-950/95 backdrop-blur px-4 py-2">
			<div className="flex items-center gap-2">
				<button
					onClick={() => goTo(Math.max(0, activeIdx - 1))}
					disabled={activeIdx === 0}
					className="rounded-md border border-neutral-200 dark:border-neutral-700 px-2 py-1 text-xs text-neutral-600 dark:text-neutral-300 disabled:opacity-40"
				>
					Prev
				</button>
				<p className="flex-1 min-w-0 text-xs text-neutral-600 dark:text-neutral-300 line-clamp-1">
					{tocItems[activeIdx]?.title ?? 'Reading sections'}
				</p>
				<button
					onClick={() => goTo(Math.min(tocItems.length - 1, activeIdx + 1))}
					disabled={activeIdx >= tocItems.length - 1}
					className="rounded-md border border-neutral-200 dark:border-neutral-700 px-2 py-1 text-xs text-neutral-600 dark:text-neutral-300 disabled:opacity-40"
				>
					Next
				</button>
			</div>
		</div>
	);
};

type PostProps = {
	type: 'post';
	post: PostFullFragment;
	publication: PublicationFragment;
	footerPosts: PostFragment[];
	morePosts: PostFragment[];
};

type PageProps = {
	type: 'page';
	page: StaticPageFragment;
	publication: PublicationFragment;
	footerPosts: PostFragment[];
};

type Props = PostProps | PageProps;

const Post = ({ publication, post, morePosts }: PostProps) => {
	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';
	const [, setMobMount] = useState(false);
	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	// Detect if we're inside an interview-prep path (client-side only)
	const [activePath, setActivePath] = useState<{ source?: string; interviewLabel?: string; interviewIcon?: string } | null>(null);
	useEmbeds({ enabled: canLoadEmbeds });

	if (post.hasLatexInPost) {
		setTimeout(() => handleMathJax(true), 500);
	}

	useEffect(() => {
		if (screen.width <= 425) setMobMount(true);
		if (!post) return;
		(async () => {
			await loadIframeResizer();
			triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
		// Read active learning path for back-link context
		const lp = loadLearningPath();
		if (lp) setActivePath({ source: lp.source, interviewLabel: lp.interviewLabel, interviewIcon: lp.interviewIcon });
	}, []);

	const coverImageSrc = !!post.coverImage?.url
		? resizeImage(post.coverImage.url, { w: 1600, h: 840, c: 'thumb' })
		: undefined;

	const tocItems: TocItem[] =
		post.features?.tableOfContents?.isEnabled &&
		(post.features.tableOfContents.items ?? []).length > 0
			? (post.features.tableOfContents.items ?? []).map((item) => ({
					id: item.id,
					slug: item.slug,
					title: item.title,
					level: item.level ?? 1,
					parentId: item.parentId ?? null,
				}))
			: [];

	const tags = post.tags ?? [];
	const aiSummaryBullets = useMemo(
		() => getAiSummaryBullets(post.content.markdown, post.title),
		[post.content.markdown, post.title],
	);
	const glossaryTerms = useMemo(
		() => detectGlossaryTerms(post.content.markdown),
		[post.content.markdown],
	);
	const prerequisites = useMemo(() => {
		const pool = [
			'Distributed systems basics',
			'Networking and latency fundamentals',
			'Data modeling and storage concepts',
			'API and system design principles',
			'Core LLM concepts and prompting',
		];
		const byTag = tags.map((tag) => `${formatTagName(tag.name)} foundations`);
		return [...new Set([...byTag.slice(0, 3), ...pool.slice(0, Math.max(0, 3 - byTag.length))])];
	}, [tags]);
	const conceptDependencies = useMemo(
		() =>
			tags.slice(0, 6).map((tag, index) => ({
				concept: formatTagName(tag.name),
				dependsOn: index > 0 ? formatTagName(tags[index - 1].name) : null,
			})),
		[tags],
	);

	return (
		<>
			<Head>
				<title>{post.seo?.title || post.title}</title>
				<link rel="canonical" href={post.url} />
				<meta
					name="description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={post.seo?.title || post.title} />
				<meta
					property="twitter:description"
					content={post.seo?.description || post.subtitle || post.brief}
				/>
				<meta
					property="og:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<meta
					property="twitter:image"
					content={
						post.ogMetaData?.image ||
						post.coverImage?.url ||
						getAutogeneratedPostOG(post, publication)
					}
				/>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addArticleJsonLd(publication, post)),
					}}
				/>
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }} />
			</Head>

			{/* ── Back Navigation ── */}
			<Link
				href={activePath?.source === 'interview-prep' ? '/interview-prep' : '/'}
				className="inline-flex items-center gap-1.5 text-sm text-neutral-400 dark:text-neutral-500 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-4 md:mb-8 group"
			>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 20 20"
					fill="currentColor"
					className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform"
				>
					<path
						fillRule="evenodd"
						d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z"
						clipRule="evenodd"
					/>
				</svg>
				{activePath?.source === 'interview-prep'
					? `${activePath.interviewIcon ?? ''} ${activePath.interviewLabel ?? 'Interview Prep'} Path`.trim()
					: 'All Posts'}
			</Link>

			{/* ── Post Hero: header + cover image side-by-side ── */}
			<div className={`flex flex-col ${coverImageSrc ? 'md:flex-row md:items-center md:gap-10' : ''} mb-8 md:mb-12`}>
				{/* Left: title, subtitle, meta */}
				<div className={coverImageSrc ? 'flex-1 min-w-0' : 'w-full'}>
					<h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold leading-[1.15] tracking-tight text-neutral-900 dark:text-neutral-50 mb-3 md:mb-4">
						{post.title}
					</h1>

					{post.subtitle && (
						<p className="text-base md:text-xl text-neutral-500 dark:text-neutral-400 leading-relaxed mb-3 md:mb-4">
							{post.subtitle}
						</p>
					)}

					{/* Series badge */}
					{post.series && (
						<div className="mb-4">
							<Link
								href={`/series/${post.series.slug}`}
								className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/50 text-emerald-700 dark:text-emerald-300 text-xs font-semibold border border-emerald-200 dark:border-emerald-800 hover:bg-emerald-200 dark:hover:bg-emerald-800/60 transition-colors"
							>
								<svg className="w-3 h-3 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
									<path fillRule="evenodd" d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z" clipRule="evenodd" />
								</svg>
								{post.series.name}
							</Link>
						</div>
					)}

					{/* Meta row */}
					<div className="flex flex-wrap items-center gap-x-3 gap-y-2 pt-5 border-t border-neutral-100 dark:border-neutral-800">
						<div className="flex items-center gap-2">
							{post.author.profilePicture && (
								<img
									src={resizeImage(post.author.profilePicture, { w: 80, h: 80, c: 'face' })}
									alt={post.author.name}
									className="w-7 h-7 rounded-full ring-2 ring-neutral-100 dark:ring-neutral-800"
								/>
							)}
							<span className="text-sm font-semibold text-neutral-700 dark:text-neutral-300">
								{post.author.name}
							</span>
						</div>
						<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
						<time className="text-sm text-neutral-400 dark:text-neutral-500">
							<DateFormatter dateString={post.publishedAt} />
						</time>
						<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
						<span className="inline-flex items-center gap-1 text-sm text-neutral-400 dark:text-neutral-500">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								viewBox="0 0 20 20"
								fill="currentColor"
								className="w-3.5 h-3.5"
							>
								<path
									fillRule="evenodd"
									d="M10 18a8 8 0 100-16 8 8 0 000 16zm.75-13a.75.75 0 00-1.5 0v5c0 .414.336.75.75.75h4a.75.75 0 000-1.5h-3.25V5z"
									clipRule="evenodd"
								/>
							</svg>
							{post.readTimeInMinutes} min read
						</span>
						{post.reactionCount > 0 && (
							<>
								<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
								<span className="text-sm text-neutral-400 dark:text-neutral-500">
									♥ {post.reactionCount}
								</span>
							</>
						)}
					</div>

					{/* Progress Badge */}
					<div className="mt-4 flex items-center gap-2">
						<ProgressBadge postId={post.id} postTitle={post.title} />
					</div>
				</div>
				{!!coverImageSrc && (
					<div className="w-full md:w-2/5 shrink-0 mt-6 md:mt-0 h-40 sm:h-52 md:h-64 rounded-xl overflow-hidden ring-1 ring-neutral-200 dark:ring-neutral-800 shadow-sm">
						<img
							src={coverImageSrc}
							alt={`Cover Image for ${post.title}`}
							className="w-full h-full object-cover"/>
					</div>
				)}
			</div>

			{/* ── 3-Column Reading Layout ── */}
			<div className="flex gap-6 lg:gap-8 xl:gap-12 mt-6 md:mt-12 min-w-0 w-full">
				{/* Left: Social share (sticky, hidden below lg) */}
				<SocialShare url={post.url} title={post.title} excerpt={post.brief ?? ''} tags={(post.tags ?? []).map((t) => t.name)} />

				{/* Center: article content — responsive max-width based on ToC visibility */}
				<div className="flex-1 min-w-0 lg:max-w-3xl xl:max-w-4xl">
					{/* Reading Level Indicator */}
					<div className="mb-6">
						<ReadingLevelIndicator 
							tags={tags} 
							readTimeInMinutes={post.readTimeInMinutes}
							showDescription={true}
							variant="full"
						/>
					</div>
					{/* AI Disclaimer — compact on mobile, full on sm+ */}
					<div className="mb-6 flex gap-2.5 rounded-xl border border-amber-200 bg-amber-50 px-3.5 py-2.5 dark:border-amber-800/60 dark:bg-amber-950/40">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							viewBox="0 0 20 20"
							fill="currentColor"
							className="mt-0.5 h-3.5 w-3.5 flex-shrink-0 text-amber-500 dark:text-amber-400"
							aria-hidden="true"
						>
							<path
								fillRule="evenodd"
								d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z"
								clipRule="evenodd"
							/>
						</svg>
						<p className="text-xs leading-relaxed text-amber-800 dark:text-amber-300">
							<span className="font-semibold">AI-assisted content.</span>
							<span className="hidden sm:inline"> This post may have been written or enhanced with AI tools. Please verify critical information independently.</span>
						</p>
					</div>

					{/* AI-generated summary + prerequisite architecture blocks */}
					<section className="mb-8 space-y-4">
						<div className="rounded-xl border border-blue-200 dark:border-blue-800 bg-blue-50/70 dark:bg-blue-950/30 p-4">
							<p className="text-[10px] font-mono uppercase tracking-widest text-blue-600 dark:text-blue-400 mb-2">
								AI-generated summary
							</p>
							<ul className="m-0 list-disc pl-5 space-y-1 text-sm text-neutral-700 dark:text-neutral-300">
								{aiSummaryBullets.map((bullet) => (
									<li key={bullet}>{bullet}</li>
								))}
							</ul>
						</div>

						<div className="rounded-xl border border-purple-200 dark:border-purple-800 bg-purple-50/70 dark:bg-purple-950/30 p-4">
							<p className="text-[10px] font-mono uppercase tracking-widest text-purple-600 dark:text-purple-400 mb-2">
								Prerequisites required
							</p>
							<div className="flex flex-wrap gap-2">
								{prerequisites.map((item) => (
									<span
										key={item}
										className="inline-flex items-center rounded-full border border-purple-200 dark:border-purple-800 px-3 py-1 text-xs text-purple-700 dark:text-purple-300"
									>
										{item}
									</span>
								))}
							</div>
						</div>

						<CalloutBlock variant="deep-dive" title="Architecture callout">
							This section highlights system boundaries, failure modes, and scaling constraints that matter in real production environments.
						</CalloutBlock>

						<div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
								Tradeoff comparison
							</p>
							<div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
								<div className="rounded-lg border border-emerald-200 dark:border-emerald-800 bg-emerald-50/70 dark:bg-emerald-950/30 p-3">
									<p className="font-semibold text-emerald-700 dark:text-emerald-300">Option A: Latency-first</p>
									<p className="mt-1 text-neutral-600 dark:text-neutral-300">Optimizes response time and user interaction loops, with higher implementation complexity.</p>
								</div>
								<div className="rounded-lg border border-amber-200 dark:border-amber-800 bg-amber-50/70 dark:bg-amber-950/30 p-3">
									<p className="font-semibold text-amber-700 dark:text-amber-300">Option B: Consistency-first</p>
									<p className="mt-1 text-neutral-600 dark:text-neutral-300">Prioritizes determinism and simpler operations, with increased latency under load.</p>
								</div>
							</div>
						</div>
					</section>

					{/* Article body — article-doc activates docs-article.css scoped styles (h2 borders, p max-width); overflow-x handled by outer container */}
					<div className="article-doc w-full min-w-0">
						<MarkdownToHtml contentMarkdown={post.content.markdown} />
					</div>

					{/* Expandable deep dives */}
					{tocItems.length > 0 && (
						<section className="mt-8 space-y-3">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
								Expandable deep dives
							</p>
							{tocItems.slice(0, 4).map((item) => (
								<details
									key={item.id}
									className="group rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4"
								>
									<summary className="cursor-pointer list-none text-sm font-semibold text-neutral-800 dark:text-neutral-100 flex items-center justify-between">
										<span>{item.title}</span>
										<span className="text-xs text-neutral-400 group-open:rotate-180 transition-transform">⌄</span>
									</summary>
									<p className="mt-2 text-sm text-neutral-600 dark:text-neutral-300">
										Dive deeper into this section and cross-reference concepts before moving to the next heading.
										<Link href={`#heading-${item.slug}`} className="ml-1 text-blue-600 dark:text-blue-400">
											Jump to section
										</Link>
									</p>
								</details>
							))}
						</section>
					)}

					{/* Share — mobile/tablet (desktop uses sticky sidebar) */}
					<MobileShareBar url={post.url} title={post.title} excerpt={post.brief ?? ''} tags={(post.tags ?? []).map((t) => t.name)} />

					{/* Dynamic Quiz */}
					<PostQuiz postTitle={post.title} postContent={post.content.markdown} />

					{/* Tags */}
					{tags.length > 0 && (
						<div className="mt-12 pt-8 border-t border-neutral-100 dark:border-neutral-800">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-3">
								Tags
							</p>
							<ul className="flex flex-wrap gap-2 list-none m-0 p-0">
								{tags.map((tag) => (
									<li key={tag.id} className="m-0 p-0">
										<Link
											href={`/tag/${tag.slug}`}
											className="inline-flex items-center px-3 py-1 bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400 rounded-full text-xs font-mono border border-neutral-200 dark:border-neutral-700 hover:bg-blue-50 hover:text-blue-700 hover:border-blue-200 dark:hover:bg-blue-950 dark:hover:text-blue-300 dark:hover:border-blue-800 transition-colors"
										>
											{formatTagName(tag.name)}
										</Link>
									</li>
								))}
							</ul>
						</div>
					)}

					{/* Author Card */}
					<div className="mt-10 p-5 rounded-xl bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 flex items-center gap-4">
						{post.author.profilePicture && (
							<img
								src={resizeImage(post.author.profilePicture, { w: 120, h: 120, c: 'face' })}
								alt={post.author.name}
								className="w-14 h-14 rounded-full ring-2 ring-neutral-200 dark:ring-neutral-700 flex-shrink-0"
							/>
						)}
						<div className="min-w-0 flex-1">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-0.5">
								Written by
							</p>
							<p className="font-semibold text-neutral-900 dark:text-neutral-100 text-sm">
								{post.author.name}
							</p>
							<p className="text-xs text-neutral-400 dark:text-neutral-500 mt-0.5 font-mono">
								@{post.author.username}
							</p>
						</div>
					</div>

					{/* What to learn next */}
					<section className="mt-10 rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5">
						<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-3">
							What to learn next
						</p>
						<div className="grid grid-cols-1 md:grid-cols-2 gap-3">
							{(morePosts.length > 0 ? morePosts.slice(0, 4) : []).map((nextPost) => {
								const nextCoverImage = normalizeCoverImageUrl(nextPost.coverImage?.url);
								return (
									<Link
										key={nextPost.id}
										href={`/${nextPost.slug}`}
										className="rounded-lg border border-neutral-200 dark:border-neutral-700 p-3 hover:border-blue-300 dark:hover:border-blue-500 transition-colors"
									>
										{nextCoverImage ? (
											<img
												src={nextCoverImage}
												alt={nextPost.title}
												className="mb-2 h-24 w-full rounded-md object-cover"
											/>
										) : (
											<div className="mb-2 h-24 w-full rounded-md bg-gradient-to-br from-blue-100 via-indigo-100 to-teal-100 dark:from-blue-950/40 dark:via-indigo-950/30 dark:to-teal-950/30" />
										)}
										<p className="text-sm font-semibold text-neutral-900 dark:text-neutral-100 line-clamp-2">
											{nextPost.title}
										</p>
										<p className="mt-1 text-xs text-neutral-500 dark:text-neutral-400">
											{nextPost.readTimeInMinutes} min read
										</p>
									</Link>
								);
							})}
						</div>
					</section>

				</div>

				{/* Right: reading context sidebar (xl+) */}
				<ReadingContextSidebar
					tocItems={tocItems}
					readTimeInMinutes={post.readTimeInMinutes}
					glossaryTerms={glossaryTerms}
					conceptDependencies={conceptDependencies}
				/>
			</div>

			{/* Floating AI Chatbot */}
			<PostChatbot postTitle={post.title} postContent={post.content.markdown} />
			<ScrollButtons />
			<LearningPathNav slug={post.slug} />
			<MobileChunkNavigator tocItems={tocItems} />
		</>
	);
};

const Page = ({ page }: PageProps) => {
	const title = page.title;
	return (
		<>
			<Head>
				<title>{title}</title>
			</Head>
			<MarkdownToHtml contentMarkdown={page.content.markdown} />
		</>
	);
};

export default function PostOrPage(props: Props) {
	const maybePost = props.type === 'post' ? props.post : null;
	const maybePage = props.type === 'page' ? props.page : null;
	const publication = props.publication;

	return (
		<AppProvider publication={publication} post={maybePost} page={maybePage} footerPosts={props.footerPosts}>
			<Layout>
				{props.type === 'post' && <ReadingProgressBar />}
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-7xl mx-auto w-full px-4 sm:px-5 pt-10 pb-28 md:pb-20 overflow-x-hidden">
						<article className="w-full min-w-0">
							{props.type === 'post' && <Post {...props} />}
							{props.type === 'page' && <Page {...props} />}
						</article>
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) {
		throw new Error('No params');
	}

	const endpoint = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
	const host = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST;
	const slug = params.slug;

	const postData = await request(endpoint, SinglePostByPublicationDocument, { host, slug });

	if (postData.publication?.post) {
		const footerPosts = await getFooterPosts();
		const currentPost = postData.publication.post;

		// ── Compute related posts from footerPosts by tag overlap + title similarity ──
		const currentTagSlugs = new Set((currentPost.tags ?? []).map((t) => t.slug));
		const currentKeywords = currentPost.title
			.toLowerCase()
			.replace(/[^\w\s]/g, ' ')
			.split(/\s+/)
			.filter((w) => w.length > 3);

		const scored = footerPosts
			.filter((p) => p.slug !== slug)
			.map((p) => {
				const tagScore = (p.tags ?? []).filter((t) => currentTagSlugs.has(t.slug)).length * 10;
				const titleWords = p.title.toLowerCase();
				const briefWords = (p.brief ?? '').toLowerCase();
				const kwScore = currentKeywords.reduce((s, w) => {
					return s + (titleWords.includes(w) ? 3 : 0) + (briefWords.includes(w) ? 1 : 0);
				}, 0);
				return { post: p, score: tagScore + kwScore };
			})
			.filter(({ score }) => score > 0)
			.sort((a, b) => b.score - a.score);

		// Require at least a tag match (>=10) or strong keyword overlap (>=6)
		const threshold = scored[0]?.score >= 10 ? 10 : 6;
		const morePosts = scored
			.filter(({ score }) => score >= threshold)
			.slice(0, 4)
			.map(({ post }) => post);

		return {
			props: {
				type: 'post',
				post: currentPost,
				publication: postData.publication,
				footerPosts,
				morePosts,
			},
			revalidate: 1,
		};
	}

	const pageData = await request(endpoint, PageByPublicationDocument, { host, slug });

	if (pageData.publication?.staticPage) {
		const footerPosts = await getFooterPosts();
		return {
			props: {
				type: 'page',
				page: pageData.publication.staticPage,
				publication: pageData.publication,
				footerPosts,
			},
			revalidate: 1,
		};
	}

	return {
		notFound: true,
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	const data = await request(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SlugPostsByPublicationDocument,
		{
			first: 10,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const postSlugs = (data.publication?.posts.edges ?? []).map((edge) => edge.node.slug);

	return {
		paths: postSlugs.map((slug) => ({ params: { slug } })),
		fallback: 'blocking',
	};
}
