import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { PersonalHeader } from '../components/personal-theme-header';
import { SystemsKnowledgeGraph } from '../components/systems-knowledge-graph';
import { useLearningContext } from '../components/learning-context-provider';
import { buildTopicCollectionSummaries, type TopicCollectionSummary } from '../lib/topic-learning';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	posts: PostFragment[];
	topicCollections: TopicCollectionSummary[];
};

export default function DiscoverPage({ publication, posts, topicCollections }: Props) {
	const { setContext } = useLearningContext();
	const router = useRouter();

	useEffect(() => {
		router.replace('/learn');
		setContext({
			source: 'discover',
			pathname: '/learn',
			title: 'Discovery',
			domain: 'Engineering',
			topic: 'Systems concepts',
			roadmapHref: '/learn',
			simulationTopic: 'systems relationships',
		});
	}, [router, setContext]);

	return (
		<AppProvider publication={publication} footerPosts={posts}>
			<Layout>
				<Head>
					<title>Discovery - {publication.title}</title>
					<meta
						name="description"
						content={`Discover ${publication.title} through chapter-backed systems concepts, architecture themes, and related engineering ideas.`}
					/>
					<meta property="og:title" content={`Discovery - ${publication.title}`} />
					<meta
						property="og:description"
						content="Move through related systems ideas without leaving the editorial reading experience."
					/>
					<meta property="og:image" content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)} />
					<meta property="twitter:card" content="summary_large_image" />
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>

				<Container className="mx-auto w-full">
					<PersonalHeader />
					<main className="mx-auto w-full max-w-[1440px] px-5 pb-20 pt-10 md:px-8">
						<Link
							href="/"
							className="mb-10 inline-flex items-center gap-1.5 text-sm text-neutral-400 transition-colors hover:text-blue-600 dark:text-neutral-500 dark:hover:text-blue-400"
						>
							Back home
						</Link>
						<div className="mb-8">
							<p className="mb-2 text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
								Discovery
							</p>
							<h1 className="text-4xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50 md:text-5xl">
								Related systems and concepts
							</h1>
							<p className="mt-3 max-w-3xl text-lg leading-relaxed text-neutral-500 dark:text-neutral-400">
								Move from one durable engineering idea to the next through chapter-backed collections, architecture themes, and a small relationship view when it helps.
							</p>
						</div>

						<section id="topic-collections" className="mt-12 scroll-mt-24">
							<div className="mb-5 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
								<div>
									<p className="mb-2 text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
										Topic collections
									</p>
									<h2 className="text-3xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50">
										Choose a connected concept area
									</h2>
								</div>
								<Link
									href="/posts"
									className="text-sm font-bold text-blue-600 transition hover:text-blue-700 dark:text-blue-300 dark:hover:text-blue-200"
								>
									Browse chapters
								</Link>
							</div>
							<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
								{topicCollections.map((topic) => (
									<Link
										key={topic.slug}
										href={`/topic/${topic.slug}`}
										className="group flex min-w-0 flex-col rounded-2xl border border-neutral-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-sm dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-blue-700"
									>
										<div className="flex items-start justify-between gap-3">
											<h3 className="min-w-0 text-lg font-black leading-6 text-neutral-950 group-hover:text-blue-700 dark:text-neutral-50 dark:group-hover:text-blue-300">
												{topic.label}
											</h3>
											<span className="shrink-0 rounded-full bg-neutral-100 px-2 py-1 text-[10px] font-black uppercase text-neutral-500 dark:bg-neutral-800 dark:text-neutral-300">
												{topic.articleCount} reads
											</span>
										</div>
										<p className="mt-2 line-clamp-3 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
											{topic.description}
										</p>
										<div className="mt-4 flex flex-wrap gap-2">
											{topic.concepts.map((concept) => (
												<span
													key={concept}
													className="max-w-full truncate rounded-full border border-neutral-200 px-2.5 py-1 text-[11px] font-semibold text-neutral-600 dark:border-neutral-800 dark:text-neutral-300"
												>
													{concept}
												</span>
											))}
										</div>
										{topic.featuredArticle ? (
											<p className="mt-4 border-t border-neutral-100 pt-3 text-xs font-semibold leading-5 text-neutral-500 dark:border-neutral-800 dark:text-neutral-400">
												Start with {topic.featuredArticle.primaryConcept}
											</p>
										) : null}
									</Link>
								))}
							</div>
						</section>

						<section className="mt-12">
							<div className="mb-5">
								<p className="mb-2 text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
									Related systems
								</p>
								<h2 className="text-3xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50">
									A light relationship map
								</h2>
								<p className="mt-2 max-w-3xl text-sm leading-relaxed text-neutral-500 dark:text-neutral-400">
									Use this only as a quick orientation layer. The chapters remain the source of depth.
								</p>
							</div>
							<SystemsKnowledgeGraph posts={posts} initialConcept="replication" compact />
						</section>
					</main>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		const first = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST },
		);

		const publication = first.publication;
		if (!publication) return { notFound: true };

		const posts: PostFragment[] = [...publication.posts.edges.map((edge) => edge.node)];
		let cursor = publication.posts.pageInfo?.endCursor;
		let hasNextPage = !!publication.posts.pageInfo?.hasNextPage;

		while (hasNextPage && cursor) {
			const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
				GQL_ENDPOINT,
				MorePostsByPublicationDocument,
				{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
			);
			if (!next.publication) break;
			posts.push(...next.publication.posts.edges.map((edge) => edge.node));
			cursor = next.publication.posts.pageInfo.endCursor;
			hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
		}

		return {
			props: { publication, posts, topicCollections: buildTopicCollectionSummaries(posts, 6) },
			revalidate: 3600,
		};
	} catch (err) {
		console.error('[discover] getStaticProps error:', err);
		return { notFound: true };
	}
};
