import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { DiscoverFilters } from '../components/discover-filters';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PostFragment,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	posts: PostFragment[];
};

export default function DiscoverPage({ publication, posts }: Props) {
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>Discover - {publication.title}</title>
					<meta
						name="description"
						content={`Discover all articles on ${publication.title}. Explore by categories, tags, and topics.`}
					/>
					<meta property="og:title" content={`Discover - ${publication.title}`} />
					<meta
						property="og:description"
						content={`Discover all articles on ${publication.title}. Explore by categories, tags, and topics.`}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={`Discover - ${publication.title}`} />
					<meta
						property="twitter:description"
						content={`Discover all articles on ${publication.title}. Explore by categories, tags, and topics.`}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Container className="mx-auto w-full px-5 py-10">
					<div className="max-w-6xl mx-auto w-full flex flex-col gap-0">
						<PersonalHeader />
						<section className="w-full py-12">
							<div className="mb-12">
								<h1 className="text-4xl md:text-5xl font-bold text-neutral-900 dark:text-neutral-50 mb-4">
									Discover
								</h1>
								<p className="text-lg text-neutral-600 dark:text-neutral-300">
									Explore our knowledge base organized by topics, categories, and complexity levels. Find
									exactly what you're looking for.
								</p>
							</div>
							<DiscoverFilters posts={posts} />
						</section>
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 100, // Get all posts for the discover page
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const posts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			posts,
		},
		revalidate: 1,
	};
};
