import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MarkdownToHtml } from '../components/markdown-to-html';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	PublicationByHostDocument,
	PublicationByHostQuery,
	PublicationByHostQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import type { GeneratedPost } from './api/generate-post';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
};

type Status = 'idle' | 'loading' | 'done' | 'error';

// ── Skeleton ─────────────────────────────────────────────────────────────────

function Skeleton({ topic }: { topic: string }) {
	return (
		<div className="animate-pulse space-y-8">
			<div className="space-y-3">
				<div className="h-8 w-3/4 rounded-lg bg-neutral-200 dark:bg-neutral-800" />
				<div className="h-5 w-1/2 rounded bg-neutral-100 dark:bg-neutral-800/60" />
			</div>
			<div className="flex gap-2">
				{[20, 24, 16].map((w) => (
					<div key={w} className={`h-6 rounded-full bg-neutral-100 dark:bg-neutral-800/60 w-${w}`} />
				))}
			</div>
			<div className="space-y-2.5">
				{[100, 95, 88, 100, 72, 90, 85, 100, 60, 95, 78, 100, 50].map((pct, i) => (
					<div
						key={i}
						className="h-4 rounded bg-neutral-100 dark:bg-neutral-800/60"
						style={{ width: `${pct}%` }}
					/>
				))}
			</div>
			<p className="text-center text-sm text-neutral-400 dark:text-neutral-500 pt-2">
				Generating article about{' '}
				<strong className="text-neutral-600 dark:text-neutral-300">&ldquo;{topic}&rdquo;</strong>…
			</p>
		</div>
	);
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function GeneratedPostPage({ publication }: Props) {
	const router = useRouter();
	const isReady = router.isReady;
	const topic = isReady && typeof router.query.topic === 'string' ? router.query.topic.trim() : '';

	const [status, setStatus] = useState<Status>('idle');
	const [post, setPost] = useState<GeneratedPost | null>(null);
	const [errorMsg, setErrorMsg] = useState('');
	const [retryKey, setRetryKey] = useState(0);

	useEffect(() => {
		if (!isReady || !topic) return;

		let cancelled = false;
		setStatus('loading');
		setPost(null);
		setErrorMsg('');

		fetch('/api/generate-post', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ topic }),
		})
			.then((r) => r.json())
			.then((data) => {
				if (cancelled) return;
				if ('error' in data) {
					setErrorMsg(data.error as string);
					setStatus('error');
				} else {
					setPost(data as GeneratedPost);
					setStatus('done');
				}
			})
			.catch((err: Error) => {
				if (cancelled) return;
				setErrorMsg(err.message ?? 'Unknown error');
				setStatus('error');
			});

		return () => { cancelled = true; };
	}, [topic, retryKey, isReady]);

	const pageTitle = post
		? `${post.title} · AI-Generated — ${publication.title}`
		: topic
		? `Generating: ${topic} — ${publication.title}`
		: `AI Article Generator — ${publication.title}`;

	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{pageTitle}</title>
					{/* Never index AI-generated content */}
					<meta name="robots" content="noindex, nofollow" />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>

				<Container>
					<PersonalHeader />

					<div className="max-w-3xl mx-auto w-full px-5 pt-10 pb-20">

						{/* ── Back link ───────────────────────────────────────── */}
						<Link
							href={topic ? `/posts?search=${encodeURIComponent(topic)}` : '/posts'}
							className="inline-flex items-center gap-1.5 text-sm text-neutral-500 dark:text-neutral-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-8 group"
						>
							<svg
								className="w-3.5 h-3.5 group-hover:-translate-x-0.5 transition-transform"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
							>
								<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
							</svg>
							Back to Posts
						</Link>

						{/* ── AI disclaimer banner ─────────────────────────── */}
						<div className="mb-8 flex gap-3 rounded-xl border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/40 px-5 py-4">
							<span className="shrink-0 text-lg">🤖</span>
							<div>
								<p className="mb-0.5 text-sm font-semibold text-amber-800 dark:text-amber-300">
									AI-Generated Article — Not a real blog post
								</p>
								<p className="text-xs leading-relaxed text-amber-700 dark:text-amber-400">
									This article was created on-the-fly because no existing post matched your query.
									It is not published on this blog and may contain inaccuracies.
									Always verify technical information from primary sources.
								</p>
							</div>
						</div>

						{/* ── Idle / no topic ──────────────────────────────── */}
						{status === 'idle' && !topic && (
							<div className="py-16 text-center">
								<p className="text-neutral-500 dark:text-neutral-400">
									No topic specified.{' '}
									<Link href="/posts" className="text-blue-600 dark:text-blue-400 hover:underline">
										Browse posts
									</Link>{' '}
									or search for something.
								</p>
							</div>
						)}

						{/* ── Loading skeleton ─────────────────────────────── */}
						{status === 'loading' && <Skeleton topic={topic} />}

						{/* ── Error ────────────────────────────────────────── */}
						{status === 'error' && (
							<div className="rounded-xl border border-red-200 dark:border-red-900 bg-red-50 dark:bg-red-950/40 px-5 py-6 text-center">
								<p className="mb-1 text-sm font-semibold text-red-700 dark:text-red-400">
									Generation failed
								</p>
								<p className="mb-4 text-xs text-red-600 dark:text-red-500">{errorMsg}</p>
								<button
									onClick={() => setRetryKey((k) => k + 1)}
									className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-red-700"
								>
									<svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
									</svg>
									Try again
								</button>
							</div>
						)}

						{/* ── Generated article ────────────────────────────── */}
						{status === 'done' && post && (
							<article>
								{/* Header */}
								<header className="mb-8">
									<h1 className="mb-3 text-3xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50 md:text-4xl leading-tight">
										{post.title}
									</h1>
									{post.summary && (
										<p className="mb-4 text-base leading-relaxed text-neutral-500 dark:text-neutral-400">
											{post.summary}
										</p>
									)}
									<div className="flex flex-wrap items-center gap-2 text-xs text-neutral-400 dark:text-neutral-500">
										<span className="font-mono tabular-nums">{post.readTimeMinutes} min read</span>
										{post.tags.length > 0 && <span>·</span>}
										{post.tags.map((tag) => (
											<span
												key={tag}
												className="rounded-full bg-neutral-100 dark:bg-neutral-800 px-2 py-0.5 text-neutral-600 dark:text-neutral-400"
											>
												{tag}
											</span>
										))}
									</div>
								</header>

								{/* Divider */}
								<div className="mb-8 h-px bg-neutral-100 dark:bg-neutral-800" />

								{/* Content */}
								<MarkdownToHtml contentMarkdown={post.markdown} />

								{/* Footer CTA */}
								<div className="mt-12 rounded-xl border border-neutral-100 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900/50 px-6 py-6 text-center">
									<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
										Explore real content
									</p>
									<p className="mb-4 text-sm text-neutral-600 dark:text-neutral-400">
										Liked this topic? Find published posts about it on this blog.
									</p>
									<div className="flex flex-wrap justify-center gap-3">
										<Link
											href={`/posts?search=${encodeURIComponent(topic)}`}
											className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
										>
											Browse posts about &ldquo;{topic}&rdquo;
										</Link>
										<Link
											href="/guided-topics"
											className="inline-flex items-center gap-2 rounded-lg border border-neutral-200 dark:border-neutral-700 px-5 py-2.5 text-sm font-semibold text-neutral-700 dark:text-neutral-300 transition-colors hover:border-blue-400 hover:text-blue-600 dark:hover:text-blue-400"
										>
											Explore guided topics
										</Link>
									</div>
								</div>
							</article>
						)}
					</div>

					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		const data = await request<PublicationByHostQuery, PublicationByHostQueryVariables>(
			GQL_ENDPOINT,
			PublicationByHostDocument,
			{ host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST },
		);

		const publication = data.publication;
		if (!publication) {
			return { notFound: true };
		}

		return {
			props: { publication },
			revalidate: 3600,
		};
	} catch (e) {
		console.warn('[generated] Hashnode API unavailable:', (e as Error).message);
		return { notFound: true, revalidate: 60 };
	}
};
