import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { LearningPaths } from '../components/learning-paths';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	postCounts: Record<string, number>;
	footerPosts: PostFragment[];
};

export default function LearningPathsPage({ publication, postCounts, footerPosts }: Props) {
	return (
		<AppProvider publication={publication} footerPosts={footerPosts}>
			<Layout>
				<Head>
					<title>Guided Topics — {publication.title}</title>
					<meta
						name="description"
						content={`Guided topics on ${publication.title} — curated series and topic roadmaps to guide you from beginner to advanced.`}
					/>
					<meta property="og:title" content={`Guided Topics — ${publication.title}`} />
					<meta
						property="og:description"
						content={`Guided topics on ${publication.title} — curated series and topic roadmaps.`}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>

				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-6xl mx-auto w-full px-5 pt-10 pb-20">

						{/* Back nav */}
						<Link
							href="/"
							className="inline-flex items-center gap-1.5 text-sm text-neutral-400 dark:text-neutral-500 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-10 group"
						>
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
								className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform">
								<path fillRule="evenodd" d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z" clipRule="evenodd" />
							</svg>
							Home
						</Link>

						{/* Page header */}
						<div className="mb-12">
							<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500 mb-2">
								Curated Roadmaps
							</p>
							<h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-neutral-900 dark:text-neutral-50 mb-3">
								Guided Topics
							</h1>
							<p className="text-lg text-neutral-500 dark:text-neutral-400 max-w-2xl">
								Choose a path and follow it from start to finish — each post builds on the previous so you develop real, lasting understanding.
							</p>
						</div>

						{/* ── Topic-based paths ────────────────────────────────────── */}
						<LearningPaths postCounts={postCounts} />

					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		// ── Fetch all posts ───────────────────────────────────────────────────
		const first = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST },
		);

		const publication = first.publication;
		if (!publication) return { notFound: true };

		const allPosts: PostFragment[] = [...(first.publication?.posts.edges ?? []).map((e) => e.node)];
		let cursor = first.publication?.posts.pageInfo?.endCursor;
		let hasNextPage = !!first.publication?.posts.pageInfo?.hasNextPage;

		while (hasNextPage && cursor) {
			const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
				GQL_ENDPOINT,
				MorePostsByPublicationDocument,
				{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
			);
			if (!next.publication) break;
			allPosts.push(...next.publication.posts.edges.map((e) => e.node));
			cursor = next.publication.posts.pageInfo.endCursor;
			hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
		}

		// ── Post counts per tag slug (for LearningPaths component) ────────────
		const tagCountMap: Record<string, number> = {};
		for (const post of allPosts) {
			for (const tag of post.tags ?? []) {
				tagCountMap[tag.slug] = (tagCountMap[tag.slug] ?? 0) + 1;
			}
		}

		return {
			props: {
				publication,
				postCounts: tagCountMap,
				footerPosts: allPosts,
			},
			revalidate: 3600,
		};
	} catch (err) {
		console.error('[guided-topics] getStaticProps error:', err);
		return { notFound: true };
	}
};
