import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { motion, useReducedMotion } from 'framer-motion';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { AppProvider } from '../components/contexts/appContext';
import { Container } from '../components/container';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { loadLearningPath } from '../components/learn-today';
import { EmbeddedAIMentor } from '../components/embedded-ai-mentor';
import { useLearningContext } from '../components/learning-context-provider';
import { InlineSimulation } from '../components/visualization/inline-simulation';
import { PersonalHeader } from '../components/personal-theme-header';
import { useFeatureConfig } from '../components/contexts/featureConfigContext';
import { useLearningMemoryStore } from '../lib/learning-memory';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
const PREP_STATE_KEY = 'aa:interview-prep-state';
const BOOKMARKS_KEY = 'aa:interview-bookmarks';
const SIDEBAR_COLLAPSED_KEY = 'aa:interview-sidebar-collapsed';

type LeanPost = {
	id: string;
	title: string;
	slug: string;
	brief: string;
	readTimeInMinutes: number;
	views: number;
	publishedAt: string;
	tags: { id: string; name: string; slug: string }[];
	series: { name: string; slug: string } | null;
};

type Props = {
	publication: PublicationFragment;
	posts: LeanPost[];
	footerPosts: PostFragment[];
};

type PrepState = {
	completedSlugs: string[];
	mockInterviews: number;
	communicationScore: number;
	targetCompanies: string[];
	preferredDomain: string;
	difficulty: 'Foundational' | 'Intermediate' | 'Advanced';
};

type PrepCategory = {
	id: string;
	label: string;
	description: string;
	query: string[];
	difficulty: string;
	accent: string;
};

type SidebarItem = {
	id: string;
	label: string;
	href: string;
	group?: string;
};

const DEFAULT_PREP_STATE: PrepState = {
	completedSlugs: [],
	mockInterviews: 0,
	communicationScore: 62,
	targetCompanies: ['FAANG', 'Startup'],
	preferredDomain: 'System Design',
	difficulty: 'Intermediate',
};

const SIDEBAR_ITEMS: SidebarItem[] = [
	{ id: 'dashboard', label: 'Overview', href: '#dashboard', group: 'Practice' },
	{ id: 'question-bank', label: 'Question Bank', href: '#question-bank', group: 'Practice' },
	{ id: 'mock-interviews', label: 'Mock Interviews', href: '#mock-interviews', group: 'Practice' },
	{ id: 'system-design', label: 'System Design', href: '#whiteboard', group: 'Practice' },
	{ id: 'coding-challenges', label: 'Coding Challenges', href: '#question-bank', group: 'Practice' },
	{ id: 'behavioral', label: 'Behavioral', href: '#question-bank', group: 'Practice' },
	{ id: 'company-rounds', label: 'Company Rounds', href: '#recommendations', group: 'Personalized' },
	{ id: 'saved-answers', label: 'Saved Answers', href: '#activity', group: 'Personalized' },
	{ id: 'bookmarks', label: 'Bookmarks', href: '#activity', group: 'Personalized' },
	{ id: 'my-progress', label: 'My Progress', href: '#readiness', group: 'Personalized' },
];

const PREP_CATEGORIES: PrepCategory[] = [
	{
		id: 'system-design',
		label: 'System Design',
		description: 'Architecture, scale, APIs, tradeoffs',
		query: ['system', 'design', 'architecture', 'scale', 'scalability'],
		difficulty: 'Intermediate to Advanced',
		accent: 'from-violet-500 to-blue-500',
	},
	{
		id: 'coding',
		label: 'Coding & Algorithms',
		description: 'Data structures, complexity, implementation',
		query: ['algorithm', 'coding', 'python', 'data structure', 'complexity'],
		difficulty: 'Foundational to Advanced',
		accent: 'from-blue-500 to-cyan-500',
	},
	{
		id: 'distributed',
		label: 'Distributed Systems',
		description: 'Consensus, replication, queues, failure modes',
		query: ['distributed', 'kafka', 'consensus', 'raft', 'replication'],
		difficulty: 'Advanced',
		accent: 'from-violet-500 to-fuchsia-500',
	},
	{
		id: 'databases',
		label: 'Databases',
		description: 'Indexes, transactions, storage, sharding',
		query: ['database', 'db', 'sql', 'transaction', 'storage', 'shard'],
		difficulty: 'Intermediate',
		accent: 'from-sky-500 to-blue-500',
	},
	{
		id: 'networking',
		label: 'Networking',
		description: 'Protocols, latency, load balancing, reliability',
		query: ['network', 'http', 'latency', 'load balancer', 'tcp'],
		difficulty: 'Intermediate',
		accent: 'from-cyan-500 to-teal-500',
	},
	{
		id: 'behavioral',
		label: 'Behavioral',
		description: 'Leadership, conflict, ambiguity, storytelling',
		query: ['leadership', 'staff', 'career', 'team', 'conflict'],
		difficulty: 'Role dependent',
		accent: 'from-rose-500 to-violet-500',
	},
	{
		id: 'ai-ml',
		label: 'AI/ML Systems',
		description: 'RAG, evaluation, serving, model tradeoffs',
		query: ['ai', 'ml', 'llm', 'rag', 'embedding', 'model'],
		difficulty: 'Intermediate to Advanced',
		accent: 'from-indigo-500 to-blue-500',
	},
	{
		id: 'company',
		label: 'Company-specific',
		description: 'FAANG, startup, senior and staff loops',
		query: ['interview', 'system design', 'staff', 'architecture'],
		difficulty: 'Adaptive',
		accent: 'from-purple-500 to-indigo-500',
	},
];

const FILTERS = {
	difficulty: ['All', 'Foundational', 'Intermediate', 'Advanced'],
	company: ['All', 'FAANG', 'Startup', 'Platform', 'AI Lab'],
	round: ['All', 'Phone Screen', 'System Design', 'Coding', 'Behavioral'],
	systemType: ['All', 'Realtime', 'Storage', 'Streaming', 'AI/ML'],
	duration: ['All', '15 min', '30 min', '45 min', '60 min'],
};

const WHITEBOARD_NODES = [
	{ id: 'client', label: 'Client', x: 8, y: 33, tone: 'border-emerald-300 bg-emerald-50 text-emerald-700' },
	{ id: 'api', label: 'API Gateway', x: 26, y: 33, tone: 'border-violet-300 bg-violet-50 text-violet-700' },
	{ id: 'rate', label: 'Rate Limiter', x: 46, y: 33, tone: 'border-blue-300 bg-blue-50 text-blue-700' },
	{ id: 'queue', label: 'Queue', x: 66, y: 18, tone: 'border-sky-300 bg-sky-50 text-sky-700' },
	{ id: 'db', label: 'Primary DB', x: 66, y: 50, tone: 'border-orange-300 bg-orange-50 text-orange-700' },
	{ id: 'cache', label: 'Cache', x: 46, y: 62, tone: 'border-rose-300 bg-rose-50 text-rose-700' },
];

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

const normalize = (value: string) => value.toLowerCase();

const postHaystack = (post: LeanPost) =>
	`${post.title} ${post.brief} ${post.series?.name ?? ''} ${post.tags.map((tag) => `${tag.name} ${tag.slug}`).join(' ')}`.toLowerCase();

const getMatchingPosts = (posts: LeanPost[], query: string[]) => {
	const matches = posts.filter((post) => {
		const haystack = postHaystack(post);
		return query.some((term) => haystack.includes(normalize(term)));
	});
	return matches.length > 0 ? matches : posts;
};

const getQuestionTitle = (post: LeanPost, categoryLabel: string) => {
	if (/design|architecture|system|distributed|database|kafka|raft|queue|cache/i.test(post.title)) {
		return post.title;
	}
	return `${categoryLabel}: ${post.title}`;
};

const getDifficulty = (minutes: number) => {
	if (minutes >= 13) return 'Advanced';
	if (minutes >= 7) return 'Intermediate';
	return 'Foundational';
};

const formatPercent = (value: number) => `${clamp(Math.round(value), 0, 100)}%`;

const loadPrepState = (): PrepState => {
	try {
		const raw = localStorage.getItem(PREP_STATE_KEY);
		return raw ? { ...DEFAULT_PREP_STATE, ...(JSON.parse(raw) as Partial<PrepState>) } : DEFAULT_PREP_STATE;
	} catch {
		return DEFAULT_PREP_STATE;
	}
};

const savePrepState = (state: PrepState) => {
	try {
		localStorage.setItem(PREP_STATE_KEY, JSON.stringify(state));
	} catch {}
};

const SectionTitle = ({
	eyebrow,
	title,
	description,
	action,
}: {
	eyebrow?: string;
	title: string;
	description?: string;
	action?: React.ReactNode;
}) => (
	<div className="mb-5 flex flex-wrap items-end justify-between gap-4">
		<div>
			{eyebrow ? <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-violet-600">{eyebrow}</p> : null}
			<h2 className="mt-1 text-2xl font-semibold tracking-tight text-neutral-950 dark:text-neutral-50">{title}</h2>
			{description ? <p className="mt-1 max-w-3xl text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">{description}</p> : null}
		</div>
		{action ? <div className="shrink-0">{action}</div> : null}
	</div>
);

const Pill = ({ children }: { children: React.ReactNode }) => (
	<span className="rounded-full border border-violet-100 bg-white/70 px-2.5 py-1 text-[11px] font-medium text-neutral-600 shadow-sm dark:border-neutral-800 dark:bg-neutral-900/70 dark:text-neutral-300">
		{children}
	</span>
);

const ProgressBar = ({ value, tone = 'bg-violet-600' }: { value: number; tone?: string }) => (
	<div className="h-2 overflow-hidden rounded-full bg-neutral-100 dark:bg-neutral-800">
		<div className={`h-full rounded-full ${tone}`} style={{ width: `${clamp(value, 0, 100)}%` }} />
	</div>
);

export default function InterviewPrepPage({ publication, posts, footerPosts }: Props) {
	const { features, loading: featureLoading } = useFeatureConfig();
	const reduceMotion = useReducedMotion();
	const [prepState, setPrepState] = useState<PrepState>(DEFAULT_PREP_STATE);
	const [bookmarks, setBookmarks] = useState<string[]>([]);
	const [savedReadSlugs, setSavedReadSlugs] = useState<string[]>([]);
	const [activeCategory, setActiveCategory] = useState(PREP_CATEGORIES[0].id);
	const [activeSidebar, setActiveSidebar] = useState('dashboard');
	const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
	const [mockMode, setMockMode] = useState<'idle' | 'live' | 'report'>('idle');
	const [savedAnswerSlug, setSavedAnswerSlug] = useState<string | null>(null);
	const [filters, setFilters] = useState({
		difficulty: 'All',
		company: 'All',
		round: 'All',
		systemType: 'All',
		duration: 'All',
	});
	const { setContext } = useLearningContext();
	const recordInterviewPractice = useLearningMemoryStore((state) => state.recordInterviewPractice);
	const recordConceptCompleted = useLearningMemoryStore((state) => state.recordConceptCompleted);

	useEffect(() => {
		setPrepState(loadPrepState());
		setSavedReadSlugs(loadLearningPath()?.readSlugs ?? []);
		try {
			setBookmarks(JSON.parse(localStorage.getItem(BOOKMARKS_KEY) ?? '[]') as string[]);
			setIsSidebarCollapsed(localStorage.getItem(SIDEBAR_COLLAPSED_KEY) === 'true');
		} catch {}
	}, []);

	useEffect(() => {
		const onScroll = () => {
			let current = SIDEBAR_ITEMS[0];
			for (const item of SIDEBAR_ITEMS) {
				const el = document.querySelector(item.href);
				if (el && el.getBoundingClientRect().top <= 130) {
					current = item;
				}
			}
			setActiveSidebar(current.id);
		};
		onScroll();
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	}, []);

	const activeCategoryData = PREP_CATEGORIES.find((item) => item.id === activeCategory) ?? PREP_CATEGORIES[0];

	useEffect(() => {
		setContext({
			source: 'interview-prep',
			pathname: '/interview-prep',
			title: 'Engineering Interview Prep',
			domain: 'Engineering',
			topic: 'Interview Prep',
			subtopic: activeCategoryData.label,
			concept: activeCategoryData.label,
			roadmapNode: activeCategoryData.label,
			roadmapHref: '/interview-prep',
			simulationTopic: activeCategoryData.label,
		});
	}, [activeCategoryData.label, setContext]);

	const completedSlugs = useMemo(
		() => new Set([...savedReadSlugs, ...prepState.completedSlugs]),
		[prepState.completedSlugs, savedReadSlugs],
	);
	const completedCount = completedSlugs.size;
	const totalPosts = Math.max(posts.length, 1);
	const overallReadiness = clamp(42 + Math.round((completedCount / totalPosts) * 38) + prepState.mockInterviews * 4, 0, 96);

	const categories = useMemo(
		() =>
			PREP_CATEGORIES.map((category) => {
				const matches = getMatchingPosts(posts, category.query);
				const completed = matches.filter((post) => completedSlugs.has(post.slug)).length;
				const totalMinutes = matches.reduce((sum, post) => sum + post.readTimeInMinutes, 0);
				return {
					...category,
					questionCount: matches.length,
					completion: matches.length ? Math.round((completed / matches.length) * 100) : 0,
					timeLabel: totalMinutes > 60 ? `${Math.round(totalMinutes / 60)} hr` : `${Math.max(totalMinutes, 20)} min`,
					preview: matches.slice(0, 3),
				};
			}),
		[completedSlugs, posts],
	);

	const questions = useMemo(() => {
		const source = getMatchingPosts(posts, activeCategoryData.query)
			.slice()
			.sort((a, b) => b.views - a.views || b.readTimeInMinutes - a.readTimeInMinutes)
			.slice(0, 8);

		return source
			.map((post, index) => ({
				post,
				title: getQuestionTitle(post, activeCategoryData.label),
				difficulty: getDifficulty(post.readTimeInMinutes),
				frequency: clamp(56 + Math.round((post.views || 0) / 20) + index * 3, 52, 96),
				round: activeCategoryData.id === 'behavioral' ? 'Behavioral' : activeCategoryData.id === 'coding' ? 'Coding' : 'System Design',
				systemType:
					activeCategoryData.id === 'distributed'
						? 'Streaming'
						: activeCategoryData.id === 'ai-ml'
						? 'AI/ML'
						: activeCategoryData.id === 'databases'
						? 'Storage'
						: 'Realtime',
			}))
			.filter((question) => filters.difficulty === 'All' || question.difficulty === filters.difficulty)
			.filter((question) => filters.round === 'All' || question.round === filters.round)
			.filter((question) => filters.systemType === 'All' || question.systemType === filters.systemType);
	}, [activeCategoryData, filters, posts]);

	const recommended = useMemo(() => {
		const weakCategories = categories.slice().sort((a, b) => a.completion - b.completion).slice(0, 3);
		return weakCategories.flatMap((category) =>
			category.preview.slice(0, 2).map((post) => ({
				category: category.label,
				post,
				reason: category.completion < 25 ? 'Build core coverage' : 'Strengthen weak-area depth',
			})),
		).slice(0, 4);
	}, [categories]);

	const readinessBreakdown = [
		{ label: 'System design', value: categories.find((item) => item.id === 'system-design')?.completion ?? 0 },
		{ label: 'Coding', value: categories.find((item) => item.id === 'coding')?.completion ?? 0 },
		{ label: 'Behavioral', value: Math.max(prepState.communicationScore - 8, 0) },
		{ label: 'Communication', value: prepState.communicationScore },
	];

	const improvementSuggestions = readinessBreakdown
		.slice()
		.sort((a, b) => a.value - b.value)
		.slice(0, 2)
		.map((item) => `Prioritize ${item.label.toLowerCase()} practice this week.`);

	const setCollapsed = (value: boolean) => {
		setIsSidebarCollapsed(value);
		try {
			localStorage.setItem(SIDEBAR_COLLAPSED_KEY, String(value));
		} catch {}
	};

	const toggleBookmark = (slug: string) => {
		const next = bookmarks.includes(slug) ? bookmarks.filter((item) => item !== slug) : [...bookmarks, slug];
		setBookmarks(next);
		try {
			localStorage.setItem(BOOKMARKS_KEY, JSON.stringify(next));
		} catch {}
	};

	const markPracticed = (slug: string) => {
		if (prepState.completedSlugs.includes(slug)) return;
		const next = { ...prepState, completedSlugs: [...prepState.completedSlugs, slug] };
		setPrepState(next);
		savePrepState(next);
		const question = questions.find((item) => item.post.slug === slug);
		if (question) {
			recordConceptCompleted({
				label: question.title,
				domain: activeCategoryData.label,
				slug,
				minutes: question.post.readTimeInMinutes,
			});
			recordInterviewPractice({
				topic: activeCategoryData.label,
				weakness: question.difficulty === 'Advanced' ? 'advanced tradeoff depth' : 'interview fluency',
				communicationDelta: 1,
			});
		}
	};

	const startMockInterview = () => {
		setMockMode('live');
		const next = { ...prepState, mockInterviews: prepState.mockInterviews + 1, communicationScore: clamp(prepState.communicationScore + 2, 0, 96) };
		setPrepState(next);
		savePrepState(next);
		recordInterviewPractice({
			topic: activeCategoryData.label,
			weakness: 'communication structure',
			communicationDelta: 2,
			completed: true,
		});
	};

	const motionProps = reduceMotion
		? { initial: { opacity: 1, y: 0 }, animate: { opacity: 1, y: 0 } }
		: { initial: { opacity: 0, y: 12 }, animate: { opacity: 1, y: 0 } };

	if (featureLoading) return null;
	if (!features.interviewPrep) {
		return <AppProvider publication={publication} footerPosts={footerPosts}><Layout><Container><PersonalHeader /><div className="mx-auto max-w-2xl px-5 py-24 text-center"><h1 className="text-3xl font-black text-slate-950 dark:text-white">Interview Prep is currently unavailable</h1><p className="mt-3 text-slate-500">This feature can be enabled by an administrator.</p><Link href="/" className="mt-6 inline-flex rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white">Return home</Link></div><Footer /></Container></Layout></AppProvider>;
	}

	return (
		<AppProvider publication={publication} footerPosts={footerPosts}>
			<Layout>
				<Head>
					<title>Engineering Interview Prep - {publication.title}</title>
					<meta
						name="description"
						content="AI-native engineering interview preparation with mock interviews, adaptive question practice, system design whiteboarding, and readiness tracking."
					/>
					<meta property="og:title" content={`Engineering Interview Prep - ${publication.title}`} />
					<meta property="og:image" content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)} />
					<meta property="twitter:card" content="summary_large_image" />
					<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }} />
				</Head>

				<Container className="mx-auto w-full bg-[radial-gradient(circle_at_20%_0%,rgba(124,58,237,0.10),transparent_28%),radial-gradient(circle_at_80%_12%,rgba(37,99,235,0.10),transparent_28%)]">
					<PersonalHeader />
					<div className="mx-auto grid w-full max-w-[1440px] gap-5 px-5 pb-24 pt-5 md:grid-cols-[auto_minmax(0,1fr)] md:px-8 md:pb-12">
						<aside
							className={`sticky top-[76px] hidden h-[calc(100vh-92px)] self-start rounded-2xl border border-white/70 bg-white/78 p-3 shadow-sm shadow-violet-100/70 backdrop-blur-xl dark:border-neutral-800 dark:bg-neutral-950/80 md:block ${
								isSidebarCollapsed ? 'w-[76px]' : 'w-[250px]'
							}`}
						>
							<div className="mb-3 flex items-center justify-between gap-2 px-2">
								{!isSidebarCollapsed ? (
									<div>
										<p className="text-xs font-bold text-neutral-950 dark:text-neutral-50">Interview Prep</p>
										<p className="text-[11px] text-neutral-500 dark:text-neutral-400">Adaptive workspace</p>
									</div>
								) : null}
								<button
									type="button"
									onClick={() => setCollapsed(!isSidebarCollapsed)}
									aria-label={isSidebarCollapsed ? 'Expand interview prep sidebar' : 'Collapse interview prep sidebar'}
									className="rounded-lg border border-neutral-200 px-2 py-1 text-xs text-neutral-500 hover:border-violet-300 hover:text-violet-600 dark:border-neutral-800"
								>
									{isSidebarCollapsed ? '>' : '<'}
								</button>
							</div>
							<nav className="space-y-4">
								{Object.entries(
									SIDEBAR_ITEMS.reduce<Record<string, SidebarItem[]>>((acc, item) => {
										const group = item.group ?? 'General';
										acc[group] = [...(acc[group] ?? []), item];
										return acc;
									}, {}),
								).map(([group, items]) => (
									<div key={group}>
										{!isSidebarCollapsed ? <p className="px-2 pb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-neutral-400">{group}</p> : null}
										<div className="space-y-1">
											{items.map((item) => (
												<Link
													key={item.id}
													href={item.href}
													title={item.label}
													className={`group flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-medium transition-colors ${
														activeSidebar === item.id
															? 'bg-violet-50 text-violet-700 shadow-sm dark:bg-violet-950/30 dark:text-violet-300'
															: 'text-neutral-600 hover:bg-neutral-50 hover:text-neutral-950 dark:text-neutral-300 dark:hover:bg-neutral-900'
													}`}
												>
													<span className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-white text-[11px] shadow-sm dark:bg-neutral-900">
														{item.label.charAt(0)}
													</span>
													{!isSidebarCollapsed ? <span>{item.label}</span> : null}
												</Link>
											))}
										</div>
									</div>
								))}
							</nav>
						</aside>

						<main className="min-w-0 space-y-8" id="dashboard">
							<motion.section
								{...motionProps}
								transition={{ duration: 0.35 }}
								className="grid gap-5 rounded-[28px] border border-white/80 bg-white/78 p-5 shadow-xl shadow-violet-100/70 backdrop-blur-xl dark:border-neutral-800 dark:bg-neutral-950/80 lg:grid-cols-[minmax(0,1.05fr)_minmax(420px,0.95fr)]"
							>
								<div className="flex min-h-[410px] flex-col justify-center py-6 md:px-5">
									<Pill>AI-native engineering interview OS</Pill>
									<h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-tight text-neutral-950 dark:text-neutral-50 md:text-6xl">
										Crack your next engineering interview.
									</h1>
									<p className="mt-5 max-w-2xl text-base leading-8 text-neutral-600 dark:text-neutral-300 md:text-lg">
										Practice real-world questions, get AI feedback, and prepare with guided mock interviews across system design, coding, behavioral, and AI/ML rounds.
									</p>
									<div className="mt-7 flex flex-wrap gap-3">
										<a
											href="#question-bank"
											className="inline-flex rounded-xl bg-gradient-to-r from-violet-600 to-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-violet-500/20 transition hover:from-violet-700 hover:to-blue-700"
										>
											Practice Questions
										</a>
										<button
											type="button"
											onClick={startMockInterview}
											className="inline-flex rounded-xl border border-neutral-200 bg-white px-5 py-3 text-sm font-semibold text-neutral-800 shadow-sm transition hover:border-violet-300 hover:text-violet-700 dark:border-neutral-800 dark:bg-neutral-900 dark:text-neutral-100"
										>
											Take Mock Interview
										</button>
									</div>
									<div className="mt-7 grid max-w-2xl grid-cols-3 gap-3">
										{[
											['Targets', prepState.targetCompanies.join(', ')],
											['Mode', prepState.preferredDomain],
											['Difficulty', prepState.difficulty],
										].map(([label, value]) => (
											<div key={label} className="rounded-2xl border border-neutral-100 bg-white/70 p-3 text-sm shadow-sm dark:border-neutral-800 dark:bg-neutral-900/70">
												<p className="text-[11px] text-neutral-500">{label}</p>
												<p className="mt-1 line-clamp-1 font-semibold text-neutral-950 dark:text-neutral-50">{value}</p>
											</div>
										))}
									</div>
								</div>

								<div className="relative min-h-[410px] overflow-hidden rounded-[24px] border border-violet-100 bg-gradient-to-br from-violet-50 via-white to-blue-50 p-5 dark:border-neutral-800 dark:from-violet-950/20 dark:via-neutral-950 dark:to-blue-950/20">
									<div className="absolute inset-0 bg-[linear-gradient(rgba(99,102,241,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(99,102,241,0.08)_1px,transparent_1px)] bg-[size:34px_34px]" />
									<div className="relative z-10 flex h-full flex-col justify-between">
										<div className="flex items-center justify-between">
											<div className="rounded-2xl bg-white/85 p-4 shadow-lg shadow-violet-200/40 dark:bg-neutral-900/85">
												<p className="text-xs font-semibold text-neutral-500">AI Interviewer</p>
												<p className="mt-1 text-sm font-bold text-neutral-950 dark:text-neutral-50">System Design Round</p>
											</div>
											<div className="rounded-2xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-violet-500/30">
												Design a rate limiter in 10 minutes.
											</div>
										</div>
										<div className="mx-auto grid w-full max-w-xl grid-cols-3 items-center gap-4">
											{['Candidate', 'Whiteboard', 'Interviewer'].map((item, index) => (
												<div key={item} className="rounded-3xl border border-white/80 bg-white/82 p-4 text-center shadow-lg shadow-blue-100/70 dark:border-neutral-800 dark:bg-neutral-900/80">
													<div className={`mx-auto mb-3 h-14 w-14 rounded-2xl bg-gradient-to-br ${index === 1 ? 'from-blue-500 to-cyan-400' : 'from-violet-500 to-blue-500'}`} />
													<p className="text-xs font-semibold text-neutral-700 dark:text-neutral-200">{item}</p>
												</div>
											))}
										</div>
										<div className="grid grid-cols-3 gap-3">
											{WHITEBOARD_NODES.slice(1, 4).map((node) => (
												<div key={node.id} className={`rounded-2xl border px-3 py-2 text-center text-xs font-semibold ${node.tone}`}>
													{node.label}
												</div>
											))}
										</div>
									</div>
								</div>
							</motion.section>

							<EmbeddedAIMentor
								contextTitle="Engineering Interview Prep"
								concept={activeCategoryData.label}
								section="Interview readiness"
								posts={posts}
							/>

							<InlineSimulation
								topic={activeCategoryData.label}
								node="Interview topology"
								source="interview-prep"
							/>

							<section id="readiness" className="grid gap-5 lg:grid-cols-[minmax(0,0.95fr)_minmax(360px,0.55fr)]">
								<div className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm backdrop-blur dark:border-neutral-800 dark:bg-neutral-950/80">
									<SectionTitle
										eyebrow="Readiness"
										title="Interview readiness score"
										description="A lightweight adaptive score from saved paths, completed practice, mock interviews, and communication signals."
										action={<Link href="#activity" className="text-sm font-semibold text-violet-700 hover:text-violet-900">View Detailed Report</Link>}
									/>
									<div className="grid gap-5 md:grid-cols-[220px_minmax(0,1fr)]">
										<div className="flex aspect-square items-center justify-center rounded-full bg-[conic-gradient(from_180deg,#7c3aed_0deg,#2563eb_var(--score),#eef2ff_var(--score),#eef2ff_360deg)] p-4" style={{ ['--score' as string]: `${overallReadiness * 3.6}deg` }}>
											<div className="flex h-full w-full flex-col items-center justify-center rounded-full bg-white text-center shadow-inner dark:bg-neutral-950">
												<p className="text-5xl font-semibold tracking-tight text-neutral-950 dark:text-neutral-50">{overallReadiness}%</p>
												<p className="mt-1 text-xs font-medium text-neutral-500">Overall readiness</p>
											</div>
										</div>
										<div className="space-y-4">
											{readinessBreakdown.map((item) => (
												<div key={item.label}>
													<div className="mb-1 flex justify-between text-sm">
														<span className="font-medium text-neutral-700 dark:text-neutral-200">{item.label}</span>
														<span className="text-neutral-500">{formatPercent(item.value)}</span>
													</div>
													<ProgressBar value={item.value} tone="bg-gradient-to-r from-violet-600 to-blue-600" />
												</div>
											))}
										</div>
									</div>
								</div>
								<div className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm backdrop-blur dark:border-neutral-800 dark:bg-neutral-950/80">
									<p className="text-sm font-semibold text-neutral-950 dark:text-neutral-50">AI improvement plan</p>
									<div className="mt-4 space-y-3">
										{improvementSuggestions.map((item) => (
											<div key={item} className="rounded-2xl bg-violet-50/80 p-3 text-sm text-violet-900 dark:bg-violet-950/30 dark:text-violet-200">
												{item}
											</div>
										))}
										<Link href="/learn" className="inline-flex rounded-xl bg-neutral-950 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-neutral-950">
											Ask AI Coach
										</Link>
									</div>
								</div>
							</section>

							<section id="system-design">
								<SectionTitle
									eyebrow="Practice"
									title="Practice by category"
									description="Question counts, difficulty, completion, and estimated preparation time are derived from the current article library."
									action={<a href="#question-bank" className="text-sm font-semibold text-violet-700">Explore Questions</a>}
								/>
								<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
									{categories.map((category) => (
										<button
											key={category.id}
											type="button"
											onClick={() => setActiveCategory(category.id)}
											className={`group rounded-3xl border bg-white/82 p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-xl hover:shadow-violet-100 dark:bg-neutral-950/80 ${
												activeCategory === category.id ? 'border-violet-300 ring-4 ring-violet-100 dark:border-violet-700 dark:ring-violet-950/40' : 'border-white/80 dark:border-neutral-800'
											}`}
										>
											<div className={`mb-4 h-12 w-12 rounded-2xl bg-gradient-to-br ${category.accent}`} />
											<div className="flex items-start justify-between gap-3">
												<div>
													<p className="font-semibold text-neutral-950 dark:text-neutral-50">{category.label}</p>
													<p className="mt-1 text-xs leading-relaxed text-neutral-500 dark:text-neutral-400">{category.description}</p>
												</div>
												<span className="text-xs font-semibold text-violet-700">{category.questionCount} Qs</span>
											</div>
											<div className="mt-4 space-y-2">
												<div className="flex justify-between text-[11px] text-neutral-500">
													<span>{category.difficulty}</span>
													<span>{formatPercent(category.completion)}</span>
												</div>
												<ProgressBar value={category.completion} tone={`bg-gradient-to-r ${category.accent}`} />
												<p className="text-[11px] text-neutral-500">{category.timeLabel} estimated prep</p>
											</div>
											<div className="mt-4 hidden rounded-2xl bg-neutral-50 p-3 text-[11px] text-neutral-600 group-hover:block dark:bg-neutral-900 dark:text-neutral-300">
												{category.preview.slice(0, 2).map((post) => (
													<p key={post.id} className="line-clamp-1">Preview: {getQuestionTitle(post, category.label)}</p>
												))}
											</div>
										</button>
									))}
								</div>
							</section>

							<section id="recommendations">
								<SectionTitle
									eyebrow="Adaptive"
									title="Recommended for you"
									description="Recommendations adjust toward lower-completion categories and your active practice domain."
									action={<a href="#question-bank" className="text-sm font-semibold text-violet-700">Continue Practice</a>}
								/>
								<div className="grid gap-4 lg:grid-cols-4">
									{recommended.map(({ post, category, reason }) => (
										<Link key={`${category}-${post.slug}`} href={`/${post.slug}`} className="rounded-3xl border border-white/80 bg-white/82 p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-xl hover:shadow-violet-100 dark:border-neutral-800 dark:bg-neutral-950/80">
											<Pill>{category}</Pill>
											<p className="mt-4 line-clamp-2 text-sm font-semibold text-neutral-950 dark:text-neutral-50">{post.title}</p>
											<p className="mt-2 line-clamp-2 text-xs leading-relaxed text-neutral-500">{reason}</p>
											<p className="mt-4 text-[11px] font-medium text-violet-700">{post.readTimeInMinutes} min practice</p>
										</Link>
									))}
								</div>
							</section>

							<section id="mock-interviews" className="grid gap-5 lg:grid-cols-[minmax(0,0.9fr)_minmax(360px,0.55fr)]">
								<div className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-950/80">
									<SectionTitle
										eyebrow="Mock interview"
										title={mockMode === 'live' ? 'AI interview in progress' : mockMode === 'report' ? 'Post interview report' : 'Upcoming mock interview'}
										description="Run a realistic system design interview loop with adaptive follow-ups and communication feedback."
									/>
									{mockMode === 'idle' ? (
										<div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_220px]">
											<div className="rounded-2xl bg-violet-50 p-4 dark:bg-violet-950/30">
												<p className="text-sm font-semibold text-neutral-950 dark:text-neutral-50">System Design Mock</p>
												<p className="mt-1 text-sm text-neutral-600 dark:text-neutral-300">45 minutes • adaptive interviewer • medium to senior level</p>
												<ul className="mt-4 grid gap-2 text-sm text-neutral-600 dark:text-neutral-300">
													<li>Clarify functional and non-functional requirements</li>
													<li>Whiteboard API, data model, scale, and tradeoffs</li>
													<li>Handle failure scenarios and optimization round</li>
												</ul>
											</div>
											<div className="space-y-2">
												<button type="button" onClick={startMockInterview} className="w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white hover:bg-violet-700">Start Interview</button>
												<button type="button" className="w-full rounded-xl border border-neutral-200 px-4 py-3 text-sm font-semibold text-neutral-700 hover:border-violet-300 dark:border-neutral-800 dark:text-neutral-200">Reschedule</button>
												<a href="#question-bank" className="block w-full rounded-xl border border-neutral-200 px-4 py-3 text-center text-sm font-semibold text-neutral-700 hover:border-violet-300 dark:border-neutral-800 dark:text-neutral-200">Review Preparation</a>
											</div>
										</div>
									) : mockMode === 'live' ? (
										<div className="grid gap-4 lg:grid-cols-[minmax(0,0.8fr)_minmax(260px,0.45fr)]">
											<div className="rounded-3xl border border-violet-100 bg-gradient-to-br from-violet-50 to-blue-50 p-4 dark:border-neutral-800 dark:from-violet-950/30 dark:to-blue-950/20">
												<div className="flex items-center justify-between">
													<div>
														<p className="text-sm font-semibold text-neutral-950 dark:text-neutral-50">AI Interviewer</p>
														<p className="text-xs text-neutral-500">Senior engineer persona • live questioning</p>
													</div>
													<span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-semibold text-emerald-700">Live</span>
												</div>
												<div className="mt-5 rounded-2xl bg-white p-4 text-sm text-neutral-700 shadow-sm dark:bg-neutral-900 dark:text-neutral-200">
													Design a scalable notification system. Start by clarifying requirements and traffic assumptions.
												</div>
												<div className="mt-4 rounded-2xl bg-white p-4 dark:bg-neutral-900">
													<p className="text-xs font-semibold text-neutral-500">Your answer</p>
													<div className="mt-3 h-20 rounded-xl bg-[linear-gradient(90deg,#8b5cf6_10%,#60a5fa_28%,#ddd6fe_50%,#3b82f6_78%)] opacity-80" />
												</div>
											</div>
											<div className="space-y-2">
												{['Pause', 'Repeat Question', 'Ask for Clarification', 'View Notes'].map((action) => (
													<button key={action} type="button" className="w-full rounded-xl border border-neutral-200 px-4 py-3 text-sm font-semibold text-neutral-700 hover:border-violet-300 dark:border-neutral-800 dark:text-neutral-200">
														{action}
													</button>
												))}
												<button type="button" onClick={() => setMockMode('report')} className="w-full rounded-xl bg-neutral-950 px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-neutral-950">
													End Interview
												</button>
											</div>
										</div>
									) : (
										<div className="grid gap-4 md:grid-cols-3">
											{[
												['Communication clarity', prepState.communicationScore],
												['Architecture depth', overallReadiness - 4],
												['Tradeoff quality', overallReadiness - 8],
												['Scalability understanding', overallReadiness - 2],
												['Bottleneck identification', overallReadiness - 12],
												['Confidence score', overallReadiness - 6],
											].map(([label, value]) => (
												<div key={label} className="rounded-2xl bg-neutral-50 p-4 dark:bg-neutral-900">
													<p className="text-xs text-neutral-500">{label}</p>
													<p className="mt-1 text-2xl font-semibold text-neutral-950 dark:text-neutral-50">{formatPercent(Number(value))}</p>
													<ProgressBar value={Number(value)} tone="bg-gradient-to-r from-violet-600 to-blue-600" />
												</div>
											))}
											<div className="md:col-span-3 flex flex-wrap gap-2">
												<a href="#recommendations" className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white">Practice Weak Areas</a>
												<button type="button" onClick={startMockInterview} className="rounded-xl border border-neutral-200 px-4 py-2 text-sm font-semibold">Retry Interview</button>
												<a href="#whiteboard" className="rounded-xl border border-neutral-200 px-4 py-2 text-sm font-semibold">View Expert Solution</a>
											</div>
										</div>
									)}
								</div>
								<div className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-950/80">
									<p className="text-sm font-semibold text-neutral-950 dark:text-neutral-50">Interview flow</p>
									<div className="mt-4 space-y-2">
										{['Introduction', 'Clarification phase', 'Architecture discussion', 'Scaling discussion', 'Tradeoff analysis', 'Failure scenarios', 'Optimization round', 'Final review'].map((step, index) => (
											<div key={step} className="flex items-center gap-3 rounded-2xl bg-neutral-50 px-3 py-2 text-sm dark:bg-neutral-900">
												<span className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-xs font-semibold text-violet-700 shadow-sm dark:bg-neutral-950">{index + 1}</span>
												<span className="text-neutral-700 dark:text-neutral-200">{step}</span>
											</div>
										))}
									</div>
								</div>
							</section>

							<section id="question-bank" className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-950/80">
								<SectionTitle
									eyebrow="Question bank"
									title={`${activeCategoryData.label} practice`}
									description="Filter by difficulty, company target, round, system type, duration, and interview signal."
								/>
								<div className="grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)]">
									<div className="space-y-4 rounded-2xl bg-neutral-50 p-4 dark:bg-neutral-900">
										{Object.entries(FILTERS).map(([key, values]) => (
											<label key={key} className="block text-xs font-semibold capitalize text-neutral-600 dark:text-neutral-300">
												{key.replace(/([A-Z])/g, ' $1')}
												<select
													value={filters[key as keyof typeof filters]}
													onChange={(event) => setFilters((prev) => ({ ...prev, [key]: event.target.value }))}
													className="mt-1 w-full rounded-xl border border-neutral-200 bg-white px-3 py-2 text-sm font-medium text-neutral-800 dark:border-neutral-800 dark:bg-neutral-950 dark:text-neutral-100"
												>
													{values.map((value) => (
														<option key={value}>{value}</option>
													))}
												</select>
											</label>
										))}
									</div>
									<div className="space-y-3">
										{questions.length > 0 ? (
											questions.map((question) => (
												<div key={question.post.id} className="group rounded-2xl border border-neutral-100 bg-white p-4 shadow-sm transition hover:border-violet-200 hover:shadow-lg dark:border-neutral-800 dark:bg-neutral-950">
													<div className="flex flex-wrap items-start justify-between gap-3">
														<div className="min-w-0">
															<p className="font-semibold text-neutral-950 dark:text-neutral-50">{question.title}</p>
															<div className="mt-2 flex flex-wrap gap-2">
																<Pill>{question.difficulty}</Pill>
																<Pill>{question.frequency}% frequency</Pill>
																<Pill>{question.post.readTimeInMinutes} min</Pill>
																{question.post.tags.slice(0, 2).map((tag) => <Pill key={tag.id}>{tag.name}</Pill>)}
															</div>
														</div>
														<div className="flex flex-wrap gap-2">
															<button type="button" onClick={() => markPracticed(question.post.slug)} className="rounded-xl bg-violet-600 px-3 py-2 text-xs font-semibold text-white">Start Practice</button>
															<button type="button" onClick={() => toggleBookmark(question.post.slug)} className="rounded-xl border border-neutral-200 px-3 py-2 text-xs font-semibold dark:border-neutral-800">
																{bookmarks.includes(question.post.slug) ? 'Bookmarked' : 'Bookmark'}
															</button>
															<button type="button" onClick={() => setSavedAnswerSlug(question.post.slug)} className="rounded-xl border border-neutral-200 px-3 py-2 text-xs font-semibold dark:border-neutral-800">Save Answer</button>
															<Link href={`/${question.post.slug}`} className="rounded-xl border border-neutral-200 px-3 py-2 text-xs font-semibold dark:border-neutral-800">Read Guide</Link>
														</div>
													</div>
													<div className="mt-4 hidden grid-cols-2 gap-3 text-xs group-hover:grid">
														<div className="rounded-xl bg-violet-50 p-3 text-violet-900 dark:bg-violet-950/30 dark:text-violet-200">
															Answer outline: clarify requirements, propose baseline design, reason about scale, then identify bottlenecks.
														</div>
														<div className="rounded-xl bg-rose-50 p-3 text-rose-900 dark:bg-rose-950/30 dark:text-rose-200">
															Common mistake: jumping into implementation before constraints, SLAs, and tradeoffs are explicit.
														</div>
													</div>
												</div>
											))
										) : (
											<div className="rounded-2xl bg-neutral-50 p-6 text-sm text-neutral-500 dark:bg-neutral-900">
												No questions match these filters. Clear a filter or switch categories.
											</div>
										)}
									</div>
								</div>
							</section>

							<section id="whiteboard" className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-950/80">
								<SectionTitle
									eyebrow="Whiteboard"
									title="System design whiteboard"
									description="Reusable workspace for templates like URL shortener, rate limiter, chat, video, ride sharing, and notification systems."
									action={<a href="#recommendations" className="text-sm font-semibold text-violet-700">Review Recommendations</a>}
								/>
								<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_260px]">
									<div className="relative min-h-[430px] overflow-hidden rounded-3xl border border-violet-100 bg-[linear-gradient(rgba(99,102,241,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(99,102,241,0.08)_1px,transparent_1px)] bg-[size:32px_32px] p-4 dark:border-neutral-800">
										<svg className="absolute inset-0 h-full w-full text-violet-300" fill="none" viewBox="0 0 100 100" preserveAspectRatio="none">
											<path d="M20 42 C28 42 30 42 36 42 S45 42 51 42 M56 42 C62 42 68 30 73 28 M56 42 C62 42 66 58 73 60 M51 70 C51 62 51 54 51 48" stroke="currentColor" strokeWidth="0.6" strokeDasharray="2 2" />
										</svg>
										{WHITEBOARD_NODES.map((node) => (
											<div key={node.id} className={`absolute rounded-2xl border px-3 py-2 text-xs font-semibold shadow-sm ${node.tone}`} style={{ left: `${node.x}%`, top: `${node.y}%` }}>
												{node.label}
											</div>
										))}
										<div className="absolute bottom-4 left-4 rounded-2xl border border-blue-200 bg-white/90 p-4 text-xs shadow-sm dark:border-neutral-800 dark:bg-neutral-900/90">
											<p className="font-semibold text-blue-700 dark:text-blue-300">Design notes</p>
											<p className="mt-1 text-neutral-500">Token bucket, regional limits, Redis fallback, async audit stream.</p>
										</div>
									</div>
									<div className="space-y-2">
										{['Start Designing', 'Share Design', 'Replay Session', 'Get AI Review', 'Practice Again'].map((action, index) => (
											<Link
												key={action}
												href="#whiteboard"
												className={`block rounded-xl px-4 py-3 text-sm font-semibold ${
													index === 0 ? 'bg-violet-600 text-white' : 'border border-neutral-200 text-neutral-700 hover:border-violet-300 dark:border-neutral-800 dark:text-neutral-200'
												}`}
											>
												{action}
											</Link>
										))}
									</div>
								</div>
							</section>

							<section id="activity" className="grid gap-5 lg:grid-cols-3">
								<div className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-950/80 lg:col-span-2">
									<SectionTitle eyebrow="Activity" title="Recent activity" description="Completed interviews, saved answers, bookmarks, and weak-area improvements." />
									<div className="grid gap-3 md:grid-cols-2">
										{[
											['Completed mock interviews', `${prepState.mockInterviews}`],
											['Questions practiced', `${completedCount}`],
											['Saved answers', savedAnswerSlug ? '1 draft' : 'No drafts yet'],
											['Bookmarks', `${bookmarks.length}`],
										].map(([label, value]) => (
											<div key={label} className="rounded-2xl bg-neutral-50 p-4 dark:bg-neutral-900">
												<p className="text-xs text-neutral-500">{label}</p>
												<p className="mt-1 text-xl font-semibold text-neutral-950 dark:text-neutral-50">{value}</p>
											</div>
										))}
									</div>
								</div>
								<div className="rounded-3xl border border-white/80 bg-white/82 p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-950/80">
									<p className="text-sm font-semibold text-neutral-950 dark:text-neutral-50">Persistent AI coach</p>
									<div className="mt-4 space-y-2">
										{['Improve My Answer', 'Generate Better Tradeoffs', 'Ask Follow-up Questions', 'Explain Simpler', 'Challenge My Design'].map((prompt) => (
											<Link
												key={prompt}
												href="/learn"
												className="block rounded-xl border border-neutral-200 px-3 py-2 text-sm font-medium text-neutral-700 transition hover:border-violet-300 hover:text-violet-700 dark:border-neutral-800 dark:text-neutral-200"
											>
												{prompt}
											</Link>
										))}
									</div>
								</div>
							</section>
						</main>
					</div>

					<nav className="fixed bottom-0 left-0 right-0 z-40 border-t border-neutral-200 bg-white/94 px-2 py-2 backdrop-blur md:hidden dark:border-neutral-800 dark:bg-neutral-950/94">
						<div className="grid grid-cols-5 gap-1 text-center text-[11px]">
							<Link href="/" className="rounded-xl py-1.5 text-neutral-600 dark:text-neutral-300">Home</Link>
							<Link href="/posts" className="rounded-xl py-1.5 text-neutral-600 dark:text-neutral-300">Learn</Link>
							<Link href="/interview-prep" className="rounded-xl bg-violet-50 py-1.5 font-semibold text-violet-700 dark:bg-violet-950/30 dark:text-violet-300">Interview</Link>
							<Link href="/learn" className="rounded-xl py-1.5 text-neutral-600 dark:text-neutral-300">Learn</Link>
							<Link href="/learn" className="rounded-xl py-1.5 text-neutral-600 dark:text-neutral-300">Learn</Link>
						</div>
					</nav>
					<button
						type="button"
						onClick={startMockInterview}
						className="fixed bottom-16 right-4 z-40 rounded-full bg-gradient-to-r from-violet-600 to-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-xl shadow-violet-500/30 motion-safe:animate-pulse md:hidden"
					>
						Start Mock Interview
					</button>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		const first = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST },
		);

		const publication = first.publication;
		if (!publication) return { notFound: true };

		const raw: PostFragment[] = [...(publication.posts.edges ?? []).map((edge) => edge.node)];
		let cursor = publication.posts.pageInfo.endCursor;
		let hasNextPage = !!publication.posts.pageInfo.hasNextPage;

		while (hasNextPage && cursor) {
			const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
				GQL_ENDPOINT,
				MorePostsByPublicationDocument,
				{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
			);
			if (!next.publication) break;
			raw.push(...next.publication.posts.edges.map((edge) => edge.node));
			cursor = next.publication.posts.pageInfo.endCursor;
			hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
		}

		const posts: LeanPost[] = raw.map((post) => ({
			id: post.id,
			title: post.title,
			slug: post.slug,
			brief: post.brief ?? '',
			readTimeInMinutes: post.readTimeInMinutes ?? 5,
			views: post.views ?? 0,
			publishedAt: post.publishedAt,
			tags: (post.tags ?? []).map((tag) => ({ id: tag.id, name: tag.name, slug: tag.slug })),
			series: post.series ? { name: post.series.name, slug: post.series.slug } : null,
		}));

		return {
			props: { publication, posts, footerPosts: raw.slice(0, 8) },
			revalidate: 3600,
		};
	} catch (error) {
		console.error('[interview-prep] getStaticProps error:', error);
		return { notFound: true };
	}
};
