import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { resizeImage } from '@starter-kit/utils/image';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { Pagination } from '../components/pagination';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import {
	DEFAULT_SORT_BY_VIEW,
	filterPosts,
	getEffectiveUpdatedAt,
	getPostsForView,
	parsePostListSort,
	parsePostListView,
	POST_VIEW_META,
	PostListView,
	sortPosts,
} from '../lib/post-listing';
import { formatTagName } from '../utils/format';
import { loadLearningPath, StoredLearningPath } from '../components/learn-today';
import { CONTENT_REVALIDATE_SECONDS } from '../lib/cache-constants';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
const PAGE_SIZE = 12;
const RECENTLY_VIEWED_KEY = 'aa:recently-viewed-posts';
const FALLBACK_POST_IMAGE = '/assets/blog/post-fallback.svg';

const TOPIC_COLLECTIONS = [
	{ id: 'system-design', label: 'System Design', query: 'system design' },
	{ id: 'backend', label: 'Backend Systems', query: 'backend api database' },
	{ id: 'ai-llm', label: 'AI Infrastructure', query: 'llm rag ai model' },
	{ id: 'distributed', label: 'Distributed Systems', query: 'distributed systems consensus replication' },
	{ id: 'tradeoffs', label: 'Tradeoff Reasoning', query: 'tradeoff failure consistency latency' },
] as const;

type RecentlyViewedItem = {
	slug: string;
	title: string;
	seenAt: number;
};

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
};

type QueryUpdates = Partial<Record<'view' | 'sort' | 'tag' | 'series', string | null>>;

const getQueryValue = (value: string | string[] | undefined) =>
	typeof value === 'string' && value.length > 0 ? value : '';

const buildTagOptions = (posts: PostFragment[]) => {
	const tags = new Map<string, { slug: string; name: string; count: number }>();

	posts.forEach((post) => {
		post.tags?.forEach((tag) => {
			const existing = tags.get(tag.slug);
			tags.set(tag.slug, {
				slug: tag.slug,
				name: formatTagName(tag.name),
				count: (existing?.count ?? 0) + 1,
			});
		});
	});

	return [...tags.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
};

const getVisibleOptions = <T extends { slug: string }>(
	options: T[],
	selectedSlug: string,
	limit: number,
) => {
	const topOptions = options.slice(0, limit);
	if (!selectedSlug || topOptions.some((option) => option.slug === selectedSlug)) {
		return topOptions;
	}

	const selected = options.find((option) => option.slug === selectedSlug);
	return selected ? [selected, ...topOptions.slice(0, Math.max(limit - 1, 0))] : topOptions;
};

const readRecentlyViewed = (): RecentlyViewedItem[] => {
	if (typeof window === 'undefined') return [];
	try {
		const raw = localStorage.getItem(RECENTLY_VIEWED_KEY);
		if (!raw) return [];
		return JSON.parse(raw) as RecentlyViewedItem[];
	} catch {
		return [];
	}
};

const resolvePostImage = (post: Pick<PostFragment, 'coverImage'>) =>
	post.coverImage?.url?.trim()
		? resizeImage(post.coverImage.url, { w: 960, h: 540, c: 'thumb' })
		: FALLBACK_POST_IMAGE;

export default function AllPostsPage({ publication, initialPosts }: Props) {
	const router = useRouter();
	const [searchTerm, setSearchTerm] = useState('');
	const [searchFocused, setSearchFocused] = useState(false);
	const [recentlyViewed, setRecentlyViewed] = useState<RecentlyViewedItem[]>([]);
	const [savedPath, setSavedPath] = useState<StoredLearningPath | null>(null);

	const view = parsePostListView(router.query.view);
	const sort = parsePostListSort(router.query.sort, view);
	const tagSlug = getQueryValue(router.query.tag);
	const seriesSlug = getQueryValue(router.query.series);

	const updateQuery = (updates: QueryUpdates) => {
		const nextState = {
			view,
			sort,
			tag: tagSlug,
			series: seriesSlug,
			...updates,
		};

		const nextQuery = Object.fromEntries(
			Object.entries(nextState).filter(([, value]) => value && value.length > 0),
		);

		router.replace(
			{
				pathname: '/posts',
				query: nextQuery,
			},
			undefined,
			{ shallow: true, scroll: false },
		);
	};

	const clearFilters = () => {
		setSearchTerm('');
		router.replace('/posts', undefined, { shallow: true, scroll: false });
	};

	useEffect(() => {
		setRecentlyViewed(readRecentlyViewed());
		setSavedPath(loadLearningPath());
	}, []);

	const rememberPostView = (post: PostFragment) => {
		if (typeof window === 'undefined') return;
		try {
			const next = [
				{ slug: post.slug, title: post.title, seenAt: Date.now() },
				...readRecentlyViewed().filter((entry) => entry.slug !== post.slug),
			].slice(0, 8);
			localStorage.setItem(RECENTLY_VIEWED_KEY, JSON.stringify(next));
			setRecentlyViewed(next);
		} catch {}
	};

	const tagOptions = useMemo(() => buildTagOptions(initialPosts), [initialPosts]);
	const visibleTagOptions = useMemo(
		() => getVisibleOptions(tagOptions, tagSlug, 6),
		[tagOptions, tagSlug],
	);
	const filteredPosts = useMemo(() => {
		const basePosts = getPostsForView(initialPosts, view);
		const queryFilteredPosts = filterPosts(basePosts, {
			searchTerm,
			tagSlug: tagSlug || null,
			seriesSlug: seriesSlug || null,
			createdFrom: '',
			createdTo: '',
			updatedFrom: '',
			updatedTo: '',
		});

		return sortPosts(queryFilteredPosts, sort);
	}, [
		initialPosts,
		searchTerm,
		seriesSlug,
		sort,
		tagSlug,
		view,
	]);

	const activeFilterCount = [
		searchTerm,
		tagSlug,
		seriesSlug,
	].filter(Boolean).length;
	const activeView = POST_VIEW_META[view];
	const pageHeading =
		sort === 'popular-desc' && view === 'all'
			? {
					label: 'Reader favorites',
					description: 'Popular systems chapters, ordered by what readers return to most.',
			  }
			: activeView;

	// ── Pagination ────────────────────────────────────────────────────────────
	const [currentPage, setCurrentPage] = useState(1);

	// Reset to page 1 whenever the result set changes
	useEffect(() => {
		setCurrentPage(1);
	}, [filteredPosts.length, view, sort, tagSlug, seriesSlug, searchTerm]);

	const totalPages = Math.ceil(filteredPosts.length / PAGE_SIZE);
	const pagedPosts = filteredPosts.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

	const handlePageChange = (page: number) => {
		setCurrentPage(page);
		window.scrollTo({ top: 0, behavior: 'smooth' });
	};

	const searchPreviewPosts = useMemo(() => {
		if (searchTerm.length < 2) return [];
		const q = searchTerm.toLowerCase();
		return initialPosts
			.filter((p) => p.title.toLowerCase().includes(q) || (p.brief ?? '').toLowerCase().includes(q))
			.slice(0, 5);
	}, [initialPosts, searchTerm]);

	const recentlyViewedPosts = useMemo(
		() =>
			recentlyViewed
				.map((entry) => initialPosts.find((post) => post.slug === entry.slug))
				.filter((post): post is PostFragment => Boolean(post))
				.slice(0, 4),
		[initialPosts, recentlyViewed],
	);

	const aiRecommendedPosts = useMemo(() => {
		const recentlyViewedSlugs = new Set(recentlyViewed.map((entry) => entry.slug));
		const recentlyViewedTags = new Set(
			recentlyViewedPosts.flatMap((post) => (post.tags ?? []).map((tag) => tag.slug)),
		);
		const tagFocus = tagSlug || '';
		const seriesFocus = seriesSlug || '';
		const query = searchTerm.toLowerCase().trim();

		return [...initialPosts]
			.map((post) => {
				let score = 0;
				if (!recentlyViewedSlugs.has(post.slug)) score += 1;
				if (tagFocus && post.tags?.some((tag) => tag.slug === tagFocus)) score += 4;
				if (seriesFocus && post.series?.slug === seriesFocus) score += 4;
				if (query && `${post.title} ${post.brief}`.toLowerCase().includes(query)) score += 2;
				if (post.tags?.some((tag) => recentlyViewedTags.has(tag.slug))) score += 3;
				score += (post.views ?? 0) / 10000;
				return { post, score };
			})
			.sort((a, b) => b.score - a.score)
			.slice(0, 5)
			.map((entry) => entry.post);
	}, [
		initialPosts,
		recentlyViewed,
		recentlyViewedPosts,
		searchTerm,
		seriesSlug,
		tagSlug,
	]);

	const topicGraphNodes = useMemo(
		() =>
			tagOptions.slice(0, 10).map((tag, index) => ({
				...tag,
				level: index < 3 ? 'Core' : index < 7 ? 'Applied' : 'Advanced',
				dependency:
					index < 3
						? null
						: tagOptions[index - 1]?.name ?? tagOptions[0]?.name ?? null,
			})),
		[tagOptions],
	);
	const featuredArticle = filteredPosts[0] ?? initialPosts[0];
	const supportingArticles = filteredPosts.filter((post) => post.slug !== featuredArticle?.slug).slice(0, 4);
	const recentDeepDives = useMemo(
		() => sortPosts(initialPosts, 'created-desc').slice(0, 7),
		[initialPosts],
	);
	const continueArticles = useMemo(() => {
		const savedArticle = savedPath?.readSlugs?.length
			? initialPosts.find((post) => post.slug === savedPath.readSlugs[savedPath.readSlugs.length - 1])
			: null;
		return [
			...(savedArticle ? [savedArticle] : []),
			...recentlyViewedPosts,
			...aiRecommendedPosts,
		]
			.filter((post, index, list) => list.findIndex((item) => item.slug === post.slug) === index)
			.slice(0, 3);
	}, [aiRecommendedPosts, initialPosts, recentlyViewedPosts, savedPath]);
	const curatedCollections = useMemo(
		() =>
			TOPIC_COLLECTIONS.slice(0, 5).map((collection, index) => {
				const tokens = collection.query.toLowerCase().split(/\s+/).filter(Boolean);
				const posts = initialPosts
					.filter((post) => {
						const haystack = `${post.title} ${post.brief ?? ''} ${(post.tags ?? [])
							.flatMap((tag) => [tag.name, tag.slug])
							.join(' ')}`.toLowerCase();
						return tokens.some((token) => haystack.includes(token));
					})
					.slice(0, 4);
				return {
					...collection,
					index,
					posts: posts.length ? posts : initialPosts.slice(index, index + 4),
				};
			}),
		[initialPosts],
	);

	return (
		<AppProvider publication={publication} footerPosts={initialPosts}>
			<Layout>
				<Head>
					<title>Chapters - {publication.title}</title>
					<meta name="description" content={`Browse systems chapters from ${publication.title}`} />
					<meta property="og:title" content={`Chapters - ${publication.title}`} />
					<meta property="og:description" content={`Browse systems chapters from ${publication.title}`} />
					<meta property="og:image" content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)} />
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={`Chapters - ${publication.title}`} />
					<meta property="twitter:description" content={`Browse systems chapters from ${publication.title}`} />
					<meta property="twitter:image" content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)} />
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="mx-auto flex w-full max-w-7xl flex-col gap-14 px-4 py-12 sm:px-5">
						<section className="grid gap-8 lg:grid-cols-[minmax(0,0.9fr)_minmax(320px,0.55fr)] lg:items-end">
							<div>
								<p className="mb-3 text-[10px] font-mono uppercase tracking-[0.24em] text-neutral-400 dark:text-neutral-500">
									Chapters
								</p>
								<h1 className="max-w-4xl text-4xl font-black tracking-tight text-neutral-950 dark:text-neutral-50 md:text-6xl">
									Engineering chapters for understanding systems.
								</h1>
								<p className="mt-4 max-w-3xl text-lg leading-relaxed text-neutral-600 dark:text-neutral-300">
									Distributed systems, AI infrastructure, data structures, and system design explained with calm, production-minded depth.
								</p>
							</div>
							<div className="rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
								<p className="text-xs font-bold uppercase tracking-wide text-neutral-500 dark:text-neutral-400">
									Find a chapter
								</p>
								<div className="relative mt-3">
									<input
										type="text"
										value={searchTerm}
										onChange={(e) => setSearchTerm(e.target.value)}
										onFocus={() => setSearchFocused(true)}
										onBlur={() => setTimeout(() => setSearchFocused(false), 150)}
										placeholder="Search concepts, systems, or tradeoffs"
										className="w-full rounded-xl border border-neutral-200 bg-neutral-50 px-3 py-2.5 text-sm text-neutral-900 outline-none focus:border-blue-400 dark:border-neutral-700 dark:bg-neutral-950 dark:text-neutral-50"
									/>
									{searchFocused && searchPreviewPosts.length > 0 && (
										<div className="absolute left-0 right-0 top-full z-50 mt-2 overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-xl dark:border-neutral-700 dark:bg-neutral-900">
											{searchPreviewPosts.map((post) => (
												<Link
													key={post.id}
													href={`/${post.slug}`}
													onClick={() => rememberPostView(post)}
													className="block border-b border-neutral-100 px-3 py-2.5 last:border-0 hover:bg-neutral-50 dark:border-neutral-800 dark:hover:bg-neutral-800"
												>
													<p className="line-clamp-1 text-sm font-semibold text-neutral-900 dark:text-neutral-50">{post.title}</p>
													<p className="mt-0.5 text-xs text-neutral-400 dark:text-neutral-500">{post.readTimeInMinutes} min read</p>
												</Link>
											))}
										</div>
									)}
								</div>
								<div className="mt-3 flex flex-wrap gap-2">
									{(['all', 'top', 'updated'] as PostListView[]).map((preset) => (
										<button
											key={preset}
											onClick={() =>
												updateQuery({
													view: preset === 'all' ? null : preset,
													sort: DEFAULT_SORT_BY_VIEW[preset],
												})
											}
											className={`rounded-full px-3 py-1.5 text-xs font-bold transition-colors ${
												view === preset
													? 'bg-neutral-950 text-white dark:bg-white dark:text-neutral-950'
													: 'bg-neutral-100 text-neutral-600 hover:text-blue-700 dark:bg-neutral-800 dark:text-neutral-300'
											}`}
										>
											{POST_VIEW_META[preset].label}
										</button>
									))}
								</div>
							</div>
						</section>

						<section>
							<div className="mb-5 flex items-end justify-between gap-4">
								<div>
									<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-400 dark:text-neutral-500">
										Continue reading
									</p>
									<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
										Pick up a chapter
									</h2>
								</div>
								<Link href="/assistant?q=what%20should%20I%20read%20next" className="hidden text-sm font-bold text-blue-600 hover:text-blue-700 dark:text-blue-300 sm:inline">
									Ask AI Mentor
								</Link>
							</div>
							<div className="grid gap-3 md:grid-cols-3">
								{continueArticles.length > 0 ? continueArticles.map((post) => (
									<Link
										key={post.id}
										href={`/${post.slug}`}
										onClick={() => rememberPostView(post)}
										className="group overflow-hidden rounded-2xl border border-neutral-200 bg-white transition hover:border-blue-300 dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-blue-700"
									>
										<Image
											src={resolvePostImage(post)}
											alt={post.title}
											width={420}
											height={220}
											className="aspect-[16/8] w-full object-cover transition-transform group-hover:scale-[1.02]"
										/>
										<div className="p-4">
											<p className="text-sm font-black leading-5 text-neutral-950 dark:text-neutral-50">{post.title}</p>
											<p className="mt-2 line-clamp-2 text-xs leading-relaxed text-neutral-500 dark:text-neutral-400">{post.brief}</p>
										</div>
									</Link>
								)) : (
									<Link href={featuredArticle ? `/${featuredArticle.slug}` : '/posts'} className="group overflow-hidden rounded-2xl border border-neutral-200 bg-white transition hover:border-blue-300 dark:border-neutral-800 dark:bg-neutral-900">
										{featuredArticle ? (
											<Image
												src={resolvePostImage(featuredArticle)}
												alt={featuredArticle.title}
												width={420}
												height={220}
												className="aspect-[16/8] w-full object-cover transition-transform group-hover:scale-[1.02]"
											/>
										) : null}
										<div className="p-4">
											<p className="text-sm font-black text-neutral-950 dark:text-neutral-50">{featuredArticle?.title ?? 'Start with a reader favorite'}</p>
											<p className="mt-2 text-xs leading-relaxed text-neutral-500 dark:text-neutral-400">Begin with a durable chapter, then follow related concepts from there.</p>
										</div>
									</Link>
								)}
							</div>
						</section>

						<section>
							<div className="mb-5">
								<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-400 dark:text-neutral-500">
									Discovery shortcuts
								</p>
								<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
									Move into Discovery
								</h2>
							</div>
							<div className="grid gap-4 lg:grid-cols-5">
								{curatedCollections.map((collection) => (
									<section key={collection.id} className="rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
										<div className="mb-4 h-1.5 w-14 rounded-full bg-blue-500 dark:bg-blue-400" />
										<h3 className="text-sm font-black text-neutral-950 dark:text-neutral-50">{collection.label}</h3>
										<div className="mt-3 space-y-2">
											{collection.posts.slice(0, 3).map((post) => (
												<Link
													key={post.id}
													href={`/${post.slug}`}
													onClick={() => rememberPostView(post)}
													className="block text-xs font-semibold leading-5 text-neutral-600 hover:text-blue-700 dark:text-neutral-300 dark:hover:text-blue-300"
												>
													{post.title}
												</Link>
											))}
										</div>
										<button
											type="button"
											onClick={() => setSearchTerm(collection.query)}
											className="mt-4 text-xs font-black text-blue-600 hover:text-blue-700 dark:text-blue-300"
										>
											Use as filter
										</button>
									</section>
								))}
							</div>
						</section>

						<section>
							<div className="mb-5 flex items-end justify-between gap-4">
								<div>
									<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-400 dark:text-neutral-500">
										Recent chapters
									</p>
									<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
										Editorial reading rhythm
									</h2>
								</div>
								<p className="text-xs font-semibold text-neutral-400 dark:text-neutral-500">
									{filteredPosts.length} chapter{filteredPosts.length === 1 ? '' : 's'}
								</p>
							</div>
							{featuredArticle ? (
								<div className="grid gap-6 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,0.85fr)]">
									<Link
										href={`/${featuredArticle.slug}`}
										onClick={() => rememberPostView(featuredArticle)}
										className="group overflow-hidden rounded-3xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900"
									>
										<Image
											src={resolvePostImage(featuredArticle)}
											alt={featuredArticle.title}
											width={960}
											height={540}
											className="aspect-[16/9] w-full object-cover"
										/>
										<div className="p-5 md:p-6">
											<p className="text-[10px] font-black uppercase tracking-wide text-blue-600 dark:text-blue-300">
												Featured chapter
											</p>
											<h3 className="mt-2 text-2xl font-black leading-tight text-neutral-950 group-hover:text-blue-700 dark:text-neutral-50 dark:group-hover:text-blue-300 md:text-3xl">
												{featuredArticle.title}
											</h3>
											<p className="mt-3 max-w-2xl text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
												{featuredArticle.brief}
											</p>
											<p className="mt-5 text-sm font-bold text-blue-600 dark:text-blue-300">Read chapter</p>
										</div>
									</Link>
									<div className="space-y-3">
										{supportingArticles.map((post) => (
											<Link
												key={post.id}
												href={`/${post.slug}`}
												onClick={() => rememberPostView(post)}
												className="grid gap-3 rounded-2xl border border-neutral-200 bg-white p-4 transition hover:border-blue-300 dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-blue-700 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"
											>
												<span className="flex items-center gap-3">
													<Image
														src={resolvePostImage(post)}
														alt={post.title}
														width={112}
														height={72}
														className="hidden h-[72px] w-[112px] rounded-xl object-cover sm:block"
													/>
													<span>
													<span className="block text-sm font-black text-neutral-950 dark:text-neutral-50">{post.title}</span>
													<span className="mt-1 line-clamp-2 block text-xs leading-relaxed text-neutral-500 dark:text-neutral-400">{post.brief}</span>
													</span>
												</span>
												<span className="text-xs font-bold text-neutral-400">{post.readTimeInMinutes} min</span>
											</Link>
										))}
									</div>
								</div>
							) : null}
						</section>

						<section>
							<div className="rounded-3xl border border-neutral-200 bg-neutral-50 p-5 dark:border-neutral-800 dark:bg-neutral-900/60">
								<div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
									<div>
										<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-400 dark:text-neutral-500">
											Systems exploration
										</p>
										<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
											Follow the concept continuity
										</h2>
									</div>
									<Link href="/discover#topic-collections" className="text-sm font-bold text-blue-600 hover:text-blue-700 dark:text-blue-300">
										View related systems
									</Link>
								</div>
								<div className="mt-6 flex snap-x gap-3 overflow-x-auto pb-2">
									{topicGraphNodes.slice(0, 5).map((node, index) => (
										<button
											key={node.slug}
											type="button"
											onClick={() => updateQuery({ tag: node.slug })}
											className="flex min-w-[180px] snap-start items-center gap-3 rounded-2xl border border-neutral-200 bg-white px-4 py-3 text-left transition hover:border-blue-300 dark:border-neutral-800 dark:bg-neutral-950 dark:hover:border-blue-700"
										>
											<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-neutral-100 text-xs font-black text-neutral-500 dark:bg-neutral-800 dark:text-neutral-300">
												{index + 1}
											</span>
											<span>
												<span className="block text-sm font-black text-neutral-950 dark:text-neutral-50">{node.name}</span>
												<span className="mt-0.5 block text-[11px] text-neutral-500 dark:text-neutral-400">{node.count} chapters</span>
											</span>
										</button>
									))}
								</div>
							</div>
						</section>

						<details className="rounded-3xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
							<summary className="cursor-pointer list-none text-sm font-black text-neutral-950 dark:text-neutral-50">
								Browse all chapters
							</summary>
							<div className="mt-5 flex flex-col gap-5">
								<div className="flex flex-wrap gap-2">
									{visibleTagOptions.map((tag) => (
										<button
											key={tag.slug}
											onClick={() => updateQuery({ tag: tag.slug })}
											className={`rounded-full px-3 py-1.5 text-xs font-bold transition-colors ${
												tagSlug === tag.slug
													? 'bg-blue-600 text-white'
													: 'bg-neutral-100 text-neutral-600 dark:bg-neutral-800 dark:text-neutral-300'
											}`}
										>
											{tag.name}
										</button>
									))}
									{activeFilterCount > 0 ? (
										<button onClick={clearFilters} className="rounded-full px-3 py-1.5 text-xs font-bold text-blue-600">
											Clear filters
										</button>
									) : null}
								</div>
								{filteredPosts.length > 0 ? (
									<>
										<div className="divide-y divide-neutral-100 dark:divide-neutral-800">
											{pagedPosts.map((post) => (
												<Link
													key={post.id}
													href={`/${post.slug}`}
													onClick={() => rememberPostView(post)}
													className="grid gap-2 py-3 md:grid-cols-[minmax(0,1fr)_120px] md:items-center"
												>
													<span className="flex items-center gap-3">
														<Image
															src={resolvePostImage(post)}
															alt={post.title}
															width={96}
															height={64}
															className="hidden h-16 w-24 rounded-lg object-cover sm:block"
														/>
														<span>
														<span className="block text-sm font-bold text-neutral-950 dark:text-neutral-50">{post.title}</span>
														<span className="mt-1 line-clamp-1 block text-xs text-neutral-500 dark:text-neutral-400">{post.brief}</span>
														</span>
													</span>
													<span className="text-xs font-semibold text-neutral-400 md:text-right">{post.readTimeInMinutes} min read</span>
												</Link>
											))}
										</div>
										<Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={handlePageChange} />
									</>
								) : (
									<div className="rounded-2xl border border-dashed border-neutral-300 px-6 py-10 text-center dark:border-neutral-700">
										<h2 className="text-lg font-semibold text-neutral-900 dark:text-neutral-50">No chapters match the current filters</h2>
										{searchTerm.trim().length > 2 ? (
											<Link
												href={`/assistant?q=${encodeURIComponent(`Explain ${searchTerm.trim()} and suggest related systems chapters`)}`}
												className="mt-4 inline-flex rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white"
											>
												Ask Mentor
											</Link>
										) : null}
									</div>
								)}
							</div>
						</details>

						<section className="rounded-3xl border border-neutral-200 bg-neutral-950 p-6 text-white dark:border-neutral-800">
							<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-blue-200">
								Continue
							</p>
							<p className="mt-2 max-w-3xl text-2xl font-black tracking-tight">
								Read one chapter, then follow the next related system.
							</p>
							<Link href="/discover#topic-collections" className="mt-5 inline-flex rounded-xl bg-white px-4 py-2 text-sm font-bold text-neutral-950">
								Open Discovery
							</Link>
						</section>
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}

	const allPosts = (publication.posts.edges ?? []).map((edge) => edge.node);
	let cursor = publication.posts.pageInfo.endCursor;
	let hasNextPage = !!publication.posts.pageInfo.hasNextPage;

	while (hasNextPage && cursor) {
		const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
		);

		if (!next.publication) {
			break;
		}

		allPosts.push(...next.publication.posts.edges.map((edge) => edge.node));
		cursor = next.publication.posts.pageInfo.endCursor;
		hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
	}

	return {
		props: {
			publication,
			initialPosts: allPosts,
		},
		revalidate: CONTENT_REVALIDATE_SECONDS,
	};
};
