import { resizeImage } from '@starter-kit/utils/image';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { format } from 'date-fns';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { Pagination } from '../components/pagination';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import {
	filterPosts,
	getPostsForView,
	parsePostListSort,
	parsePostListView,
	PostListSort,
	sortPosts,
} from '../lib/post-listing';
import { CONTENT_REVALIDATE_SECONDS } from '../lib/cache-constants';
import { formatTagName } from '../utils/format';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
const PAGE_SIZE = 8;
const RECENTLY_VIEWED_KEY = 'aa:recently-viewed-posts';
const FALLBACK_POST_IMAGE = '/assets/blog/post-fallback.svg';

type RecentlyViewedItem = {
	slug: string;
	title: string;
	seenAt: number;
};

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
};

type QueryUpdates = Partial<Record<'view' | 'sort' | 'tag' | 'series', string | null>>;

type IconName =
	| 'article'
	| 'bookmark'
	| 'calendar'
	| 'clock'
	| 'eye'
	| 'mail'
	| 'search'
	| 'share';

const getQueryValue = (value: string | string[] | undefined) =>
	typeof value === 'string' && value.length > 0 ? value : '';

const buildTagOptions = (posts: PostFragment[]) => {
	const tags = new Map<string, { slug: string; name: string; count: number }>();

	posts.forEach((post) => {
		post.tags?.forEach((tag) => {
			const existing = tags.get(tag.slug);
			tags.set(tag.slug, {
				slug: tag.slug,
				name: formatTagName(tag.name),
				count: (existing?.count ?? 0) + 1,
			});
		});
	});

	return [...tags.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
};

const getVisibleOptions = <T extends { slug: string }>(
	options: T[],
	selectedSlug: string,
	limit: number,
) => {
	const topOptions = options.slice(0, limit);
	if (!selectedSlug || topOptions.some((option) => option.slug === selectedSlug)) {
		return topOptions;
	}

	const selected = options.find((option) => option.slug === selectedSlug);
	return selected ? [selected, ...topOptions.slice(0, Math.max(limit - 1, 0))] : topOptions;
};

const readRecentlyViewed = (): RecentlyViewedItem[] => {
	if (typeof window === 'undefined') return [];
	try {
		const raw = localStorage.getItem(RECENTLY_VIEWED_KEY);
		if (!raw) return [];
		return JSON.parse(raw) as RecentlyViewedItem[];
	} catch {
		return [];
	}
};

const resolvePostImage = (post: Pick<PostFragment, 'coverImage'>) =>
	post.coverImage?.url?.trim()
		? resizeImage(post.coverImage.url, { w: 960, h: 540, c: 'thumb' })
		: FALLBACK_POST_IMAGE;

const formatPostDate = (date: string) => {
	try {
		return format(new Date(date), 'MMM d, yyyy');
	} catch {
		return date.slice(0, 10);
	}
};

const formatViews = (views: number | null | undefined) => {
	if (!views || views <= 0) return null;
	if (views >= 1000000) return `${(views / 1000000).toFixed(1).replace('.0', '')}M views`;
	if (views >= 1000) return `${(views / 1000).toFixed(1).replace('.0', '')}K views`;
	return `${views.toLocaleString()} views`;
};

const SORT_OPTIONS: Array<{ value: PostListSort; label: string }> = [
	{ value: 'created-desc', label: 'Latest' },
	{ value: 'popular-desc', label: 'Popular' },
	{ value: 'updated-desc', label: 'Recently updated' },
];

const Icon = ({ name, className = 'h-4 w-4' }: { name: IconName; className?: string }) => {
	const paths: Record<IconName, JSX.Element> = {
		article: (
			<>
				<path d="M7 3h7l4 4v14H7z" />
				<path d="M14 3v5h4" />
				<path d="M10 12h5M10 16h5" />
			</>
		),
		bookmark: <path d="M7 4h10v17l-5-3-5 3z" />,
		calendar: (
			<>
				<path d="M5 6h14v14H5z" />
				<path d="M8 4v4M16 4v4M5 10h14" />
			</>
		),
		clock: (
			<>
				<circle cx="12" cy="12" r="8" />
				<path d="M12 8v5l3 2" />
			</>
		),
		eye: (
			<>
				<path d="M3 12s3-6 9-6 9 6 9 6-3 6-9 6-9-6-9-6z" />
				<circle cx="12" cy="12" r="2.5" />
			</>
		),
		mail: (
			<>
				<path d="M4 6h16v12H4z" />
				<path d="m4 7 8 6 8-6" />
			</>
		),
		search: (
			<>
				<circle cx="10.5" cy="10.5" r="6.5" />
				<path d="m16 16 4 4" />
			</>
		),
		share: (
			<>
				<circle cx="18" cy="5" r="3" />
				<circle cx="6" cy="12" r="3" />
				<circle cx="18" cy="19" r="3" />
				<path d="m8.7 10.7 6.6-4.4M8.7 13.3l6.6 4.4" />
			</>
		),
	};

	return (
		<svg
			className={className}
			fill="none"
			stroke="currentColor"
			strokeLinecap="round"
			strokeLinejoin="round"
			strokeWidth={2}
			viewBox="0 0 24 24"
			aria-hidden="true"
		>
			{paths[name]}
		</svg>
	);
};

const BlogHeroGraphic = () => (
	<div className="relative hidden min-h-[240px] overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_center,rgba(37,99,235,0.12),transparent_58%)] lg:block">
		<div className="absolute inset-0 bg-[linear-gradient(rgba(59,130,246,0.12)_1px,transparent_1px),linear-gradient(90deg,rgba(59,130,246,0.12)_1px,transparent_1px)] bg-[size:28px_28px] opacity-40" />
		<div className="absolute left-[31%] top-[28%] rounded-xl border border-blue-100 bg-white px-4 py-3 text-xs font-bold text-slate-700 shadow-sm">
			System Design
		</div>
		<div className="absolute left-[24%] top-[58%] rounded-xl border border-violet-100 bg-white px-4 py-3 text-xs font-bold text-slate-700 shadow-sm">
			Best Practices
		</div>
		<div className="absolute right-[7%] top-[24%] rounded-xl border border-emerald-100 bg-white px-4 py-3 text-xs font-bold text-slate-700 shadow-sm">
			Architecture
		</div>
		<div className="absolute right-[9%] bottom-[19%] rounded-xl border border-orange-100 bg-white px-4 py-3 text-xs font-bold text-slate-700 shadow-sm">
			Tutorials
		</div>
		<div className="absolute left-1/2 top-1/2 h-40 w-40 -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-blue-100 bg-white p-5 shadow-xl shadow-blue-100/60">
			<div className="mb-4 flex items-center gap-3">
				<span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600">
					<Icon name="article" className="h-5 w-5" />
				</span>
				<span className="h-3 flex-1 rounded-full bg-slate-200" />
			</div>
			<div className="h-12 rounded-xl bg-gradient-to-br from-blue-100 to-slate-100" />
			<div className="mt-4 space-y-2">
				<span className="block h-2 rounded-full bg-slate-200" />
				<span className="block h-2 w-5/6 rounded-full bg-slate-200" />
				<span className="block h-2 w-2/3 rounded-full bg-slate-200" />
			</div>
		</div>
	</div>
);

export default function AllPostsPage({ publication, initialPosts }: Props) {
	const router = useRouter();
	const [searchTerm, setSearchTerm] = useState('');
	const [recentlyViewed, setRecentlyViewed] = useState<RecentlyViewedItem[]>([]);

	const view = parsePostListView(router.query.view);
	const sort = parsePostListSort(router.query.sort, view);
	const tagSlug = getQueryValue(router.query.tag);
	const seriesSlug = getQueryValue(router.query.series);

	const updateQuery = (updates: QueryUpdates) => {
		const nextState = {
			view,
			sort,
			tag: tagSlug,
			series: seriesSlug,
			...updates,
		};

		const nextQuery = Object.fromEntries(
			Object.entries(nextState).filter(([, value]) => value && value.length > 0),
		);

		router.replace({ pathname: '/posts', query: nextQuery }, undefined, {
			shallow: true,
			scroll: false,
		});
	};

	const clearFilters = () => {
		setSearchTerm('');
		router.replace('/posts', undefined, { shallow: true, scroll: false });
	};

	useEffect(() => {
		setRecentlyViewed(readRecentlyViewed());
	}, []);

	const rememberPostView = (post: PostFragment) => {
		if (typeof window === 'undefined') return;
		try {
			const next = [
				{ slug: post.slug, title: post.title, seenAt: Date.now() },
				...readRecentlyViewed().filter((entry) => entry.slug !== post.slug),
			].slice(0, 8);
			localStorage.setItem(RECENTLY_VIEWED_KEY, JSON.stringify(next));
			setRecentlyViewed(next);
		} catch {}
	};

	const tagOptions = useMemo(() => buildTagOptions(initialPosts), [initialPosts]);
	const visibleTagOptions = useMemo(
		() => getVisibleOptions(tagOptions, tagSlug, 7),
		[tagOptions, tagSlug],
	);
	const filteredPosts = useMemo(() => {
		const basePosts = getPostsForView(initialPosts, view);
		const queryFilteredPosts = filterPosts(basePosts, {
			searchTerm,
			tagSlug: tagSlug || null,
			seriesSlug: seriesSlug || null,
			createdFrom: '',
			createdTo: '',
			updatedFrom: '',
			updatedTo: '',
		});

		return sortPosts(queryFilteredPosts, sort);
	}, [initialPosts, searchTerm, seriesSlug, sort, tagSlug, view]);

	const recentlyViewedPosts = useMemo(
		() =>
			recentlyViewed
				.map((entry) => initialPosts.find((post) => post.slug === entry.slug))
				.filter((post): post is PostFragment => Boolean(post))
				.slice(0, 3),
		[initialPosts, recentlyViewed],
	);
	const popularPosts = useMemo(
		() => sortPosts(initialPosts, 'popular-desc').filter((post) => (post.views ?? 0) > 0).slice(0, 4),
		[initialPosts],
	);
	const featuredArticle = filteredPosts[0] ?? initialPosts[0];
	const listPosts = filteredPosts.filter((post) => post.slug !== featuredArticle?.slug);
	const activeFilterCount = [searchTerm, tagSlug, seriesSlug].filter(Boolean).length;

	const [currentPage, setCurrentPage] = useState(1);

	useEffect(() => {
		setCurrentPage(1);
	}, [filteredPosts.length, view, sort, tagSlug, seriesSlug, searchTerm]);

	const totalPages = Math.ceil(listPosts.length / PAGE_SIZE);
	const pagedPosts = listPosts.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

	const handlePageChange = (page: number) => {
		setCurrentPage(page);
		window.scrollTo({ top: 360, behavior: 'smooth' });
	};

	const activeTagName = tagOptions.find((tag) => tag.slug === tagSlug)?.name;

	return (
		<AppProvider publication={publication} footerPosts={initialPosts}>
			<Layout>
				<Head>
					<title>Blog - {publication.title}</title>
					<meta
						name="description"
						content={`In-depth articles, tutorials, and engineering insights from ${publication.title}.`}
					/>
					<meta property="og:title" content={`Blog - ${publication.title}`} />
					<meta
						property="og:description"
						content={`In-depth articles, tutorials, and engineering insights from ${publication.title}.`}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={`Blog - ${publication.title}`} />
					<meta
						property="twitter:description"
						content={`In-depth articles, tutorials, and engineering insights from ${publication.title}.`}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<main className="bg-white text-slate-950">
						<section className="border-b border-slate-200 bg-gradient-to-b from-white to-slate-50">
							<div className="mx-auto grid w-full max-w-[1440px] gap-8 px-5 py-12 md:px-8 md:py-16 lg:grid-cols-[minmax(0,0.72fr)_minmax(420px,0.78fr)] lg:items-center">
								<div>
									<h1 className="max-w-3xl text-4xl font-black tracking-normal text-slate-950 md:text-5xl">
										Engineering Insights.
										<span className="block text-blue-600">Shared for Growth.</span>
									</h1>
									<p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">
										In-depth articles, tutorials and insights on system design, architecture, coding and everything in between.
									</p>
									<div className="mt-8 flex flex-wrap gap-3">
										<a
											href="#articles"
											className="inline-flex h-12 items-center gap-3 rounded-lg bg-blue-600 px-6 text-sm font-bold text-white shadow-lg shadow-blue-200 transition hover:bg-blue-700"
										>
											Explore Articles
											<span aria-hidden="true">-&gt;</span>
										</a>
										<a
											href="#newsletter"
											className="inline-flex h-12 items-center gap-3 rounded-lg border border-slate-300 bg-white px-6 text-sm font-bold text-slate-950 transition hover:border-blue-300 hover:text-blue-700"
										>
											<Icon name="bookmark" />
											Subscribe to Newsletter
										</a>
									</div>
								</div>
								<BlogHeroGraphic />
							</div>
						</section>

						<section id="articles" className="mx-auto w-full max-w-[1440px] px-5 py-8 md:px-8">
							<div className="mb-4 flex flex-col gap-4 border-b border-slate-200 pb-2 lg:flex-row lg:items-center lg:justify-between">
								<div className="flex gap-6 overflow-x-auto">
									<button
										type="button"
										onClick={() => updateQuery({ tag: null })}
										className={`h-10 shrink-0 border-b-2 px-2 text-sm font-bold transition ${
											!tagSlug
												? 'border-blue-600 text-blue-600'
												: 'border-transparent text-slate-700 hover:text-blue-600'
										}`}
									>
										All Articles
									</button>
									{visibleTagOptions.map((tag) => (
										<button
											key={tag.slug}
											type="button"
											onClick={() => updateQuery({ tag: tag.slug })}
											className={`h-10 shrink-0 border-b-2 px-2 text-sm font-bold transition ${
												tagSlug === tag.slug
													? 'border-blue-600 text-blue-600'
													: 'border-transparent text-slate-700 hover:text-blue-600'
											}`}
										>
											{tag.name}
										</button>
									))}
								</div>
								<div className="flex flex-wrap items-center gap-2">
									<label className="relative min-w-[220px] flex-1 lg:w-[260px] lg:flex-none">
										<span className="sr-only">Search articles</span>
										<Icon name="search" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
										<input
											type="search"
											value={searchTerm}
											onChange={(event) => setSearchTerm(event.target.value)}
											placeholder="Search articles..."
											className="h-11 w-full rounded-lg border border-slate-300 bg-white pl-10 pr-3 text-sm text-slate-900 outline-none transition focus:border-blue-500"
										/>
									</label>
									<select
										value={sort}
										onChange={(event) => {
											const nextSort = event.target.value as PostListSort;
											updateQuery({
												sort: nextSort === 'created-desc' ? null : nextSort,
												view: nextSort === 'popular-desc' ? 'top' : nextSort === 'updated-desc' ? 'updated' : null,
											});
										}}
										className="h-11 rounded-lg border border-slate-300 bg-white px-4 text-sm font-bold text-slate-900 outline-none transition focus:border-blue-500"
									>
										{SORT_OPTIONS.map((option) => (
											<option key={option.value} value={option.value}>
												{option.label}
											</option>
										))}
									</select>
								</div>
							</div>

							{activeFilterCount > 0 ? (
								<div className="mb-5 flex flex-wrap items-center gap-2 text-sm text-slate-600">
									<span>
										Showing {filteredPosts.length} article{filteredPosts.length === 1 ? '' : 's'}
										{activeTagName ? ` in ${activeTagName}` : ''}
									</span>
									<button type="button" onClick={clearFilters} className="font-bold text-blue-600">
										Clear filters
									</button>
								</div>
							) : null}

							<div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
								<div className="space-y-4">
									{featuredArticle ? (
										<Link
											href={`/${featuredArticle.slug}`}
											onClick={() => rememberPostView(featuredArticle)}
											className="grid overflow-hidden rounded-lg border border-slate-200 bg-white p-3 shadow-sm transition hover:border-blue-300 hover:shadow-md md:grid-cols-[minmax(260px,0.44fr)_minmax(0,1fr)]"
										>
											<Image
												src={resolvePostImage(featuredArticle)}
												alt={featuredArticle.title}
												width={520}
												height={320}
												className="h-full min-h-[220px] w-full rounded-md object-cover"
											/>
											<div className="flex flex-col p-4 md:p-6">
												<span className="mb-3 w-fit rounded-md bg-blue-50 px-2 py-1 text-xs font-black uppercase text-blue-600">
													Featured
												</span>
												<h2 className="text-2xl font-black leading-tight text-slate-950">
													{featuredArticle.title}
												</h2>
												<p className="mt-3 line-clamp-3 text-base leading-7 text-slate-600">
													{featuredArticle.brief}
												</p>
												<div className="mt-4 flex flex-wrap gap-2">
													{featuredArticle.tags?.slice(0, 3).map((tag) => (
														<span key={tag.slug} className="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">
															{formatTagName(tag.name)}
														</span>
													))}
												</div>
												<ArticleMeta post={featuredArticle} className="mt-auto pt-5" />
											</div>
										</Link>
									) : null}

									{pagedPosts.map((post) => (
										<Link
											key={post.id}
											href={`/${post.slug}`}
											onClick={() => rememberPostView(post)}
											className="grid gap-4 rounded-lg border border-slate-200 bg-white p-3 shadow-sm transition hover:border-blue-300 hover:shadow-md sm:grid-cols-[minmax(180px,0.32fr)_minmax(0,1fr)]"
										>
											<Image
												src={resolvePostImage(post)}
												alt={post.title}
												width={360}
												height={210}
												className="h-full min-h-[138px] w-full rounded-md object-cover"
											/>
											<div className="flex min-w-0 flex-col py-1 pr-1">
												<h3 className="text-xl font-black leading-snug text-slate-950">
													{post.title}
												</h3>
												<p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">
													{post.brief}
												</p>
												<div className="mt-3 flex flex-wrap gap-2">
													{post.tags?.slice(0, 3).map((tag) => (
														<span key={tag.slug} className="rounded-md bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">
															{formatTagName(tag.name)}
														</span>
													))}
												</div>
												<ArticleMeta post={post} className="mt-auto pt-3" />
											</div>
										</Link>
									))}

									{filteredPosts.length === 0 ? (
										<div className="rounded-lg border border-dashed border-slate-300 bg-white px-6 py-14 text-center">
											<h2 className="text-xl font-black text-slate-950">No articles match the current filters</h2>
											<p className="mt-2 text-sm text-slate-600">
												Try a different topic, search term, or sort option.
											</p>
										</div>
									) : null}

									<Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={handlePageChange} />
								</div>

								<aside className="space-y-4 lg:sticky lg:top-24 lg:self-start">
									<section id="newsletter" className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
										<div className="flex gap-4">
											<span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-blue-600">
												<Icon name="mail" className="h-6 w-6" />
											</span>
											<div>
												<p className="text-sm font-bold text-slate-700">Newsletter</p>
												<h2 className="mt-1 text-2xl font-black text-slate-950">Stay in the loop</h2>
												<p className="mt-2 text-sm leading-6 text-slate-600">
													Get engineering articles and interview prep notes delivered to your inbox.
												</p>
											</div>
										</div>
										<form className="mt-5 flex gap-2" action="#" method="post">
											<label className="sr-only" htmlFor="newsletter-email">
												Email address
											</label>
											<input
												id="newsletter-email"
												type="email"
												placeholder="Enter your email"
												className="h-11 min-w-0 flex-1 rounded-lg border border-slate-300 px-4 text-sm outline-none transition focus:border-blue-500"
											/>
											<button type="submit" className="h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold text-white transition hover:bg-blue-700">
												Subscribe
											</button>
										</form>
									</section>

									<section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
										<div className="mb-4 flex items-center justify-between gap-3">
											<h2 className="text-lg font-black text-slate-950">Popular Topics</h2>
											<span className="text-xs font-bold text-slate-400">By article count</span>
										</div>
										<div className="space-y-3">
											{tagOptions.slice(0, 5).map((tag) => (
												<button
													key={tag.slug}
													type="button"
													onClick={() => updateQuery({ tag: tag.slug })}
													className="flex w-full items-center justify-between gap-4 text-left text-sm"
												>
													<span className="font-bold text-slate-800">{tag.name}</span>
													<span className="text-slate-500">
														{tag.count} article{tag.count === 1 ? '' : 's'}
													</span>
												</button>
											))}
										</div>
										<Link href="/learn" className="mt-5 inline-flex text-sm font-bold text-blue-600">
											View all topics -&gt;
										</Link>
									</section>

									{popularPosts.length > 0 ? (
										<section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
											<h2 className="text-lg font-black text-slate-950">Popular Reads</h2>
											<div className="mt-4 space-y-4">
												{popularPosts.map((post, index) => (
													<Link
														key={post.id}
														href={`/${post.slug}`}
														onClick={() => rememberPostView(post)}
														className="grid grid-cols-[24px_minmax(0,1fr)_auto] gap-3 text-sm"
													>
														<span className="flex h-6 w-6 items-center justify-center rounded-md bg-slate-100 text-xs font-black text-slate-600">
															{index + 1}
														</span>
														<span className="line-clamp-2 font-bold leading-5 text-slate-900">
															{post.title}
														</span>
														<span className="text-xs text-slate-500">{formatViews(post.views)}</span>
													</Link>
												))}
											</div>
											<button
												type="button"
												onClick={() => updateQuery({ view: 'top', sort: 'popular-desc' })}
												className="mt-5 inline-flex text-sm font-bold text-blue-600"
											>
												View popular articles -&gt;
											</button>
										</section>
									) : null}

									{recentlyViewedPosts.length > 0 ? (
										<section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
											<h2 className="text-lg font-black text-slate-950">Recently Viewed</h2>
											<div className="mt-4 space-y-3">
												{recentlyViewedPosts.map((post) => (
													<Link
														key={post.id}
														href={`/${post.slug}`}
														onClick={() => rememberPostView(post)}
														className="block text-sm font-bold leading-5 text-slate-800 hover:text-blue-600"
													>
														{post.title}
													</Link>
												))}
											</div>
										</section>
									) : null}
								</aside>
							</div>
						</section>
					</main>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

const ArticleMeta = ({ post, className = '' }: { post: PostFragment; className?: string }) => {
	const views = formatViews(post.views);

	return (
		<div className={`flex flex-wrap items-center gap-x-4 gap-y-2 text-xs font-semibold text-slate-500 ${className}`}>
			<span className="inline-flex items-center gap-1.5">
				<Icon name="calendar" className="h-3.5 w-3.5" />
				{formatPostDate(post.publishedAt)}
			</span>
			<span className="inline-flex items-center gap-1.5">
				<Icon name="clock" className="h-3.5 w-3.5" />
				{post.readTimeInMinutes} min read
			</span>
			{views ? (
				<span className="inline-flex items-center gap-1.5">
					<Icon name="eye" className="h-3.5 w-3.5" />
					{views}
				</span>
			) : null}
		</div>
	);
};

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}

	const allPosts = (publication.posts.edges ?? []).map((edge) => edge.node);
	let cursor = publication.posts.pageInfo.endCursor;
	let hasNextPage = !!publication.posts.pageInfo.hasNextPage;

	while (hasNextPage && cursor) {
		const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
		);

		if (!next.publication) {
			break;
		}

		allPosts.push(...next.publication.posts.edges.map((edge) => edge.node));
		cursor = next.publication.posts.pageInfo.endCursor;
		hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
	}

	return {
		props: {
			publication,
			initialPosts: allPosts,
		},
		revalidate: CONTENT_REVALIDATE_SECONDS,
	};
};
