import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState, useMemo } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function AllPostsPage({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(
		initialPosts.sort((a, b) => {
			const dateA = new Date(a.publishedAt || 0).getTime();
			const dateB = new Date(b.publishedAt || 0).getTime();
			return dateB - dateA;
		})
	);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);

	const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
	const [selectedSeries, setSelectedSeries] = useState<string | null>(null);

	const categories = useMemo(() => {
		const map = new Map<string, string>();
		posts.forEach((p) => {
			(p.tags ?? []).forEach((t) => {
				if (t && t.slug && !map.has(t.slug)) map.set(t.slug, t.name ?? t.slug);
			});
		});
		return Array.from(map.entries())
			.map(([slug, name]) => ({ slug, name }))
			.sort((a, b) => a.name.localeCompare(b.name));
	}, [posts]);

	const seriesList = useMemo(() => {
		const map = new Map<string, string>();
		posts.forEach((p) => {
			const s = p.series;
			if (Array.isArray(s)) {
				s.forEach((item) => {
					if (item && item.slug && !map.has(item.slug)) map.set(item.slug, item.name ?? item.slug);
				});
			} else if (s && (s as any).slug) {
				const slug = (s as any).slug;
				if (!map.has(slug)) map.set(slug, (s as any).name ?? slug);
			}
		});
		return Array.from(map.entries())
			.map(([slug, name]) => ({ slug, name }))
			.sort((a, b) => a.name.localeCompare(b.name));
	}, [posts]);

	const filteredPosts = useMemo(() => {
		return posts.filter((post) => {
			if (selectedCategory) {
				const has = (post.tags ?? []).some((t) => t && (t.slug === selectedCategory || t.name === selectedCategory));
				if (!has) return false;
			}
			if (selectedSeries) {
				const s = post.series;
				let has = false;
				if (Array.isArray(s)) {
					has = s.some((item) => item && (item.slug === selectedSeries || item.name === selectedSeries));
				} else if (s && ((s as any).slug === selectedSeries || (s as any).name === selectedSeries)) {
					has = true;
				}
				if (!has) return false;
			}
			return true;
		});
	}, [posts, selectedCategory, selectedSeries]);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		const combined = [...posts, ...newPosts].sort((a, b) => {
			const dateA = new Date(a.publishedAt || 0).getTime();
			const dateB = new Date(b.publishedAt || 0).getTime();
			return dateB - dateA;
		});
		setPosts(combined);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};
	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>All Posts - {publication.title}</title>
					<meta
						name="description"
						content={`All posts from ${publication.title}`}
					/>
					<meta property="og:title" content={`All Posts - ${publication.title}`} />
					<meta
						property="og:description"
						content={`All posts from ${publication.title}`}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={`All Posts - ${publication.title}`} />
					<meta
						property="twitter:description"
						content={`All posts from ${publication.title}`}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-6xl mx-auto w-full px-5 flex flex-col gap-0">
						<section className="w-full py-12">
							<div className="mb-8">
								<h1 className="text-4xl md:text-5xl font-bold text-neutral-900 dark:text-neutral-50 mb-4">
									All Posts
								</h1>
								<p className="text-lg text-neutral-600 dark:text-neutral-300">
									Browse every article, filter by category or series.
								</p>
							</div>
							<div className="flex flex-col md:flex-row items-start md:items-center gap-4 mb-8 p-4 rounded-lg border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900">
								<div className="flex items-center gap-2">
									<label className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Category</label>
									<select
										value={selectedCategory ?? ''}
										onChange={(e) => setSelectedCategory(e.target.value || null)}
										className="rounded-lg border border-neutral-200 dark:border-neutral-700 px-3 py-2 text-sm bg-white dark:bg-neutral-800 text-neutral-900 dark:text-neutral-50 focus:outline-none focus:ring-2 focus:ring-blue-500"
									>
										<option value="">All</option>
										{categories.map((c) => (
											<option key={c.slug} value={c.slug}>
												{c.name}
											</option>
										))}
									</select>
								</div>
								<div className="flex items-center gap-2">
									<label className="text-sm font-medium text-neutral-700 dark:text-neutral-300">Series</label>
									<select
										value={selectedSeries ?? ''}
										onChange={(e) => setSelectedSeries(e.target.value || null)}
										className="rounded-lg border border-neutral-200 dark:border-neutral-700 px-3 py-2 text-sm bg-white dark:bg-neutral-800 text-neutral-900 dark:text-neutral-50 focus:outline-none focus:ring-2 focus:ring-blue-500"
									>
										<option value="">All</option>
										{seriesList.map((s) => (
											<option key={s.slug} value={s.slug}>
												{s.name}
											</option>
										))}
									</select>
								</div>
								<button
									onClick={() => {
										setSelectedCategory(null);
										setSelectedSeries(null);
									}}
									className="inline-flex items-center gap-2 px-3 py-2 text-sm rounded-lg border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-800 text-neutral-700 dark:text-neutral-300 hover:bg-neutral-100 dark:hover:bg-neutral-700 transition-colors"
								>
									Clear filters
								</button>
								{(selectedCategory || selectedSeries) && (
									<span className="text-sm text-neutral-500 dark:text-neutral-400 md:ml-auto">
										{filteredPosts.length} post{filteredPosts.length !== 1 ? 's' : ''} found
									</span>
								)}
							</div>
							{filteredPosts.length > 0 ? (
								<MinimalPosts context="home" posts={filteredPosts} />
							) : (
								<p className="text-neutral-600 dark:text-neutral-400 py-8 text-center">
									No posts match the selected filters.
								</p>
							)}
							{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
								<div className="mt-10 flex justify-center">
									<button
										onClick={loadMore}
										className="px-6 py-2.5 text-sm font-medium rounded-lg border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors"
									>
										Load more posts
									</button>
								</div>
							)}
							{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
								<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
							)}
						</section>
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
