import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { resizeImage } from '@starter-kit/utils/image';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { PersonalHeader } from '../components/personal-theme-header';
import { CONTENT_REVALIDATE_SECONDS } from '../lib/cache-constants';
import {
	AllSeriesByPublicationDocument,
	AllSeriesByPublicationQuery,
	AllSeriesByPublicationQueryVariables,
	PublicationFragment,
	PostFragment,
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
const RECENTLY_VIEWED_KEY = 'aa:recently-viewed-posts';
const FALLBACK_POST_IMAGE = '/assets/blog/post-fallback.svg';

type SeriesPost = {
	slug: string;
	title: string;
	coverImage: string | null;
};

type Series = {
	id: string;
	name: string;
	slug: string;
	description: string;
	coverImage: string | null;
	postCount: number;
	totalReadTime: number;
	posts: SeriesPost[];
};

type Props = {
	publication: PublicationFragment;
	series: Series[];
	footerPosts: PostFragment[];
};

type RecentlyViewedItem = {
	slug: string;
	title: string;
	seenAt: number;
};

const FEATURED_SERIES = [
	'system-design-interview-prep',
	'llm-engineering',
	'distributed-systems',
	'modern-java',
	'vector-databases',
];

const readRecentlyViewed = (): RecentlyViewedItem[] => {
	if (typeof window === 'undefined') return [];
	try {
		const raw = localStorage.getItem(RECENTLY_VIEWED_KEY);
		if (!raw) return [];
		return JSON.parse(raw) as RecentlyViewedItem[];
	} catch {
		return [];
	}
};

const formatDuration = (minutes: number) => {
	if (minutes <= 0) return '';
	const hours = Math.floor(minutes / 60);
	const mins = minutes % 60;
	if (hours <= 0) return `${mins} min`;
	return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
};

const resolveBookImage = (s: Series, size: { w: number; h: number }) => {
	const source = s.coverImage || s.posts.find((post) => post.coverImage)?.coverImage;
	return source ? resizeImage(source, { ...size, c: 'thumb' }) : FALLBACK_POST_IMAGE;
};

const getBookOutcome = (s: Series) => {
	const text = `${s.name} ${s.description}`.toLowerCase();
	if (/kafka/.test(text)) return 'Understand Kafka from partitions and brokers through delivery guarantees.';
	if (/distributed|consensus|replication/.test(text)) return 'Build intuition for coordination, consistency, failure, and recovery.';
	if (/vector|embedding|rag/.test(text)) return 'Learn how semantic retrieval systems are modeled, queried, and operated.';
	if (/java|jvm|spring/.test(text)) return 'Move through modern Java runtime behavior and production design choices.';
	if (/system design|hld|interview/.test(text)) return 'Practice turning ambiguous requirements into durable architecture decisions.';
	if (/llm|agent|ai/.test(text)) return 'Connect model behavior, agent design, evaluation, and production guardrails.';
	return s.description || `Build progressive understanding of ${s.name}.`;
};

const getFeaturedSeries = (series: Series[]) => {
	const bySlug = new Map(series.map((s) => [s.slug, s]));
	const curated = FEATURED_SERIES.map((slug) => bySlug.get(slug)).filter((s): s is Series => Boolean(s));
	const remaining = series.filter((s) => !curated.some((item) => item.id === s.id));
	return [...curated, ...remaining].slice(0, Math.min(5, series.length));
};

const ContinueBook = ({ series }: { series: Series[] }) => {
	const [recentlyViewed, setRecentlyViewed] = useState<RecentlyViewedItem[]>([]);

	useEffect(() => {
		setRecentlyViewed(readRecentlyViewed());
	}, []);

	const progress = useMemo(() => {
		for (const item of recentlyViewed) {
			const book = series.find((s) => s.posts.some((post) => post.slug === item.slug));
			if (!book) continue;
			const chapterIndex = book.posts.findIndex((post) => post.slug === item.slug);
			return {
				book,
				chapterIndex,
				currentChapter: book.posts[chapterIndex],
			};
		}
		return null;
	}, [recentlyViewed, series]);

	if (!progress) return null;

	return (
		<section className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 dark:border-neutral-800 dark:bg-neutral-900/60">
			<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-500 dark:text-neutral-400">
				Continue book
			</p>
			<div className="mt-3 grid gap-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-end">
				<div>
					<h2 className="text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
						{progress.book.name}
					</h2>
					<p className="mt-2 text-sm font-semibold text-neutral-500 dark:text-neutral-400">
						Chapter {progress.chapterIndex + 1} of {progress.book.postCount}
					</p>
					<p className="mt-1 line-clamp-1 text-sm text-neutral-600 dark:text-neutral-300">
						{progress.currentChapter.title}
					</p>
				</div>
				<Link
					href={`/${progress.currentChapter.slug}`}
					className="inline-flex justify-center rounded-xl bg-neutral-950 px-4 py-2 text-sm font-bold text-white transition hover:bg-blue-700 dark:bg-white dark:text-neutral-950 dark:hover:bg-blue-100"
				>
					Continue Book
				</Link>
			</div>
		</section>
	);
};

const FeaturedBookCard = ({ s }: { s: Series }) => {
	const hours = Math.floor(s.totalReadTime / 60);
	const mins = s.totalReadTime % 60;
	const duration = hours > 0 ? `${hours}h ${mins}m` : `${mins} min`;

	return (
		<article className="flex min-w-0 flex-col overflow-hidden rounded-2xl border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900">
			<img
				src={resolveBookImage(s, { w: 720, h: 360 })}
				alt={s.name}
				className="aspect-[16/8] w-full object-cover"
			/>
			<div className="flex flex-1 flex-col p-5">
				<h3 className="text-xl font-black leading-tight text-neutral-950 dark:text-neutral-50">{s.name}</h3>
				<p className="mt-3 line-clamp-3 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
					{getBookOutcome(s)}
				</p>
				<div className="mt-5 flex flex-wrap gap-x-3 gap-y-1 text-xs font-semibold text-neutral-500 dark:text-neutral-400">
					<span>{s.postCount} chapter{s.postCount !== 1 ? 's' : ''}</span>
					{duration ? <span>{duration}</span> : null}
				</div>
				<Link
					href={`/series/${s.slug}`}
					className="mt-5 inline-flex justify-center rounded-xl bg-neutral-950 px-4 py-2 text-sm font-bold text-white transition hover:bg-blue-700 dark:bg-white dark:text-neutral-950 dark:hover:bg-blue-100"
				>
					Start Book
				</Link>
			</div>
		</article>
	);
};

const BookRow = ({ s, index }: { s: Series; index: number }) => {
	const duration = formatDuration(s.totalReadTime);
	return (
		<div className="grid gap-4 border-t border-neutral-100 py-5 first:border-t-0 dark:border-neutral-800 md:grid-cols-[72px_minmax(0,1fr)_auto] md:items-center">
			<span className="flex h-10 w-10 items-center justify-center rounded-xl bg-neutral-100 text-xs font-black text-neutral-500 dark:bg-neutral-800 dark:text-neutral-300">
				{index + 1}
			</span>
			<div className="grid min-w-0 gap-3 sm:grid-cols-[96px_minmax(0,1fr)] sm:items-center">
				<img
					src={resolveBookImage(s, { w: 192, h: 144 })}
					alt={s.name}
					className="hidden aspect-[4/3] w-24 rounded-xl object-cover sm:block"
				/>
				<div className="min-w-0">
					<h3 className="text-base font-black text-neutral-950 dark:text-neutral-50">{s.name}</h3>
					<p className="mt-1 line-clamp-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
						{getBookOutcome(s)}
					</p>
					<p className="mt-2 text-xs font-semibold text-neutral-500 dark:text-neutral-400">
						{s.postCount} chapter{s.postCount !== 1 ? 's' : ''}{duration ? ` · ${duration}` : ''}
					</p>
				</div>
			</div>
			<div className="flex flex-wrap gap-3 md:justify-end">
				<Link
					href={`/series/${s.slug}`}
					className="inline-flex rounded-xl bg-neutral-950 px-4 py-2 text-sm font-bold text-white transition hover:bg-blue-700 dark:bg-white dark:text-neutral-950 dark:hover:bg-blue-100"
				>
					Start Book
				</Link>
				<Link
					href={`/series/${s.slug}`}
					className="inline-flex rounded-xl px-2 py-2 text-sm font-bold text-neutral-500 transition hover:text-blue-700 dark:text-neutral-400 dark:hover:text-blue-300"
				>
					View Chapters
				</Link>
			</div>
		</div>
	);
};

export default function SeriesPage({ publication, series, footerPosts }: Props) {
	const featuredSeries = useMemo(() => getFeaturedSeries(series), [series]);
	const featuredIds = useMemo(() => new Set(featuredSeries.map((s) => s.id)), [featuredSeries]);
	const allBooks = useMemo(
		() => [...featuredSeries, ...series.filter((s) => !featuredIds.has(s.id))],
		[featuredIds, featuredSeries, series],
	);

	return (
		<AppProvider publication={publication} footerPosts={footerPosts}>
			<Layout>
				<Head>
					<title>Engineering Books - {publication.title}</title>
					<meta
						name="description"
						content={`Curated engineering books from ${publication.title} that build understanding chapter by chapter.`}
					/>
					<meta property="og:title" content={`Engineering Books - ${publication.title}`} />
					<meta
						property="og:description"
						content={`Curated engineering books from ${publication.title} that build understanding chapter by chapter.`}
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={`Engineering Books - ${publication.title}`} />
					<meta
						property="twitter:description"
						content={`Curated engineering books from ${publication.title} that build understanding chapter by chapter.`}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<main className="mx-auto w-full max-w-7xl px-4 pb-20 pt-10 sm:px-5">
						<Link
							href="/"
							className="mb-10 inline-flex text-sm text-neutral-400 transition-colors hover:text-blue-600 dark:text-neutral-500 dark:hover:text-blue-400"
						>
							Home
						</Link>

						<section>
							<p className="mb-2 text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
								Books
							</p>
							<h1 className="text-4xl font-black tracking-tight text-neutral-950 dark:text-neutral-50 md:text-5xl">
								Engineering books
							</h1>
							<p className="mt-3 max-w-2xl text-base leading-relaxed text-neutral-600 dark:text-neutral-300">
								Curated technical books that build understanding chapter by chapter.
							</p>
						</section>

						{series.length > 0 ? (
							<div className="mt-10 space-y-14">
								<ContinueBook series={series} />

								<section>
									<div className="mb-5">
										<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-400 dark:text-neutral-500">
											Featured books
										</p>
										<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
											Start with a book
										</h2>
									</div>
									<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
										{featuredSeries.slice(0, 5).map((s) => (
											<FeaturedBookCard key={s.id} s={s} />
										))}
									</div>
								</section>

								<section>
									<div className="mb-3">
										<p className="text-[10px] font-mono uppercase tracking-[0.22em] text-neutral-400 dark:text-neutral-500">
											All books
										</p>
										<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
											Choose a book
										</h2>
									</div>
									<div className="rounded-2xl border border-neutral-200 bg-white px-4 dark:border-neutral-800 dark:bg-neutral-900">
										{allBooks.map((s, index) => (
											<BookRow key={s.id} s={s} index={index} />
										))}
									</div>
								</section>

								<section className="border-t border-neutral-100 pt-6 dark:border-neutral-800">
									<div className="flex flex-wrap gap-x-4 gap-y-2 text-sm font-bold">
										<Link href="/posts" className="text-neutral-500 transition hover:text-blue-700 dark:text-neutral-400 dark:hover:text-blue-300">
											Browse chapters
										</Link>
										<Link href="/discover#topic-collections" className="text-neutral-500 transition hover:text-blue-700 dark:text-neutral-400 dark:hover:text-blue-300">
											Open Discovery
										</Link>
									</div>
								</section>
							</div>
						) : (
							<div className="mt-10 rounded-2xl border border-dashed border-neutral-200 px-6 py-16 text-center dark:border-neutral-800">
								<p className="text-base text-neutral-500 dark:text-neutral-400">
									No books available yet.
								</p>
							</div>
						)}
					</main>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		// ── 1. Fetch all posts (for tag + read-time aggregation) ───────────────
		const postsData = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			PostsByPublicationDocument,
			{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST },
		);

		const publication = postsData.publication;
		if (!publication) return { notFound: true };

		const allPosts: PostFragment[] = [...(postsData.publication?.posts.edges ?? []).map((e) => e.node)];
		let cursor = postsData.publication?.posts.pageInfo?.endCursor;
		let hasNextPage = !!postsData.publication?.posts.pageInfo?.hasNextPage;

		while (hasNextPage && cursor) {
			const next = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
				GQL_ENDPOINT,
				MorePostsByPublicationDocument,
				{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: cursor },
			);
			if (!next.publication) break;
			allPosts.push(...next.publication.posts.edges.map((e) => e.node));
			cursor = next.publication.posts.pageInfo.endCursor;
			hasNextPage = !!next.publication.posts.pageInfo.hasNextPage;
		}

		// ── 2. Fetch series metadata (description + cover) — falls back gracefully ──
		type RawSeries = { id: string; name: string; slug: string; description?: { text?: string } | null; coverImage?: string | null };
		let rawSeriesMap = new Map<string, RawSeries>();
		try {
			let seriesCursor: string | null | undefined = undefined;
			let seriesHasNextPage = true;
			while (seriesHasNextPage) {
				const seriesPage: AllSeriesByPublicationQuery = await request<AllSeriesByPublicationQuery, AllSeriesByPublicationQueryVariables>(
					GQL_ENDPOINT,
					AllSeriesByPublicationDocument,
					{ first: 20, host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST, after: seriesCursor },
				);
				for (const edge of seriesPage.publication?.seriesList?.edges ?? []) {
					rawSeriesMap.set(edge.node.id, edge.node);
				}
				seriesCursor = seriesPage.publication?.seriesList?.pageInfo?.endCursor;
				seriesHasNextPage = !!seriesPage.publication?.seriesList?.pageInfo?.hasNextPage;
			}
		} catch (err) {
			console.warn('seriesList query failed, falling back to post-derived series:', err);
		}

		// ── 3. Aggregate per-series data from posts ────────────────────────────
		// Collect all unique series ids from posts
		const seriesIdOrder: string[] = [];
		const seenIds = new Set<string>();
		for (const post of allPosts) {
			if (post.series?.id && !seenIds.has(post.series.id)) {
				seenIds.add(post.series.id);
				seriesIdOrder.push(post.series.id);
				// Seed rawSeriesMap if seriesList query returned nothing
				if (!rawSeriesMap.has(post.series.id)) {
					rawSeriesMap.set(post.series.id, { id: post.series.id, name: post.series.name, slug: post.series.slug });
				}
			}
		}

		const series: Series[] = [...rawSeriesMap.values()].map((s) => {
			const seriesPosts = allPosts.filter((p) => p.series?.id === s.id);

			return {
				id: s.id,
				name: s.name,
				slug: s.slug,
				description: s.description?.text ?? '',
				coverImage: s.coverImage ?? null,
				postCount: seriesPosts.length,
				totalReadTime: seriesPosts.reduce((sum, p) => sum + (p.readTimeInMinutes ?? 0), 0),
				posts: seriesPosts.map((post) => ({
					slug: post.slug,
					title: post.title,
					coverImage: post.coverImage?.url ?? null,
				})),
			};
		}).sort((a, b) => b.postCount - a.postCount);

		return {
			props: { publication, series, footerPosts: allPosts },
			revalidate: CONTENT_REVALIDATE_SECONDS,
		};
	} catch (error) {
		console.error('Error fetching series page data:', error);
		return { notFound: true };
	}
};

