import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import { CONTENT_REVALIDATE_SECONDS } from '../lib/cache-constants';
import { fetchYouTubeFeed, YouTubeFeed, YouTubeVideo } from '../lib/youtube-feed';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
const DEFAULT_CHANNEL_ID = 'UChQ6hLBvvloMv2IZPlHCdhw';

type Props = {
	publication: PublicationFragment;
	posts: PostFragment[];
	feed: YouTubeFeed;
};

type IconName = 'play' | 'grid' | 'article' | 'series' | 'bookmark' | 'history' | 'external' | 'youtube' | 'clock' | 'sparkle';

const Icon = ({ name, className = 'h-5 w-5' }: { name: IconName; className?: string }) => {
	const props = {
		className,
		fill: 'none',
		stroke: 'currentColor',
		strokeWidth: 1.8,
		strokeLinecap: 'round' as const,
		strokeLinejoin: 'round' as const,
		viewBox: '0 0 24 24',
		'aria-hidden': true,
	};
	if (name === 'play') return <svg {...props}><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m10 9 5 3-5 3V9Z" /></svg>;
	if (name === 'grid') return <svg {...props}><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></svg>;
	if (name === 'article') return <svg {...props}><path d="M6 3h9l3 3v15H6V3Z" /><path d="M9 10h6M9 14h6M9 18h4" /></svg>;
	if (name === 'series') return <svg {...props}><path d="M4 6h16M4 12h16M4 18h10" /></svg>;
	if (name === 'bookmark') return <svg {...props}><path d="M6 4h12v17l-6-4-6 4V4Z" /></svg>;
	if (name === 'history') return <svg {...props}><path d="M3 12a9 9 0 1 0 3-6.7L3 8" /><path d="M3 3v5h5M12 7v5l3 2" /></svg>;
	if (name === 'clock') return <svg {...props}><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></svg>;
	if (name === 'external') return <svg {...props}><path d="M14 4h6v6M20 4l-9 9" /><path d="M18 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6" /></svg>;
	if (name === 'youtube') return <svg {...props}><path d="M21 8.2a2.5 2.5 0 0 0-1.8-1.8C17.6 6 12 6 12 6s-5.6 0-7.2.4A2.5 2.5 0 0 0 3 8.2 26 26 0 0 0 2.6 12 26 26 0 0 0 3 15.8a2.5 2.5 0 0 0 1.8 1.8c1.6.4 7.2.4 7.2.4s5.6 0 7.2-.4a2.5 2.5 0 0 0 1.8-1.8 26 26 0 0 0 .4-3.8 26 26 0 0 0-.4-3.8Z" /><path d="m10 9 5 3-5 3V9Z" /></svg>;
	return <svg {...props}><path d="m12 3 1.4 4.1L17.5 8.5l-4.1 1.4L12 14l-1.4-4.1-4.1-1.4 4.1-1.4L12 3ZM18.5 14l.8 2.2 2.2.8-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.8.8-2.2Z" /></svg>;
};

const formatViews = (views: number) => {
	if (!views) return 'New';
	if (views >= 1_000_000) return `${(views / 1_000_000).toFixed(1).replace('.0', '')}M views`;
	if (views >= 1_000) return `${(views / 1_000).toFixed(1).replace('.0', '')}K views`;
	return `${views} views`;
};

const formatDate = (value: string) => {
	const date = new Date(value);
	if (Number.isNaN(date.getTime())) return '';
	const days = Math.max(0, Math.floor((Date.now() - date.getTime()) / 86_400_000));
	if (days === 0) return 'Today';
	if (days === 1) return 'Yesterday';
	if (days < 30) return `${days} days ago`;
	if (days < 365) return `${Math.floor(days / 30)} months ago`;
	return `${Math.floor(days / 365)} years ago`;
};

const getTags = (video: YouTubeVideo) => {
	const text = `${video.title} ${video.description}`.toLowerCase();
	const tags = [
		['Data Structures', ['array', 'linked list', 'stack', 'queue', 'tree', 'graph']],
		['Algorithms', ['algorithm', 'complexity', 'sorting', 'search']],
		['System Design', ['system design', 'scalab', 'cache', 'database']],
		['Interview Prep', ['interview', 'question']],
	] as const;
	const matches = tags.filter(([, words]) => words.some((word) => text.includes(word))).map(([label]) => label);
	return [...matches, video.isShort ? 'Quick lesson' : 'Video'].slice(0, 3);
};

const VideoRow = ({ video, onPlay }: { video: YouTubeVideo; onPlay: (video: YouTubeVideo) => void }) => (
	<button type="button" onClick={() => onPlay(video)} className="group grid w-full gap-4 border-b border-slate-100 p-4 text-left last:border-b-0 md:grid-cols-[240px_minmax(0,1fr)_160px]">
		<div className="relative overflow-hidden rounded-xl bg-slate-100">
			<Image src={video.thumbnailUrl} alt="" width={480} height={270} className="aspect-video h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]" />
			<span className="absolute inset-0 flex items-center justify-center bg-slate-950/5 transition group-hover:bg-slate-950/15">
				<span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/95 text-red-600 shadow-lg"><Icon name="play" className="h-6 w-6" /></span>
			</span>
			{video.isShort ? <span className="absolute bottom-2 right-2 rounded bg-slate-950/85 px-2 py-1 text-[10px] font-black uppercase tracking-wide text-white">Short</span> : null}
		</div>
		<div className="min-w-0 py-1">
			<h2 className="line-clamp-2 text-base font-extrabold leading-6 text-slate-950 transition group-hover:text-blue-700">{video.title}</h2>
			<p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-600">{video.description}</p>
			<div className="mt-3 flex flex-wrap gap-2">{getTags(video).map((tag) => <span key={tag} className="rounded-md bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{tag}</span>)}</div>
		</div>
		<div className="flex items-start justify-between gap-4 py-1 md:block">
			<p className="flex items-center gap-1.5 text-xs font-bold text-emerald-700"><Icon name="sparkle" className="h-4 w-4" /> Learn something new</p>
			<p className="mt-2 text-xs text-slate-500">{formatViews(video.views)} <span className="mx-1">•</span> {formatDate(video.publishedAt)}</p>
			<p className="mt-5 hidden text-xs leading-5 text-slate-500 md:block"><span className="font-bold text-slate-700">Why watch?</span><br />A focused visual lesson from our channel.</p>
		</div>
	</button>
);

export default function VideosPage({ publication, posts, feed }: Props) {
	const [filter, setFilter] = useState<'all' | 'videos' | 'shorts'>('all');
	const [selectedVideo, setSelectedVideo] = useState<YouTubeVideo | null>(null);
	const shownVideos = useMemo(() => feed.videos.filter((video) => filter === 'all' || (filter === 'shorts' ? video.isShort : !video.isShort)), [feed.videos, filter]);
	const latest = feed.videos[0];

	useEffect(() => {
		if (!selectedVideo) return;
		const previousOverflow = document.body.style.overflow;
		const onKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape') setSelectedVideo(null);
		};
		document.body.style.overflow = 'hidden';
		window.addEventListener('keydown', onKeyDown);
		return () => {
			document.body.style.overflow = previousOverflow;
			window.removeEventListener('keydown', onKeyDown);
		};
	}, [selectedVideo]);

	return (
		<AppProvider publication={publication} footerPosts={posts}>
			<Layout>
				<Head>
					<title>Videos - {publication.title}</title>
					<meta name="description" content={`Watch software engineering lessons from ${feed.channelTitle}.`} />
					<meta property="og:image" content={latest?.thumbnailUrl || publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)} />
					<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }} />
				</Head>
				<Container className="mx-auto w-full bg-white">
					<PersonalHeader />
					<main className="mx-auto grid w-full max-w-[1440px] grid-cols-1 border-x border-slate-200 lg:grid-cols-[220px_minmax(0,1fr)]">
						<aside className="hidden min-h-screen border-r border-slate-200 bg-white p-5 lg:block">
							<p className="px-3 text-[10px] font-black uppercase tracking-wider text-slate-500">Learn</p>
							<nav className="mt-3 grid gap-1">
								<Link href="/learn" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><Icon name="grid" className="h-4 w-4" />Overview</Link>
								<Link href="/posts" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><Icon name="article" className="h-4 w-4" />Articles</Link>
								<Link href="/videos" className="flex items-center gap-3 rounded-lg bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700"><Icon name="play" className="h-4 w-4" />Videos</Link>
								<Link href="/series" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><Icon name="series" className="h-4 w-4" />Playlists & Series</Link>
							</nav>
							<div className="my-6 border-t border-slate-200" />
							<p className="px-3 text-[10px] font-black uppercase tracking-wider text-slate-500">My learning</p>
							<nav className="mt-3 grid gap-1">
								<Link href="/progress" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><Icon name="bookmark" className="h-4 w-4" />Saved lessons</Link>
								<Link href="/progress" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><Icon name="history" className="h-4 w-4" />My progress</Link>
							</nav>
							<div className="mt-10 rounded-xl border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-4">
								<span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white"><Icon name="play" /></span>
								<p className="mt-4 text-sm font-black text-slate-950">Learn in a few minutes</p>
								<p className="mt-2 text-xs leading-5 text-slate-600">Visual lessons and Shorts for busy engineers.</p>
							</div>
						</aside>

						<div className="min-w-0 bg-slate-50/40">
							<section className="border-b border-slate-200 bg-white px-5 py-8 md:px-9">
								<p className="text-xs font-bold text-blue-700">Learn <span className="mx-2 text-slate-300">/</span> Video Library</p>
								<div className="mt-7 flex flex-col gap-6 md:flex-row md:items-center md:justify-between">
									<div>
										<span className="inline-flex items-center gap-2 rounded-full bg-red-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-red-600"><Icon name="youtube" className="h-4 w-4" /> From our YouTube channel</span>
										<h1 className="mt-4 text-3xl font-black tracking-tight text-slate-950 md:text-4xl">Video Library</h1>
										<p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Curated software engineering explainers, quick lessons, and practical guides from {feed.channelTitle}.</p>
									</div>
									<a href={feed.channelUrl} target="_blank" rel="noopener noreferrer" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-red-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-red-600/15 hover:bg-red-700">Visit channel <Icon name="external" className="h-4 w-4" /></a>
								</div>
								<div className="mt-7 flex flex-wrap gap-6 border-t border-slate-100 pt-5 text-xs font-bold text-slate-600">
									<span className="flex items-center gap-2"><Icon name="play" className="h-4 w-4 text-blue-600" />{feed.videos.length} latest lessons</span>
									<span className="flex items-center gap-2"><Icon name="clock" className="h-4 w-4 text-blue-600" />Updated automatically</span>
									<span className="flex items-center gap-2"><Icon name="sparkle" className="h-4 w-4 text-blue-600" />Free on YouTube</span>
								</div>
							</section>

							<section className="grid gap-6 p-5 md:p-9 xl:grid-cols-[minmax(0,1fr)_280px]">
								<div className="min-w-0">
									<div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
										<div><h2 className="text-xl font-black text-slate-950">Latest videos</h2><p className="mt-1 text-xs text-slate-500">Fresh lessons, loaded directly from YouTube.</p></div>
										<div className="inline-flex w-fit rounded-lg border border-slate-200 bg-white p-1">{(['all', 'videos', 'shorts'] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-md px-3 py-1.5 text-xs font-bold capitalize ${filter === item ? 'bg-blue-600 text-white' : 'text-slate-600 hover:bg-slate-50'}`}>{item}</button>)}</div>
									</div>
									<div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
										{shownVideos.length ? shownVideos.map((video) => <VideoRow key={video.id} video={video} onPlay={setSelectedVideo} />) : <div className="p-10 text-center"><p className="font-bold text-slate-900">No {filter} found in the latest uploads.</p><button onClick={() => setFilter('all')} className="mt-3 text-sm font-bold text-blue-600">Show all videos</button></div>}
									</div>
								</div>

								<aside className="space-y-4">
									<div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
										<span className="flex h-10 w-10 items-center justify-center rounded-xl bg-red-50 text-red-600"><Icon name="youtube" /></span>
										<h2 className="mt-4 text-base font-black text-slate-950">Learning from YouTube</h2>
										<p className="mt-2 text-xs leading-5 text-slate-600">Watch clear, focused lessons, then use the articles and roadmaps here to go deeper.</p>
										<a href={feed.channelUrl} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-black text-blue-600">Explore the channel <Icon name="external" className="h-3.5 w-3.5" /></a>
									</div>
									<div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
										<h2 className="text-base font-black text-slate-950">Keep learning</h2>
										<div className="mt-4 grid gap-3"><Link href="/learn" className="flex items-center justify-between rounded-lg bg-blue-50 px-3 py-3 text-xs font-bold text-blue-700"><span className="flex items-center gap-2"><Icon name="grid" className="h-4 w-4" />Learning paths</span>→</Link><Link href="/posts" className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-3 text-xs font-bold text-slate-700"><span className="flex items-center gap-2"><Icon name="article" className="h-4 w-4" />Read articles</span>→</Link></div>
									</div>
									<div className="rounded-xl border border-blue-100 bg-gradient-to-br from-blue-50 to-indigo-50 p-5">
										<span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-blue-600 shadow-sm"><Icon name="bookmark" /></span>
										<h2 className="mt-4 text-base font-black text-slate-950">Save your progress</h2><p className="mt-2 text-xs leading-5 text-slate-600">Keep your articles, roadmaps, and learning activity together.</p><Link href="/progress" className="mt-4 inline-flex text-xs font-black text-blue-600">View my progress →</Link>
									</div>
								</aside>
							</section>
						</div>
					</main>
					<Footer />
				</Container>
				{selectedVideo ? (
					<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/85 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={`Playing ${selectedVideo.title}`} onMouseDown={(event) => { if (event.currentTarget === event.target) setSelectedVideo(null); }}>
						<div className="w-full max-w-5xl overflow-hidden rounded-2xl border border-white/10 bg-slate-950 shadow-2xl">
							<div className="flex items-center justify-between gap-4 border-b border-white/10 px-4 py-3 sm:px-5">
								<div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-wider text-red-400">Now playing</p><h2 className="mt-1 truncate text-sm font-bold text-white sm:text-base">{selectedVideo.title}</h2></div>
								<button type="button" onClick={() => setSelectedVideo(null)} aria-label="Close video player" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-white/10 text-2xl text-white transition hover:bg-white/20">×</button>
							</div>
							<div className="aspect-video w-full bg-black">
								<iframe
									key={selectedVideo.id}
									className="h-full w-full"
									src={`https://www.youtube-nocookie.com/embed/${selectedVideo.id}?autoplay=1&rel=0&modestbranding=1`}
									title={selectedVideo.title}
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
									allowFullScreen
								/>
							</div>
						</div>
					</div>
				) : null}
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	try {
		const channelId = process.env.YOUTUBE_CHANNEL_ID || DEFAULT_CHANNEL_ID;
		const [data, feedResult] = await Promise.all([
			request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(GQL_ENDPOINT, PostsByPublicationDocument, {
				first: 8,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
			}),
			fetchYouTubeFeed(channelId).catch((error) => {
				console.error('[videos] YouTube feed error:', error);
				return { channelId, channelTitle: 'Abstract Algorithms', channelUrl: `https://www.youtube.com/channel/${channelId}`, videos: [] };
			}),
		]);
		if (!data.publication) return { notFound: true };
		return {
			props: {
				publication: data.publication,
				posts: data.publication.posts.edges.map((edge) => edge.node),
				feed: feedResult,
			},
			revalidate: Math.min(CONTENT_REVALIDATE_SECONDS, 3600),
		};
	} catch (error) {
		console.error('[videos] getStaticProps error:', error);
		return { notFound: true };
	}
};
