import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { AppProvider } from '../components/contexts/appContext';
import { Container } from '../components/container';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { useLearningContext } from '../components/learning-context-provider';
import { CTALink } from '../components/cta-system';
import { PersonalHeader } from '../components/personal-theme-header';
import { VisualizationStudio } from '../components/visualization/visualization-studio';
import { PostFragment, PublicationByHostDocument, PublicationByHostQuery, PublicationByHostQueryVariables, PublicationFragment } from '../generated/graphql';
import { getFooterPosts } from '../lib/api/footerData';
import { CONTENT_REVALIDATE_SECONDS } from '../lib/cache-constants';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	footerPosts: PostFragment[];
};

export default function VisualizationsPage({ publication, footerPosts }: Props) {
	const router = useRouter();
	const { setContext } = useLearningContext();
	const topic = typeof router.query.q === 'string' ? router.query.q : 'Technical Visualization System';
	const section = typeof router.query.section === 'string' ? router.query.section : undefined;
	const sectionId = typeof router.query.sectionId === 'string' ? router.query.sectionId : undefined;
	const sourcePath = typeof router.query.from === 'string' ? router.query.from : undefined;
	const roadmapNode = typeof router.query.node === 'string' ? router.query.node : topic;

	useEffect(() => {
		setContext({
			source: 'simulation',
			pathname: '/visualizations',
			title: 'Technical Visualization System',
			domain: 'Engineering',
			topic,
			concept: topic,
			sectionId,
			sectionTitle: section,
			simulationTopic: topic,
			roadmapNode,
		});
	}, [roadmapNode, section, sectionId, setContext, topic]);

	return (
		<AppProvider publication={publication} footerPosts={footerPosts}>
			<Layout>
				<Head>
					<title>Interactive Technical Visualizations - {publication.title}</title>
					<meta
						name="description"
						content="Interactive architecture flows and step-by-step simulations for Kafka, quorum, CAP, consensus, vector databases, LLM pipelines, and more."
					/>
					<meta property="og:title" content={`Interactive Technical Visualizations - ${publication.title}`} />
					<meta
						property="og:description"
						content="Explore animated simulations for distributed systems and AI architecture patterns."
					/>
					<meta
						property="og:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={`Interactive Technical Visualizations - ${publication.title}`} />
					<meta
						property="twitter:description"
						content="Explore animated simulations for distributed systems and AI architecture patterns."
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-7xl mx-auto w-full px-5 py-10">
						<section className="mb-8">
							<p className="text-[10px] font-mono uppercase tracking-widest text-blue-500 dark:text-blue-400">
								Interactive learning lab
							</p>
							<h1 className="mt-2 text-4xl md:text-5xl font-bold tracking-tight text-neutral-900 dark:text-neutral-50">
								Technical Visualization System
							</h1>
							<p className="mt-3 max-w-3xl text-neutral-600 dark:text-neutral-300">
								Transform static diagrams into simulation playback with layered explanations, hover-based
								context, and mobile-compatible traversal.
							</p>
							{section ? (
								<div className="mt-4 inline-flex flex-wrap items-center gap-2 rounded-2xl border border-violet-200 bg-violet-50/70 px-3 py-2 text-xs font-semibold text-violet-700 dark:border-violet-800 dark:bg-violet-950/30 dark:text-violet-200">
									<span>Launched from article section:</span>
									<span className="text-neutral-900 dark:text-neutral-50">{section}</span>
								</div>
							) : null}
							<div className="mt-4 flex flex-wrap gap-2">
								{sourcePath ? (
									<CTALink
										href={sectionId ? `${sourcePath}#${sectionId}` : sourcePath}
										level={2}
										size="sm"
									>
										Back to Article Context
									</CTALink>
								) : null}
								<CTALink
									href="/posts"
									level={sourcePath ? 3 : 2}
									size="sm"
								>
									Browse Articles
								</CTALink>
								<CTALink
									href="/"
									level={3}
									size="sm"
								>
									Back to Home
								</CTALink>
							</div>
						</section>

						<VisualizationStudio initialTopic={topic} initialSection={section} />
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PublicationByHostQuery, PublicationByHostQueryVariables>(
		GQL_ENDPOINT,
		PublicationByHostDocument,
		{
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}

	const footerPosts = await getFooterPosts();

	return {
		props: {
			publication,
			footerPosts,
		},
		revalidate: CONTENT_REVALIDATE_SECONDS,
	};
};
