import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { resizeImage } from '@starter-kit/utils/image';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Container } from '../../components/container';
import { AppProvider } from '../../components/contexts/appContext';
import { Footer } from '../../components/footer';
import { Layout } from '../../components/layout';
import { MarkdownToHtml } from '../../components/markdown-to-html';
import { PersonalHeader } from '../../components/personal-theme-header';
import { getFooterPosts } from '../../lib/api/footerData';
import { ARTICLE_REVALIDATE_SECONDS } from '../../lib/cache-constants';
import {
	PageByPublicationDocument,
	PageByPublicationQuery,
	PageByPublicationQueryVariables,
	PostFragment,
	PublicationFragment,
	SeriesPostsByPublicationDocument,
	SeriesPostsByPublicationQuery,
	SeriesPostsByPublicationQueryVariables,
} from '../../generated/graphql';

const RECENTLY_VIEWED_KEY = 'aa:recently-viewed-posts';
const FALLBACK_POST_IMAGE = '/assets/blog/post-fallback.svg';

type SeriesInfo = {
	id: string;
	name: string;
	slug: string;
	coverImage?: string | null;
	description?: string | null;
};

type SeriesPlanPage = {
	title: string;
	markdown: string;
} | null;

type Props = {
	publication: PublicationFragment;
	posts: PostFragment[];
	series: SeriesInfo;
	roadmap: SeriesPlanPage;
	footerPosts: PostFragment[];
};

type RecentlyViewedItem = {
	slug: string;
	title: string;
	seenAt: number;
};

type RelatedBook = {
	name: string;
	slug: string;
	postCount: number;
	totalReadTime: number;
};

const readRecentlyViewed = (): RecentlyViewedItem[] => {
	if (typeof window === 'undefined') return [];
	try {
		const raw = localStorage.getItem(RECENTLY_VIEWED_KEY);
		if (!raw) return [];
		return JSON.parse(raw) as RecentlyViewedItem[];
	} catch {
		return [];
	}
};

const rememberPostView = (post: PostFragment) => {
	if (typeof window === 'undefined') return;
	try {
		const next = [
			{ slug: post.slug, title: post.title, seenAt: Date.now() },
			...readRecentlyViewed().filter((entry) => entry.slug !== post.slug),
		].slice(0, 8);
		localStorage.setItem(RECENTLY_VIEWED_KEY, JSON.stringify(next));
	} catch {}
};

const stripHtml = (value?: string | null) => value?.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim() ?? '';

const formatDuration = (minutes: number) => {
	if (minutes <= 0) return '';
	const hours = Math.floor(minutes / 60);
	const mins = minutes % 60;
	if (hours <= 0) return `${mins} min`;
	return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
};

const getBookOutcome = (series: SeriesInfo) => {
	const description = stripHtml(series.description);
	const text = `${series.name} ${description}`.toLowerCase();
	if (description) return description;
	if (/kafka/.test(text)) return 'Understand Kafka from partitions to transactions and exactly-once processing.';
	if (/distributed|consensus|replication/.test(text)) return 'Understand coordination, consistency, failure, and recovery in distributed systems.';
	if (/vector|embedding|rag/.test(text)) return 'Understand semantic retrieval from embeddings to production query behavior.';
	if (/java|jvm|spring/.test(text)) return 'Understand modern Java from runtime behavior to production design choices.';
	if (/system design|hld|interview/.test(text)) return 'Build practical judgment for turning ambiguous requirements into durable architecture.';
	if (/llm|agent|ai/.test(text)) return 'Understand model behavior, agent architecture, evaluation, and production guardrails.';
	return `Build progressive understanding of ${series.name}.`;
};

const chapterTitle = (title: string) =>
	title
		.replace(/^(chapter|part)\s+\d+\s*[:.-]\s*/i, '')
		.replace(/^\d+\s*[:.-]\s*/, '')
		.trim();

const buildOverviewSteps = (posts: PostFragment[]) => {
	if (posts.length <= 5) return posts.map((post) => chapterTitle(post.title));
	const indexes = [0, Math.floor(posts.length * 0.25), Math.floor(posts.length * 0.5), Math.floor(posts.length * 0.75), posts.length - 1];
	return [...new Set(indexes)].map((index) => chapterTitle(posts[index].title));
};

const getRelatedBooks = (currentSeriesId: string, posts: PostFragment[]): RelatedBook[] => {
	const map = new Map<string, RelatedBook>();
	for (const post of posts) {
		if (!post.series || post.series.id === currentSeriesId) continue;
		const existing = map.get(post.series.id);
		map.set(post.series.id, {
			name: post.series.name,
			slug: post.series.slug,
			postCount: (existing?.postCount ?? 0) + 1,
			totalReadTime: (existing?.totalReadTime ?? 0) + (post.readTimeInMinutes ?? 0),
		});
	}
	return [...map.values()].sort((a, b) => b.postCount - a.postCount).slice(0, 2);
};

const SeriesPlanSection = ({ title, markdown }: { title: string; markdown: string }) => {
	return (
		<details className="rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
			<summary className="cursor-pointer list-none text-sm font-black text-neutral-950 dark:text-neutral-50">
				{title}
			</summary>
			<div className="mt-4 border-t border-neutral-100 pt-4 dark:border-neutral-800">
				<div className="prose prose-neutral max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-blue-600 prose-a:no-underline hover:prose-a:underline prose-code:text-sm dark:prose-invert dark:prose-a:text-blue-400">
					<MarkdownToHtml contentMarkdown={markdown} />
				</div>
			</div>
		</details>
	);
};

export default function SeriesDetailPage({ publication, posts, series, roadmap, footerPosts }: Props) {
	const title = `${series.name} - ${publication.title}`;
	const totalReadTime = posts.reduce((sum, p) => sum + (p.readTimeInMinutes ?? 0), 0);
	const firstPost = posts[0];
	const rawCoverImage = series.coverImage || firstPost?.coverImage?.url;
	const coverImage = rawCoverImage ? resizeImage(rawCoverImage, { w: 1280, h: 560, c: 'thumb' }) : FALLBACK_POST_IMAGE;
	const overviewSteps = useMemo(() => buildOverviewSteps(posts), [posts]);
	const relatedBooks = useMemo(() => getRelatedBooks(series.id, footerPosts), [footerPosts, series.id]);
	const [recentlyViewed, setRecentlyViewed] = useState<RecentlyViewedItem[]>([]);
	const currentProgress = useMemo(() => {
		for (const item of recentlyViewed) {
			const index = posts.findIndex((post) => post.slug === item.slug);
			if (index >= 0) return { post: posts[index], index };
		}
		return null;
	}, [posts, recentlyViewed]);
	const primaryPost = currentProgress?.post ?? firstPost;
	const primaryLabel = currentProgress ? 'Continue Book' : 'Start Book';
	const outcome = getBookOutcome(series);

	useEffect(() => {
		setRecentlyViewed(readRecentlyViewed());
	}, []);

	return (
		<AppProvider publication={publication} footerPosts={footerPosts}>
			<Layout>
				<Head>
					<title>{title}</title>
					<meta name="description" content={outcome} />
					<meta property="og:title" content={title} />
					<meta property="og:description" content={outcome} />
					<meta
						property="og:image"
						content={coverImage || publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={title} />
					<meta
						property="twitter:image"
						content={coverImage || publication.ogMetaData?.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<main className="mx-auto w-full max-w-7xl px-4 pb-20 pt-10 sm:px-5">
						<Link
							href="/series"
							className="mb-10 inline-flex text-sm text-neutral-400 transition-colors hover:text-blue-600 dark:text-neutral-500 dark:hover:text-blue-400"
						>
							All Books
						</Link>

						<section className="mx-auto grid w-full max-w-none gap-8 lg:grid-cols-[minmax(0,1fr)_220px] lg:items-end">
							<div>
								<p className="mb-2 text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
									Book
								</p>
								<h1 className="text-4xl font-black leading-tight tracking-tight text-neutral-950 dark:text-neutral-50 md:text-5xl">
									{series.name}
								</h1>
								<p className="mt-4 max-w-3xl text-base leading-relaxed text-neutral-600 dark:text-neutral-300">
									{outcome}
								</p>
								<div className="mt-5 flex flex-wrap gap-x-4 gap-y-1 text-sm font-semibold text-neutral-500 dark:text-neutral-400">
									<span>{posts.length} chapter{posts.length !== 1 ? 's' : ''}</span>
									{totalReadTime > 0 ? <span>{formatDuration(totalReadTime)}</span> : null}
								</div>
							</div>
							{primaryPost ? (
								<div className="rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-900">
									{currentProgress ? (
										<>
											<p className="text-[10px] font-mono uppercase tracking-[0.2em] text-blue-600 dark:text-blue-300">
												Continue from
											</p>
											<p className="mt-2 text-sm font-black text-neutral-950 dark:text-neutral-50">
												Chapter {currentProgress.index + 1}
											</p>
										</>
									) : (
										<p className="text-[10px] font-mono uppercase tracking-[0.2em] text-blue-600 dark:text-blue-300">
											Begin here
										</p>
									)}
									<Link
										href={`/${primaryPost.slug}`}
										onClick={() => rememberPostView(primaryPost)}
										className="mt-4 inline-flex w-full justify-center rounded-xl bg-neutral-950 px-4 py-2 text-sm font-bold text-white transition hover:bg-blue-700 dark:bg-white dark:text-neutral-950 dark:hover:bg-blue-100"
									>
										{primaryLabel}
									</Link>
								</div>
							) : null}
						</section>

						<img
							src={coverImage}
							alt={series.name}
							className="mx-auto mt-8 aspect-[16/7] w-full max-w-none rounded-2xl object-cover"
						/>

						<div className="mx-auto mt-10 w-full max-w-none space-y-12">
							<section>
								<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
									Book overview
								</p>
								<div className="mt-4 rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
									<ol className="space-y-3">
										{overviewSteps.map((step, index) => (
											<li key={`${step}-${index}`} className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_24px] sm:items-center">
												<span className="text-sm font-black text-neutral-950 dark:text-neutral-50">{step}</span>
												{index < overviewSteps.length - 1 ? (
													<span className="text-neutral-300 dark:text-neutral-700 sm:text-center" aria-hidden="true">↓</span>
												) : null}
											</li>
										))}
									</ol>
								</div>
							</section>

							{roadmap ? <SeriesPlanSection title={roadmap.title} markdown={roadmap.markdown} /> : null}

							<section>
								<div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
									<div>
										<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
											Reading path
										</p>
										<h2 className="mt-2 text-2xl font-black tracking-tight text-neutral-950 dark:text-neutral-50">
											Chapters
										</h2>
									</div>
									<Link
										href={`/assistant?q=${encodeURIComponent(`What should I know before starting ${series.name}?`)}`}
										className="text-sm font-bold text-neutral-500 transition hover:text-blue-700 dark:text-neutral-400 dark:hover:text-blue-300"
									>
										Ask AI: before starting
									</Link>
								</div>
								<div className="divide-y divide-neutral-100 rounded-2xl border border-neutral-200 bg-white dark:divide-neutral-800 dark:border-neutral-800 dark:bg-neutral-900">
									{posts.map((post, index) => (
										<Link
											key={post.id}
											href={`/${post.slug}`}
											onClick={() => rememberPostView(post)}
											className="grid gap-3 p-4 transition hover:bg-neutral-50 dark:hover:bg-neutral-800/60 sm:grid-cols-[96px_minmax(0,1fr)_auto] sm:items-start"
										>
											<span className="text-xs font-black uppercase tracking-wide text-neutral-400 dark:text-neutral-500">
												Chapter {index + 1}
											</span>
											<span className="min-w-0">
												<span className="block text-base font-black text-neutral-950 dark:text-neutral-50">{post.title}</span>
												<span className="mt-1 line-clamp-2 block text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
													{post.brief}
												</span>
											</span>
											<span className="text-xs font-semibold text-neutral-400 dark:text-neutral-500">
												{post.readTimeInMinutes} min
											</span>
										</Link>
									))}
								</div>
							</section>

							<section className="grid gap-4 border-t border-neutral-100 pt-6 dark:border-neutral-800 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center">
								<div>
									<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
										Summarize
									</p>
									<p className="mt-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
										Get a short orientation before you start the chapters.
									</p>
								</div>
								<Link
									href={`/assistant?q=${encodeURIComponent(`Summarize the ${series.name} book and explain the chapter progression.`)}`}
									className="inline-flex justify-center rounded-xl border border-neutral-200 px-4 py-2 text-sm font-bold text-neutral-700 transition hover:border-blue-300 hover:text-blue-700 dark:border-neutral-800 dark:text-neutral-300 dark:hover:border-blue-700 dark:hover:text-blue-300"
								>
									Summarize Book
								</Link>
							</section>

							{relatedBooks.length > 0 ? (
								<section>
									<p className="text-[10px] font-mono uppercase tracking-widest text-neutral-400 dark:text-neutral-500">
										Next
									</p>
									<div className="mt-4 grid gap-3 sm:grid-cols-2">
										{relatedBooks.map((book) => (
											<Link
												key={book.slug}
												href={`/series/${book.slug}`}
												className="rounded-2xl border border-neutral-200 bg-white p-4 transition hover:border-blue-300 dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-blue-700"
											>
												<p className="text-sm font-black text-neutral-950 dark:text-neutral-50">{book.name}</p>
												<p className="mt-2 text-xs font-semibold text-neutral-500 dark:text-neutral-400">
													{book.postCount} chapter{book.postCount !== 1 ? 's' : ''}{book.totalReadTime ? ` · ${formatDuration(book.totalReadTime)}` : ''}
												</p>
												<p className="mt-3 text-xs font-bold text-blue-600 dark:text-blue-300">View Related Book</p>
											</Link>
										))}
									</div>
								</section>
							) : null}
						</div>
					</main>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) throw new Error('No params');

	const data = await request<SeriesPostsByPublicationQuery, SeriesPostsByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SeriesPostsByPublicationDocument,
		{
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
			seriesSlug: params.slug,
			first: 20,
		},
	);

	const publication = data.publication;
	if (!publication || !publication.series) {
		return { notFound: true };
	}

	const { series } = publication;
	const posts = series.posts.edges.map((edge) => edge.node);
	const footerPosts = await getFooterPosts();

	// Try to fetch a matching static page using the series slug.
	let roadmap: SeriesPlanPage = null;
	try {
		const pageData = await request<PageByPublicationQuery, PageByPublicationQueryVariables>(
			process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
			PageByPublicationDocument,
			{
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				slug: `${params.slug}-roadmap`,
			},
		);
		const page = pageData.publication?.staticPage;
		if (page && !page.hidden) {
			roadmap = {
				title: page.title,
				markdown: page.content.markdown,
			};
		}
	} catch {
		// No matching page — silently skip
	}

	return {
		props: {
			publication,
			posts,
			series: {
				id: series.id,
				name: series.name,
				slug: series.slug,
				coverImage: series.coverImage ?? null,
				description: series.description?.html ?? null,
			},
			roadmap,
			footerPosts,
		},
		revalidate: ARTICLE_REVALIDATE_SECONDS,
	};
};

export async function getStaticPaths() {
	return {
		paths: [],
		fallback: 'blocking',
	};
}
