import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Container } from '../../components/container';
import { AppProvider } from '../../components/contexts/appContext';
import { DateFormatter } from '../../components/date-formatter';
import { Footer } from '../../components/footer';
import { Layout } from '../../components/layout';
import { MarkdownToHtml } from '../../components/markdown-to-html';
import { PersonalHeader } from '../../components/personal-theme-header';
import { SeriesAiLearningPath } from '../../components/series-ai-learning-path';
import { getFooterPosts } from '../../lib/api/footerData';
import {
	PageByPublicationDocument,
	PageByPublicationQuery,
	PageByPublicationQueryVariables,
	PostFragment,
	PublicationFragment,
	SeriesPostsByPublicationDocument,
	SeriesPostsByPublicationQuery,
	SeriesPostsByPublicationQueryVariables,
} from '../../generated/graphql';

type SeriesInfo = {
	id: string;
	name: string;
	slug: string;
	coverImage?: string | null;
	description?: string | null;
};

type RoadmapPage = {
	title: string;
	markdown: string;
} | null;

type Props = {
	publication: PublicationFragment;
	posts: PostFragment[];
	series: SeriesInfo;
	roadmap: RoadmapPage;
	footerPosts: PostFragment[];
};

const UNCATEGORIZED = '__uncategorized__';

const toTitleCase = (str: string) =>
	str.replace(/\w\S*/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());

const RoadmapSection = ({ title, markdown }: { title: string; markdown: string }) => {
	const [open, setOpen] = useState(true);
	return (
		<div className="mb-12 rounded-xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 overflow-hidden">
			{/* Header */}
			<button
				onClick={() => setOpen((v) => !v)}
				className="w-full flex items-center justify-between gap-4 px-6 py-4 text-left hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors"
			>
				<div className="flex items-center gap-3">
					<span className="text-[10px] font-mono uppercase tracking-widest text-blue-500 dark:text-blue-400">
						Roadmap
					</span>
					<span className="text-base font-bold text-neutral-900 dark:text-neutral-50">
						{title}
					</span>
				</div>
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 20 20"
					fill="currentColor"
					className={`w-5 h-5 flex-shrink-0 text-neutral-400 dark:text-neutral-500 transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
				>
					<path fillRule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clipRule="evenodd" />
				</svg>
			</button>
			{/* Collapsible body */}
			{open && (
				<div className="px-6 pb-6 pt-2 border-t border-neutral-100 dark:border-neutral-800">
					<div className="prose prose-neutral dark:prose-invert max-w-none prose-headings:font-bold prose-headings:tracking-tight prose-a:text-blue-600 dark:prose-a:text-blue-400 prose-a:no-underline hover:prose-a:underline prose-code:text-sm">
						<MarkdownToHtml contentMarkdown={markdown} />
					</div>
				</div>
			)}
		</div>
	);
};

export default function SeriesDetailPage({ publication, posts, series, roadmap, footerPosts }: Props) {
	const title = `${series.name} - ${publication.title}`;
	const totalReadTime = posts.reduce((sum, p) => sum + (p.readTimeInMinutes ?? 0), 0);
	const latestDate = posts.length > 0
		? posts.reduce((latest, p) => (p.publishedAt > latest ? p.publishedAt : latest), posts[0].publishedAt)
		: null;

	// Build a stable global index map so step numbers always reflect series order
	const globalIndexMap = useMemo(() => {
		const m = new Map<string, number>();
		posts.forEach((p, i) => m.set(p.id, i));
		return m;
	}, [posts]);

	const [activeCategory, setActiveCategory] = useState<string | null>(null);

	const { categories, grouped } = useMemo(() => {
		const order: { slug: string; name: string }[] = [];
		const seenCats = new Set<string>();
		const map = new Map<string, PostFragment[]>();

		// Each post is assigned to its FIRST valid tag only (primary category).
		// This ensures every post appears exactly once — later groups show only the delta.
		for (const post of posts) {
			const tags = (post.tags ?? []).filter((t): t is NonNullable<typeof t> => !!t?.slug);
			const primaryTag = tags[0];

			if (!primaryTag) {
				// No tags → Uncategorized
				if (!seenCats.has(UNCATEGORIZED)) {
					seenCats.add(UNCATEGORIZED);
					order.push({ slug: UNCATEGORIZED, name: 'Uncategorized' });
				}
				map.set(UNCATEGORIZED, [...(map.get(UNCATEGORIZED) ?? []), post]);
			} else {
				// Only add to the primary (first) tag bucket
				if (!seenCats.has(primaryTag.slug)) {
					seenCats.add(primaryTag.slug);
					order.push({ slug: primaryTag.slug, name: toTitleCase(primaryTag.name ?? primaryTag.slug) });
				}
				map.set(primaryTag.slug, [...(map.get(primaryTag.slug) ?? []), post]);
			}
		}

		// Sort by post count descending (majority first); Uncategorized always last
		const sorted = order
			.filter(c => c.slug !== UNCATEGORIZED)
			.sort((a, b) => (map.get(b.slug)?.length ?? 0) - (map.get(a.slug)?.length ?? 0));
		if (seenCats.has(UNCATEGORIZED)) sorted.push({ slug: UNCATEGORIZED, name: 'Uncategorized' });

		return { categories: sorted, grouped: map };
	}, [posts]);

	const visibleCategories = useMemo(
		() => (activeCategory ? categories.filter(c => c.slug === activeCategory) : categories),
		[categories, activeCategory]
	);

	return (
		<AppProvider publication={publication} footerPosts={footerPosts}>
			<Layout>
				<Head>
					<title>{title}</title>
					<meta name="description" content={series.description ?? `Posts in the ${series.name} series`} />
					<meta property="og:title" content={title} />
					<meta property="og:description" content={series.description ?? `Posts in the ${series.name} series`} />
					<meta
						property="og:image"
						content={series.coverImage ?? publication.ogMetaData.image ?? getAutogeneratedPublicationOG(publication)}
					/>
					<meta property="twitter:card" content="summary_large_image" />
					<meta property="twitter:title" content={title} />
					<meta
						property="twitter:image"
						content={series.coverImage ?? publication.ogMetaData.image ?? getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{ __html: JSON.stringify(addPublicationJsonLd(publication)) }}
					/>
				</Head>
				<Container className="mx-auto w-full">
					<PersonalHeader />
					<div className="max-w-7xl mx-auto w-full px-5 pt-10 pb-20">

						{/* ── Back Navigation ── */}
						<Link
							href="/series"
							className="inline-flex items-center gap-1.5 text-sm text-neutral-400 dark:text-neutral-500 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-10 group"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								viewBox="0 0 20 20"
								fill="currentColor"
								className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform"
							>
								<path
									fillRule="evenodd"
									d="M17 10a.75.75 0 01-.75.75H5.612l4.158 3.96a.75.75 0 11-1.04 1.08l-5.5-5.25a.75.75 0 010-1.08l5.5-5.25a.75.75 0 111.04 1.08L5.612 9.25H16.25A.75.75 0 0117 10z"
									clipRule="evenodd"
								/>
							</svg>
							All Series
						</Link>

						{/* ── Series Hero ── */}
						<div className={`flex flex-col ${series.coverImage ? 'md:flex-row md:items-center md:gap-10' : ''} mb-12`}>
							{/* Left: label, title, description, meta */}
							<div className={series.coverImage ? 'flex-1 min-w-0' : 'w-full'}>
								<p className="text-[10px] font-mono uppercase tracking-widest text-blue-500 dark:text-blue-400 mb-2">
									Series
								</p>
								<h1 className="text-4xl md:text-5xl font-extrabold leading-[1.15] tracking-tight text-neutral-900 dark:text-neutral-50 mb-4 capitalize">
									{series.name}
								</h1>
								{series.description && (
									<div
										className="text-lg text-neutral-500 dark:text-neutral-400 leading-relaxed mb-4"
										dangerouslySetInnerHTML={{ __html: series.description }}
									/>
								)}

								{/* Meta row */}
								<div className="flex flex-wrap items-center gap-x-3 gap-y-2 pt-5 border-t border-neutral-100 dark:border-neutral-800">
									<span className="inline-flex items-center gap-1.5 text-sm text-neutral-500 dark:text-neutral-400">
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5">
											<path d="M10.75 16.82A7.462 7.462 0 0115 15.5c.71 0 1.396.098 2.046.282A.75.75 0 0018 15.06v-11a.75.75 0 00-.546-.721A9.006 9.006 0 0015 3a8.963 8.963 0 00-4.25 1.065V16.82zM9.25 4.065A8.963 8.963 0 005 3c-.85 0-1.673.118-2.454.339A.75.75 0 002 4.06v11a.75.75 0 00.954.721A7.506 7.506 0 015 15.5c1.579 0 3.042.487 4.25 1.32V4.065z" />
										</svg>
										{posts.length} article{posts.length !== 1 ? 's' : ''}
									</span>
									{totalReadTime > 0 && (
										<>
											<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
											<span className="inline-flex items-center gap-1 text-sm text-neutral-400 dark:text-neutral-500">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-3.5 h-3.5">
													<path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm.75-13a.75.75 0 00-1.5 0v5c0 .414.336.75.75.75h4a.75.75 0 000-1.5h-3.25V5z" clipRule="evenodd" />
												</svg>
												~{totalReadTime} min total
											</span>
										</>
									)}
									{latestDate && (
										<>
											<span className="text-neutral-200 dark:text-neutral-700 select-none">·</span>
											<span className="text-sm text-neutral-400 dark:text-neutral-500">
												Updated <DateFormatter dateString={latestDate} />
											</span>
										</>
									)}
								</div>
							</div>

							{/* Right: cover image */}
							{series.coverImage && (
								<div className="w-full md:w-2/5 shrink-0 mt-8 md:mt-0 h-52 md:h-64 rounded-xl overflow-hidden ring-1 ring-neutral-200 dark:ring-neutral-800 shadow-sm">
									<img
										src={series.coverImage}
										alt={series.name}
										className="w-full h-full object-cover"
									/>
								</div>
							)}
						</div>

						{/* ── Roadmap (static page) ── */}
						{roadmap && <RoadmapSection title={roadmap.title} markdown={roadmap.markdown} />}

						{/* ── AI Learning Path ── */}
						{posts.length > 0 && (
							<SeriesAiLearningPath seriesName={series.name} posts={posts} />
						)}
					</div>
					<Footer />
				</Container>
			</Layout>
		</AppProvider>
	);
}

type Params = {
	slug: string;
};

export const getStaticProps: GetStaticProps<Props, Params> = async ({ params }) => {
	if (!params) throw new Error('No params');

	const data = await request<SeriesPostsByPublicationQuery, SeriesPostsByPublicationQueryVariables>(
		process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
		SeriesPostsByPublicationDocument,
		{
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
			seriesSlug: params.slug,
			first: 20,
		},
	);

	const publication = data.publication;
	if (!publication || !publication.series) {
		return { notFound: true };
	}

	const { series } = publication;
	const posts = series.posts.edges.map((edge) => edge.node);
	const footerPosts = await getFooterPosts();

	// Try to fetch a matching static page (roadmap) using the series slug
	let roadmap: RoadmapPage = null;
	try {
		const pageData = await request<PageByPublicationQuery, PageByPublicationQueryVariables>(
			process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT,
			PageByPublicationDocument,
			{
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				slug: `${params.slug}-roadmap`,
			},
		);
		const page = pageData.publication?.staticPage;
		if (page && !page.hidden) {
			roadmap = {
				title: page.title,
				markdown: page.content.markdown,
			};
		}
	} catch {
		// No matching page — silently skip
	}

	return {
		props: {
			publication,
			posts,
			series: {
				id: series.id,
				name: series.name,
				slug: series.slug,
				coverImage: series.coverImage ?? null,
				description: series.description?.html ?? null,
			},
			roadmap,
			footerPosts,
		},
		revalidate: 1,
	};
};

export async function getStaticPaths() {
	return {
		paths: [],
		fallback: 'blocking',
	};
}
